// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ivpn/dns/proxy/model"
	mock "github.com/stretchr/testify/mock"
)

// NewCache creates a new instance of Cache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *Cache {
	mock := &Cache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Cache is an autogenerated mock type for the Cache type
type Cache struct {
	mock.Mock
}

type Cache_Expecter struct {
	mock *mock.Mock
}

func (_m *Cache) EXPECT() *Cache_Expecter {
	return &Cache_Expecter{mock: &_m.Mock}
}

// GetBlocklistEntry provides a mock function for the type Cache
func (_mock *Cache) GetBlocklistEntry(ctx context.Context, blocklistId string, domain string) (bool, error) {
	ret := _mock.Called(ctx, blocklistId, domain)

	if len(ret) == 0 {
		panic("no return value specified for GetBlocklistEntry")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, blocklistId, domain)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, blocklistId, domain)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, blocklistId, domain)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cache_GetBlocklistEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlocklistEntry'
type Cache_GetBlocklistEntry_Call struct {
	*mock.Call
}

// GetBlocklistEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - blocklistId string
//   - domain string
func (_e *Cache_Expecter) GetBlocklistEntry(ctx interface{}, blocklistId interface{}, domain interface{}) *Cache_GetBlocklistEntry_Call {
	return &Cache_GetBlocklistEntry_Call{Call: _e.mock.On("GetBlocklistEntry", ctx, blocklistId, domain)}
}

func (_c *Cache_GetBlocklistEntry_Call) Run(run func(ctx context.Context, blocklistId string, domain string)) *Cache_GetBlocklistEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Cache_GetBlocklistEntry_Call) Return(b bool, err error) *Cache_GetBlocklistEntry_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *Cache_GetBlocklistEntry_Call) RunAndReturn(run func(ctx context.Context, blocklistId string, domain string) (bool, error)) *Cache_GetBlocklistEntry_Call {
	_c.Call.Return(run)
	return _c
}

// GetCustomRulesHash provides a mock function for the type Cache
func (_mock *Cache) GetCustomRulesHash(ctx context.Context, hashId string) (map[string]string, error) {
	ret := _mock.Called(ctx, hashId)

	if len(ret) == 0 {
		panic("no return value specified for GetCustomRulesHash")
	}

	var r0 map[string]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (map[string]string, error)); ok {
		return returnFunc(ctx, hashId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) map[string]string); ok {
		r0 = returnFunc(ctx, hashId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, hashId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cache_GetCustomRulesHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCustomRulesHash'
type Cache_GetCustomRulesHash_Call struct {
	*mock.Call
}

// GetCustomRulesHash is a helper method to define mock.On call
//   - ctx context.Context
//   - hashId string
func (_e *Cache_Expecter) GetCustomRulesHash(ctx interface{}, hashId interface{}) *Cache_GetCustomRulesHash_Call {
	return &Cache_GetCustomRulesHash_Call{Call: _e.mock.On("GetCustomRulesHash", ctx, hashId)}
}

func (_c *Cache_GetCustomRulesHash_Call) Run(run func(ctx context.Context, hashId string)) *Cache_GetCustomRulesHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cache_GetCustomRulesHash_Call) Return(stringToString map[string]string, err error) *Cache_GetCustomRulesHash_Call {
	_c.Call.Return(stringToString, err)
	return _c
}

func (_c *Cache_GetCustomRulesHash_Call) RunAndReturn(run func(ctx context.Context, hashId string) (map[string]string, error)) *Cache_GetCustomRulesHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetCustomRulesHashes provides a mock function for the type Cache
func (_mock *Cache) GetCustomRulesHashes(ctx context.Context, profileId string) ([]string, error) {
	ret := _mock.Called(ctx, profileId)

	if len(ret) == 0 {
		panic("no return value specified for GetCustomRulesHashes")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return returnFunc(ctx, profileId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, profileId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, profileId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cache_GetCustomRulesHashes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCustomRulesHashes'
type Cache_GetCustomRulesHashes_Call struct {
	*mock.Call
}

// GetCustomRulesHashes is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
func (_e *Cache_Expecter) GetCustomRulesHashes(ctx interface{}, profileId interface{}) *Cache_GetCustomRulesHashes_Call {
	return &Cache_GetCustomRulesHashes_Call{Call: _e.mock.On("GetCustomRulesHashes", ctx, profileId)}
}

func (_c *Cache_GetCustomRulesHashes_Call) Run(run func(ctx context.Context, profileId string)) *Cache_GetCustomRulesHashes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cache_GetCustomRulesHashes_Call) Return(strings []string, err error) *Cache_GetCustomRulesHashes_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *Cache_GetCustomRulesHashes_Call) RunAndReturn(run func(ctx context.Context, profileId string) ([]string, error)) *Cache_GetCustomRulesHashes_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfileAdvancedSettings provides a mock function for the type Cache
func (_mock *Cache) GetProfileAdvancedSettings(ctx context.Context, profileId string) (map[string]string, error) {
	ret := _mock.Called(ctx, profileId)

	if len(ret) == 0 {
		panic("no return value specified for GetProfileAdvancedSettings")
	}

	var r0 map[string]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (map[string]string, error)); ok {
		return returnFunc(ctx, profileId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) map[string]string); ok {
		r0 = returnFunc(ctx, profileId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, profileId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cache_GetProfileAdvancedSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfileAdvancedSettings'
type Cache_GetProfileAdvancedSettings_Call struct {
	*mock.Call
}

// GetProfileAdvancedSettings is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
func (_e *Cache_Expecter) GetProfileAdvancedSettings(ctx interface{}, profileId interface{}) *Cache_GetProfileAdvancedSettings_Call {
	return &Cache_GetProfileAdvancedSettings_Call{Call: _e.mock.On("GetProfileAdvancedSettings", ctx, profileId)}
}

func (_c *Cache_GetProfileAdvancedSettings_Call) Run(run func(ctx context.Context, profileId string)) *Cache_GetProfileAdvancedSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cache_GetProfileAdvancedSettings_Call) Return(stringToString map[string]string, err error) *Cache_GetProfileAdvancedSettings_Call {
	_c.Call.Return(stringToString, err)
	return _c
}

func (_c *Cache_GetProfileAdvancedSettings_Call) RunAndReturn(run func(ctx context.Context, profileId string) (map[string]string, error)) *Cache_GetProfileAdvancedSettings_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfileBlocklists provides a mock function for the type Cache
func (_mock *Cache) GetProfileBlocklists(ctx context.Context, profileId string) ([]string, error) {
	ret := _mock.Called(ctx, profileId)

	if len(ret) == 0 {
		panic("no return value specified for GetProfileBlocklists")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return returnFunc(ctx, profileId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, profileId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, profileId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cache_GetProfileBlocklists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfileBlocklists'
type Cache_GetProfileBlocklists_Call struct {
	*mock.Call
}

// GetProfileBlocklists is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
func (_e *Cache_Expecter) GetProfileBlocklists(ctx interface{}, profileId interface{}) *Cache_GetProfileBlocklists_Call {
	return &Cache_GetProfileBlocklists_Call{Call: _e.mock.On("GetProfileBlocklists", ctx, profileId)}
}

func (_c *Cache_GetProfileBlocklists_Call) Run(run func(ctx context.Context, profileId string)) *Cache_GetProfileBlocklists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cache_GetProfileBlocklists_Call) Return(strings []string, err error) *Cache_GetProfileBlocklists_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *Cache_GetProfileBlocklists_Call) RunAndReturn(run func(ctx context.Context, profileId string) ([]string, error)) *Cache_GetProfileBlocklists_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfileDNSSECSettings provides a mock function for the type Cache
func (_mock *Cache) GetProfileDNSSECSettings(ctx context.Context, profileId string) (map[string]string, error) {
	ret := _mock.Called(ctx, profileId)

	if len(ret) == 0 {
		panic("no return value specified for GetProfileDNSSECSettings")
	}

	var r0 map[string]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (map[string]string, error)); ok {
		return returnFunc(ctx, profileId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) map[string]string); ok {
		r0 = returnFunc(ctx, profileId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, profileId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cache_GetProfileDNSSECSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfileDNSSECSettings'
type Cache_GetProfileDNSSECSettings_Call struct {
	*mock.Call
}

// GetProfileDNSSECSettings is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
func (_e *Cache_Expecter) GetProfileDNSSECSettings(ctx interface{}, profileId interface{}) *Cache_GetProfileDNSSECSettings_Call {
	return &Cache_GetProfileDNSSECSettings_Call{Call: _e.mock.On("GetProfileDNSSECSettings", ctx, profileId)}
}

func (_c *Cache_GetProfileDNSSECSettings_Call) Run(run func(ctx context.Context, profileId string)) *Cache_GetProfileDNSSECSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cache_GetProfileDNSSECSettings_Call) Return(stringToString map[string]string, err error) *Cache_GetProfileDNSSECSettings_Call {
	_c.Call.Return(stringToString, err)
	return _c
}

func (_c *Cache_GetProfileDNSSECSettings_Call) RunAndReturn(run func(ctx context.Context, profileId string) (map[string]string, error)) *Cache_GetProfileDNSSECSettings_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfileLogsSettings provides a mock function for the type Cache
func (_mock *Cache) GetProfileLogsSettings(ctx context.Context, profileId string) (map[string]string, error) {
	ret := _mock.Called(ctx, profileId)

	if len(ret) == 0 {
		panic("no return value specified for GetProfileLogsSettings")
	}

	var r0 map[string]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (map[string]string, error)); ok {
		return returnFunc(ctx, profileId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) map[string]string); ok {
		r0 = returnFunc(ctx, profileId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, profileId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cache_GetProfileLogsSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfileLogsSettings'
type Cache_GetProfileLogsSettings_Call struct {
	*mock.Call
}

// GetProfileLogsSettings is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
func (_e *Cache_Expecter) GetProfileLogsSettings(ctx interface{}, profileId interface{}) *Cache_GetProfileLogsSettings_Call {
	return &Cache_GetProfileLogsSettings_Call{Call: _e.mock.On("GetProfileLogsSettings", ctx, profileId)}
}

func (_c *Cache_GetProfileLogsSettings_Call) Run(run func(ctx context.Context, profileId string)) *Cache_GetProfileLogsSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cache_GetProfileLogsSettings_Call) Return(stringToString map[string]string, err error) *Cache_GetProfileLogsSettings_Call {
	_c.Call.Return(stringToString, err)
	return _c
}

func (_c *Cache_GetProfileLogsSettings_Call) RunAndReturn(run func(ctx context.Context, profileId string) (map[string]string, error)) *Cache_GetProfileLogsSettings_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfilePrivacySettings provides a mock function for the type Cache
func (_mock *Cache) GetProfilePrivacySettings(ctx context.Context, profileId string) (map[string]string, error) {
	ret := _mock.Called(ctx, profileId)

	if len(ret) == 0 {
		panic("no return value specified for GetProfilePrivacySettings")
	}

	var r0 map[string]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (map[string]string, error)); ok {
		return returnFunc(ctx, profileId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) map[string]string); ok {
		r0 = returnFunc(ctx, profileId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, profileId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cache_GetProfilePrivacySettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfilePrivacySettings'
type Cache_GetProfilePrivacySettings_Call struct {
	*mock.Call
}

// GetProfilePrivacySettings is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
func (_e *Cache_Expecter) GetProfilePrivacySettings(ctx interface{}, profileId interface{}) *Cache_GetProfilePrivacySettings_Call {
	return &Cache_GetProfilePrivacySettings_Call{Call: _e.mock.On("GetProfilePrivacySettings", ctx, profileId)}
}

func (_c *Cache_GetProfilePrivacySettings_Call) Run(run func(ctx context.Context, profileId string)) *Cache_GetProfilePrivacySettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cache_GetProfilePrivacySettings_Call) Return(stringToString map[string]string, err error) *Cache_GetProfilePrivacySettings_Call {
	_c.Call.Return(stringToString, err)
	return _c
}

func (_c *Cache_GetProfilePrivacySettings_Call) RunAndReturn(run func(ctx context.Context, profileId string) (map[string]string, error)) *Cache_GetProfilePrivacySettings_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfileServicesBlocked provides a mock function for the type Cache
func (_mock *Cache) GetProfileServicesBlocked(ctx context.Context, profileId string) ([]string, error) {
	ret := _mock.Called(ctx, profileId)

	if len(ret) == 0 {
		panic("no return value specified for GetProfileServicesBlocked")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return returnFunc(ctx, profileId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, profileId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, profileId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cache_GetProfileServicesBlocked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfileServicesBlocked'
type Cache_GetProfileServicesBlocked_Call struct {
	*mock.Call
}

// GetProfileServicesBlocked is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
func (_e *Cache_Expecter) GetProfileServicesBlocked(ctx interface{}, profileId interface{}) *Cache_GetProfileServicesBlocked_Call {
	return &Cache_GetProfileServicesBlocked_Call{Call: _e.mock.On("GetProfileServicesBlocked", ctx, profileId)}
}

func (_c *Cache_GetProfileServicesBlocked_Call) Run(run func(ctx context.Context, profileId string)) *Cache_GetProfileServicesBlocked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cache_GetProfileServicesBlocked_Call) Return(strings []string, err error) *Cache_GetProfileServicesBlocked_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *Cache_GetProfileServicesBlocked_Call) RunAndReturn(run func(ctx context.Context, profileId string) ([]string, error)) *Cache_GetProfileServicesBlocked_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfileSettingsBatch provides a mock function for the type Cache
func (_mock *Cache) GetProfileSettingsBatch(ctx context.Context, profileId string) (*model.ProfileSettings, error) {
	ret := _mock.Called(ctx, profileId)

	if len(ret) == 0 {
		panic("no return value specified for GetProfileSettingsBatch")
	}

	var r0 *model.ProfileSettings
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.ProfileSettings, error)); ok {
		return returnFunc(ctx, profileId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.ProfileSettings); ok {
		r0 = returnFunc(ctx, profileId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ProfileSettings)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, profileId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cache_GetProfileSettingsBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfileSettingsBatch'
type Cache_GetProfileSettingsBatch_Call struct {
	*mock.Call
}

// GetProfileSettingsBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
func (_e *Cache_Expecter) GetProfileSettingsBatch(ctx interface{}, profileId interface{}) *Cache_GetProfileSettingsBatch_Call {
	return &Cache_GetProfileSettingsBatch_Call{Call: _e.mock.On("GetProfileSettingsBatch", ctx, profileId)}
}

func (_c *Cache_GetProfileSettingsBatch_Call) Run(run func(ctx context.Context, profileId string)) *Cache_GetProfileSettingsBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cache_GetProfileSettingsBatch_Call) Return(profileSettings *model.ProfileSettings, err error) *Cache_GetProfileSettingsBatch_Call {
	_c.Call.Return(profileSettings, err)
	return _c
}

func (_c *Cache_GetProfileSettingsBatch_Call) RunAndReturn(run func(ctx context.Context, profileId string) (*model.ProfileSettings, error)) *Cache_GetProfileSettingsBatch_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfileStatisticsSettings provides a mock function for the type Cache
func (_mock *Cache) GetProfileStatisticsSettings(ctx context.Context, profileId string) (map[string]string, error) {
	ret := _mock.Called(ctx, profileId)

	if len(ret) == 0 {
		panic("no return value specified for GetProfileStatisticsSettings")
	}

	var r0 map[string]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (map[string]string, error)); ok {
		return returnFunc(ctx, profileId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) map[string]string); ok {
		r0 = returnFunc(ctx, profileId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, profileId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cache_GetProfileStatisticsSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfileStatisticsSettings'
type Cache_GetProfileStatisticsSettings_Call struct {
	*mock.Call
}

// GetProfileStatisticsSettings is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
func (_e *Cache_Expecter) GetProfileStatisticsSettings(ctx interface{}, profileId interface{}) *Cache_GetProfileStatisticsSettings_Call {
	return &Cache_GetProfileStatisticsSettings_Call{Call: _e.mock.On("GetProfileStatisticsSettings", ctx, profileId)}
}

func (_c *Cache_GetProfileStatisticsSettings_Call) Run(run func(ctx context.Context, profileId string)) *Cache_GetProfileStatisticsSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cache_GetProfileStatisticsSettings_Call) Return(stringToString map[string]string, err error) *Cache_GetProfileStatisticsSettings_Call {
	_c.Call.Return(stringToString, err)
	return _c
}

func (_c *Cache_GetProfileStatisticsSettings_Call) RunAndReturn(run func(ctx context.Context, profileId string) (map[string]string, error)) *Cache_GetProfileStatisticsSettings_Call {
	_c.Call.Return(run)
	return _c
}
