// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Cache is an autogenerated mock type for the Cache type
type Cache struct {
	mock.Mock
}

// GetBlocklistEntry provides a mock function with given fields: ctx, blocklistId, domain
func (_m *Cache) GetBlocklistEntry(ctx context.Context, blocklistId string, domain string) (bool, error) {
	ret := _m.Called(ctx, blocklistId, domain)

	if len(ret) == 0 {
		panic("no return value specified for GetBlocklistEntry")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, blocklistId, domain)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, blocklistId, domain)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, blocklistId, domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProfileAdvancedSettings provides a mock function with given fields: ctx, profileId
func (_m *Cache) GetProfileAdvancedSettings(ctx context.Context, profileId string) (map[string]string, error) {
	ret := _m.Called(ctx, profileId)

	if len(ret) == 0 {
		panic("no return value specified for GetProfileAdvancedSettings")
	}

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (map[string]string, error)); ok {
		return rf(ctx, profileId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) map[string]string); ok {
		r0 = rf(ctx, profileId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, profileId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProfileBlocklists provides a mock function with given fields: ctx, profileId
func (_m *Cache) GetProfileBlocklists(ctx context.Context, profileId string) ([]string, error) {
	ret := _m.Called(ctx, profileId)

	if len(ret) == 0 {
		panic("no return value specified for GetProfileBlocklists")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, profileId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, profileId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, profileId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProfileDNSSECSettings provides a mock function with given fields: ctx, profileId
func (_m *Cache) GetProfileDNSSECSettings(ctx context.Context, profileId string) (map[string]string, error) {
	ret := _m.Called(ctx, profileId)

	if len(ret) == 0 {
		panic("no return value specified for GetProfileDNSSECSettings")
	}

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (map[string]string, error)); ok {
		return rf(ctx, profileId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) map[string]string); ok {
		r0 = rf(ctx, profileId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, profileId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProfileLogsSettings provides a mock function with given fields: ctx, profileId
func (_m *Cache) GetProfileLogsSettings(ctx context.Context, profileId string) (map[string]string, error) {
	ret := _m.Called(ctx, profileId)

	if len(ret) == 0 {
		panic("no return value specified for GetProfileLogsSettings")
	}

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (map[string]string, error)); ok {
		return rf(ctx, profileId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) map[string]string); ok {
		r0 = rf(ctx, profileId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, profileId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProfilePrivacySettings provides a mock function with given fields: ctx, profileId
func (_m *Cache) GetProfilePrivacySettings(ctx context.Context, profileId string) (map[string]string, error) {
	ret := _m.Called(ctx, profileId)

	if len(ret) == 0 {
		panic("no return value specified for GetProfilePrivacySettings")
	}

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (map[string]string, error)); ok {
		return rf(ctx, profileId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) map[string]string); ok {
		r0 = rf(ctx, profileId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, profileId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProfileStatisticsSettings provides a mock function with given fields: ctx, profileId
func (_m *Cache) GetProfileStatisticsSettings(ctx context.Context, profileId string) (map[string]string, error) {
	ret := _m.Called(ctx, profileId)

	if len(ret) == 0 {
		panic("no return value specified for GetProfileStatisticsSettings")
	}

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (map[string]string, error)); ok {
		return rf(ctx, profileId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) map[string]string); ok {
		r0 = rf(ctx, profileId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, profileId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCustomRulesHash provides a mock function with given fields: ctx, hashId
func (_m *Cache) GetCustomRulesHash(ctx context.Context, hashId string) (map[string]string, error) {
	ret := _m.Called(ctx, hashId)

	if len(ret) == 0 {
		panic("no return value specified for GetCustomRulesHash")
	}

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (map[string]string, error)); ok {
		return rf(ctx, hashId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) map[string]string); ok {
		r0 = rf(ctx, hashId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, hashId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCustomRulesHashes provides a mock function with given fields: ctx, profileId
func (_m *Cache) GetCustomRulesHashes(ctx context.Context, profileId string) ([]string, error) {
	ret := _m.Called(ctx, profileId)

	if len(ret) == 0 {
		panic("no return value specified for GetCustomRulesHashes")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, profileId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, profileId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, profileId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCache creates a new instance of Cache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *Cache {
	mock := &Cache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
