// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// CollectorConfig is an autogenerated mock type for the CollectorConfig type
type CollectorConfig struct {
	mock.Mock
}

// GetBatchSize provides a mock function with no fields
func (_m *CollectorConfig) GetBatchSize() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBatchSize")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// GetFrequency provides a mock function with no fields
func (_m *CollectorConfig) GetFrequency() time.Duration {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetFrequency")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// NewCollectorConfig creates a new instance of CollectorConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCollectorConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *CollectorConfig {
	mock := &CollectorConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
