// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/ivpn/dns/proxy/model"
)

// Emitter is an autogenerated mock type for the Emitter type
type Emitter struct {
	mock.Mock
}

// Disconnect provides a mock function with no fields
func (_m *Emitter) Disconnect() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Disconnect")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EmitQueryLogs provides a mock function with given fields: ctx, data
func (_m *Emitter) EmitQueryLogs(ctx context.Context, data []model.EventQueryLog) error {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for EmitQueryLogs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []model.EventQueryLog) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EmitStatistics provides a mock function with given fields: ctx, data
func (_m *Emitter) EmitStatistics(ctx context.Context, data []model.EventStatistics) error {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for EmitStatistics")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []model.EventStatistics) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewEmitter creates a new instance of Emitter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEmitter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Emitter {
	mock := &Emitter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
