// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	quic "github.com/quic-go/quic-go"
	mock "github.com/stretchr/testify/mock"
)

// quicConnection is an autogenerated mock type for the quicConnection type
type quicConnection struct {
	mock.Mock
}

// ConnectionState provides a mock function with no fields
func (_m *quicConnection) ConnectionState() quic.ConnectionState {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ConnectionState")
	}

	var r0 quic.ConnectionState
	if rf, ok := ret.Get(0).(func() quic.ConnectionState); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(quic.ConnectionState)
	}

	return r0
}

// newQuicConnection creates a new instance of quicConnection. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newQuicConnection(t interface {
	mock.TestingT
	Cleanup(func())
}) *quicConnection {
	mock := &quicConnection{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
