// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	tls "crypto/tls"
)

// tlsConn is an autogenerated mock type for the tlsConn type
type tlsConn struct {
	mock.Mock
}

// ConnectionState provides a mock function with no fields
func (_m *tlsConn) ConnectionState() tls.ConnectionState {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ConnectionState")
	}

	var r0 tls.ConnectionState
	if rf, ok := ret.Get(0).(func() tls.ConnectionState); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(tls.ConnectionState)
	}

	return r0
}

// newTlsConn creates a new instance of tlsConn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newTlsConn(t interface {
	mock.TestingT
	Cleanup(func())
}) *tlsConn {
	mock := &tlsConn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
