services:
  mongodb:
    image: mongo:7.0.8
    networks:
      - dnsnetwork
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=dns
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./bootstrap/mongo:/docker-entrypoint-initdb.d
      - mongodb:/data/db
      - mongoconfig:/data/configdb
 
volumes:
  mongodb:
  mongoconfig:
