services:
  recursor_unbound:
    image: mvance/unbound:1.21.1
    restart: always
    command: /opt/unbound/sbin/unbound -vv -d -d -c /opt/unbound/etc/unbound/unbound.conf
    networks:
      dnsnetwork:
        ipv4_address: 10.5.0.6
    container_name: unbound
    volumes:
      - ./bootstrap/recursor:/opt/unbound/etc/unbound/
