# coding: utf-8

"""
    modDNS REST API

    modDNS REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moddns.models.model_security import ModelSecurity

class TestModelSecurity(unittest.TestCase):
    """ModelSecurity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelSecurity:
        """Test ModelSecurity
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelSecurity`
        """
        model = ModelSecurity()
        if include_optional:
            return ModelSecurity(
                dnssec = moddns.models.model/dnssec_settings.model.DNSSECSettings(
                    enabled = True, 
                    send_do_bit = True, )
            )
        else:
            return ModelSecurity(
                dnssec = moddns.models.model/dnssec_settings.model.DNSSECSettings(
                    enabled = True, 
                    send_do_bit = True, ),
        )
        """

    def testModelSecurity(self):
        """Test ModelSecurity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
