# coding: utf-8

"""
    modDNS REST API

    modDNS REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moddns.models.protocol_resident_key_requirement import ProtocolResidentKeyRequirement

class TestProtocolResidentKeyRequirement(unittest.TestCase):
    """ProtocolResidentKeyRequirement unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProtocolResidentKeyRequirement(self):
        """Test ProtocolResidentKeyRequirement"""
        # inst = ProtocolResidentKeyRequirement()

if __name__ == '__main__':
    unittest.main()
