# coding: utf-8

"""
    modDNS REST API

    modDNS REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moddns.models.model_profile_settings import ModelProfileSettings

class TestModelProfileSettings(unittest.TestCase):
    """ModelProfileSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelProfileSettings:
        """Test ModelProfileSettings
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelProfileSettings`
        """
        model = ModelProfileSettings()
        if include_optional:
            return ModelProfileSettings(
                advanced = moddns.models.model/advanced.model.Advanced(
                    recursor = '', ),
                custom_rules = [
                    moddns.models.model/custom_rule.model.CustomRule(
                        action = '', 
                        id = '', 
                        value = '', )
                    ],
                logs = moddns.models.model/logs_settings.model.LogsSettings(
                    enabled = True, 
                    log_clients_ips = True, 
                    log_domains = True, 
                    retention = '1h', ),
                privacy = moddns.models.model/privacy.model.Privacy(
                    blocklists = [
                        ''
                        ], 
                    default_rule = 'block', 
                    subdomains_rule = 'block', ),
                profile_id = '',
                security = moddns.models.model/security.model.Security(
                    dnssec = moddns.models.model/dnssec_settings.model.DNSSECSettings(
                        enabled = True, 
                        send_do_bit = True, ), ),
                statistics = moddns.models.model/statistics_settings.model.StatisticsSettings(
                    enabled = True, )
            )
        else:
            return ModelProfileSettings(
                advanced = moddns.models.model/advanced.model.Advanced(
                    recursor = '', ),
                logs = moddns.models.model/logs_settings.model.LogsSettings(
                    enabled = True, 
                    log_clients_ips = True, 
                    log_domains = True, 
                    retention = '1h', ),
                privacy = moddns.models.model/privacy.model.Privacy(
                    blocklists = [
                        ''
                        ], 
                    default_rule = 'block', 
                    subdomains_rule = 'block', ),
                profile_id = '',
                security = moddns.models.model/security.model.Security(
                    dnssec = moddns.models.model/dnssec_settings.model.DNSSECSettings(
                        enabled = True, 
                        send_do_bit = True, ), ),
                statistics = moddns.models.model/statistics_settings.model.StatisticsSettings(
                    enabled = True, ),
        )
        """

    def testModelProfileSettings(self):
        """Test ModelProfileSettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
