# coding: utf-8

"""
    modDNS REST API

    modDNS REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moddns.models.api_verify_email_otp_body import ApiVerifyEmailOTPBody

class TestApiVerifyEmailOTPBody(unittest.TestCase):
    """ApiVerifyEmailOTPBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiVerifyEmailOTPBody:
        """Test ApiVerifyEmailOTPBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiVerifyEmailOTPBody`
        """
        model = ApiVerifyEmailOTPBody()
        if include_optional:
            return ApiVerifyEmailOTPBody(
                otp = ''
            )
        else:
            return ApiVerifyEmailOTPBody(
                otp = '',
        )
        """

    def testApiVerifyEmailOTPBody(self):
        """Test ApiVerifyEmailOTPBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
