# coding: utf-8

"""
    modDNS REST API

    modDNS REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moddns.models.model_profile import ModelProfile

class TestModelProfile(unittest.TestCase):
    """ModelProfile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelProfile:
        """Test ModelProfile
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelProfile`
        """
        model = ModelProfile()
        if include_optional:
            return ModelProfile(
                account_id = '',
                id = '',
                name = '',
                profile_id = '',
                settings = moddns.models.model/profile_settings.model.ProfileSettings(
                    advanced = moddns.models.model/advanced.model.Advanced(
                        recursor = '', ), 
                    custom_rules = [
                        moddns.models.model/custom_rule.model.CustomRule(
                            action = '', 
                            id = '', 
                            value = '', )
                        ], 
                    logs = moddns.models.model/logs_settings.model.LogsSettings(
                        enabled = True, 
                        log_clients_ips = True, 
                        log_domains = True, 
                        retention = '1h', ), 
                    privacy = moddns.models.model/privacy.model.Privacy(
                        blocklists = [
                            ''
                            ], 
                        blocklists_subdomains_rule = 'block', 
                        custom_rules_subdomains_rule = 'include', 
                        default_rule = 'block', 
                        services = moddns.models.model/services_settings.model.ServicesSettings(
                            blocked = [
                                ''
                                ], ), ), 
                    profile_id = '', 
                    security = moddns.models.model/security.model.Security(
                        dnssec = moddns.models.model/dnssec_settings.model.DNSSECSettings(
                            enabled = True, 
                            send_do_bit = True, ), ), 
                    statistics = moddns.models.model/statistics_settings.model.StatisticsSettings(
                        enabled = True, ), )
            )
        else:
            return ModelProfile(
                account_id = '',
                id = '',
                name = '',
                profile_id = '',
                settings = moddns.models.model/profile_settings.model.ProfileSettings(
                    advanced = moddns.models.model/advanced.model.Advanced(
                        recursor = '', ), 
                    custom_rules = [
                        moddns.models.model/custom_rule.model.CustomRule(
                            action = '', 
                            id = '', 
                            value = '', )
                        ], 
                    logs = moddns.models.model/logs_settings.model.LogsSettings(
                        enabled = True, 
                        log_clients_ips = True, 
                        log_domains = True, 
                        retention = '1h', ), 
                    privacy = moddns.models.model/privacy.model.Privacy(
                        blocklists = [
                            ''
                            ], 
                        blocklists_subdomains_rule = 'block', 
                        custom_rules_subdomains_rule = 'include', 
                        default_rule = 'block', 
                        services = moddns.models.model/services_settings.model.ServicesSettings(
                            blocked = [
                                ''
                                ], ), ), 
                    profile_id = '', 
                    security = moddns.models.model/security.model.Security(
                        dnssec = moddns.models.model/dnssec_settings.model.DNSSECSettings(
                            enabled = True, 
                            send_do_bit = True, ), ), 
                    statistics = moddns.models.model/statistics_settings.model.StatisticsSettings(
                        enabled = True, ), ),
        )
        """

    def testModelProfile(self):
        """Test ModelProfile"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
