# coding: utf-8

"""
    modDNS REST API

    modDNS REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moddns.models.protocol_authenticator_attachment import ProtocolAuthenticatorAttachment

class TestProtocolAuthenticatorAttachment(unittest.TestCase):
    """ProtocolAuthenticatorAttachment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProtocolAuthenticatorAttachment(self):
        """Test ProtocolAuthenticatorAttachment"""
        # inst = ProtocolAuthenticatorAttachment()

if __name__ == '__main__':
    unittest.main()
