# coding: utf-8

"""
    modDNS REST API

    modDNS REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moddns.models.protocol_attestation_format import ProtocolAttestationFormat

class TestProtocolAttestationFormat(unittest.TestCase):
    """ProtocolAttestationFormat unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProtocolAttestationFormat(self):
        """Test ProtocolAttestationFormat"""
        # inst = ProtocolAttestationFormat()

if __name__ == '__main__':
    unittest.main()
