# coding: utf-8

"""
    modDNS REST API

    modDNS REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moddns.models.model_mfa_settings import ModelMFASettings

class TestModelMFASettings(unittest.TestCase):
    """ModelMFASettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelMFASettings:
        """Test ModelMFASettings
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelMFASettings`
        """
        model = ModelMFASettings()
        if include_optional:
            return ModelMFASettings(
                totp = moddns.models.model/totp_settings.model.TotpSettings(
                    enabled = True, )
            )
        else:
            return ModelMFASettings(
        )
        """

    def testModelMFASettings(self):
        """Test ModelMFASettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
