# coding: utf-8

"""
    modDNS REST API

    modDNS REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moddns.api.account_api import AccountApi


class TestAccountApi(unittest.TestCase):
    """AccountApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AccountApi()

    def tearDown(self) -> None:
        pass

    def test_api_v1_accounts_current_delete(self) -> None:
        """Test case for api_v1_accounts_current_delete

        Delete account
        """
        pass

    def test_api_v1_accounts_current_deletion_code_post(self) -> None:
        """Test case for api_v1_accounts_current_deletion_code_post

        Generate deletion code
        """
        pass

    def test_api_v1_accounts_current_get(self) -> None:
        """Test case for api_v1_accounts_current_get

        Get account data
        """
        pass

    def test_api_v1_accounts_mfa_totp_disable_post(self) -> None:
        """Test case for api_v1_accounts_mfa_totp_disable_post

        Disable TOTP
        """
        pass

    def test_api_v1_accounts_mfa_totp_enable_confirm_post(self) -> None:
        """Test case for api_v1_accounts_mfa_totp_enable_confirm_post

        Confirm TOTP
        """
        pass

    def test_api_v1_accounts_mfa_totp_enable_post(self) -> None:
        """Test case for api_v1_accounts_mfa_totp_enable_post

        Enable TOTP
        """
        pass

    def test_api_v1_accounts_patch(self) -> None:
        """Test case for api_v1_accounts_patch

        Update account
        """
        pass

    def test_api_v1_accounts_post(self) -> None:
        """Test case for api_v1_accounts_post

        Register account
        """
        pass

    def test_api_v1_accounts_reset_password_post(self) -> None:
        """Test case for api_v1_accounts_reset_password_post

        Send reset password email
        """
        pass


if __name__ == '__main__':
    unittest.main()
