# coding: utf-8

"""
    modDNS REST API

    modDNS REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moddns.models.webauthncose_cose_algorithm_identifier import WebauthncoseCOSEAlgorithmIdentifier

class TestWebauthncoseCOSEAlgorithmIdentifier(unittest.TestCase):
    """WebauthncoseCOSEAlgorithmIdentifier unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWebauthncoseCOSEAlgorithmIdentifier(self):
        """Test WebauthncoseCOSEAlgorithmIdentifier"""
        # inst = WebauthncoseCOSEAlgorithmIdentifier()

if __name__ == '__main__':
    unittest.main()
