# coding: utf-8

"""
    modDNS REST API

    modDNS REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moddns.models.servicescatalog_service import ServicescatalogService

class TestServicescatalogService(unittest.TestCase):
    """ServicescatalogService unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServicescatalogService:
        """Test ServicescatalogService
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServicescatalogService`
        """
        model = ServicescatalogService()
        if include_optional:
            return ServicescatalogService(
                asns = [
                    56
                    ],
                id = '',
                logo_key = '',
                name = ''
            )
        else:
            return ServicescatalogService(
        )
        """

    def testServicescatalogService(self):
        """Test ServicescatalogService"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
