# coding: utf-8

"""
    modDNS REST API

    modDNS REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moddns.models.model_query_log import ModelQueryLog

class TestModelQueryLog(unittest.TestCase):
    """ModelQueryLog unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelQueryLog:
        """Test ModelQueryLog
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelQueryLog`
        """
        model = ModelQueryLog()
        if include_optional:
            return ModelQueryLog(
                client_ip = '',
                device_id = '',
                dns_request = moddns.models.model/dns_request.model.DNSRequest(
                    dnssec = True, 
                    domain = '', 
                    query_type = '', 
                    response_code = '', ),
                id = '',
                profile_id = '',
                protocol = '',
                reasons = [
                    ''
                    ],
                status = '',
                timestamp = ''
            )
        else:
            return ModelQueryLog(
        )
        """

    def testModelQueryLog(self):
        """Test ModelQueryLog"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
