# coding: utf-8

"""
    modDNS REST API

    modDNS REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moddns.api.statistics_api import StatisticsApi


class TestStatisticsApi(unittest.TestCase):
    """StatisticsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StatisticsApi()

    def tearDown(self) -> None:
        pass

    def test_api_v1_profiles_id_statistics_get(self) -> None:
        """Test case for api_v1_profiles_id_statistics_get

        Get statistics data for a profile
        """
        pass


if __name__ == '__main__':
    unittest.main()
