# coding: utf-8

"""
    modDNS REST API

    modDNS REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moddns.models.requests_account_updates import RequestsAccountUpdates

class TestRequestsAccountUpdates(unittest.TestCase):
    """RequestsAccountUpdates unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestsAccountUpdates:
        """Test RequestsAccountUpdates
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestsAccountUpdates`
        """
        model = RequestsAccountUpdates()
        if include_optional:
            return RequestsAccountUpdates(
                updates = [
                    moddns.models.model/account_update.model.AccountUpdate(
                        operation = 'remove', 
                        path = '/password', 
                        value = moddns.models.value.value(), )
                    ]
            )
        else:
            return RequestsAccountUpdates(
                updates = [
                    moddns.models.model/account_update.model.AccountUpdate(
                        operation = 'remove', 
                        path = '/password', 
                        value = moddns.models.value.value(), )
                    ],
        )
        """

    def testRequestsAccountUpdates(self):
        """Test RequestsAccountUpdates"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
