# coding: utf-8

"""
    modDNS REST API

    modDNS REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moddns.models.protocol_credential_creation import ProtocolCredentialCreation

class TestProtocolCredentialCreation(unittest.TestCase):
    """ProtocolCredentialCreation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProtocolCredentialCreation:
        """Test ProtocolCredentialCreation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProtocolCredentialCreation`
        """
        model = ProtocolCredentialCreation()
        if include_optional:
            return ProtocolCredentialCreation(
                mediation = 'silent',
                public_key = moddns.models.protocol/public_key_credential_creation_options.protocol.PublicKeyCredentialCreationOptions(
                    attestation = 'none', 
                    attestation_formats = [
                        'packed'
                        ], 
                    authenticator_selection = moddns.models.protocol/authenticator_selection.protocol.AuthenticatorSelection(
                        authenticator_attachment = moddns.models.authenticator_attachment.authenticatorAttachment(), 
                        require_resident_key = True, 
                        resident_key = moddns.models.resident_key.residentKey(), 
                        user_verification = moddns.models.user_verification.userVerification(), ), 
                    challenge = [
                        56
                        ], 
                    exclude_credentials = [
                        moddns.models.protocol/credential_descriptor.protocol.CredentialDescriptor(
                            id = [
                                56
                                ], 
                            transports = [
                                'usb'
                                ], 
                            type = moddns.models.type.type(), )
                        ], 
                    extensions = {
                        'key' : None
                        }, 
                    hints = [
                        'security-key'
                        ], 
                    pub_key_cred_params = [
                        moddns.models.protocol/credential_parameter.protocol.CredentialParameter(
                            alg = -7, 
                            type = 'public-key', )
                        ], 
                    rp = moddns.models.protocol/relying_party_entity.protocol.RelyingPartyEntity(
                        name = '', ), 
                    timeout = 56, 
                    user = moddns.models.protocol/user_entity.protocol.UserEntity(
                        display_name = '', 
                        name = '', ), )
            )
        else:
            return ProtocolCredentialCreation(
        )
        """

    def testProtocolCredentialCreation(self):
        """Test ProtocolCredentialCreation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
