# coding: utf-8

"""
    modDNS REST API

    modDNS REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moddns.models.api_register_account_body import ApiRegisterAccountBody

class TestApiRegisterAccountBody(unittest.TestCase):
    """ApiRegisterAccountBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiRegisterAccountBody:
        """Test ApiRegisterAccountBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiRegisterAccountBody`
        """
        model = ApiRegisterAccountBody()
        if include_optional:
            return ApiRegisterAccountBody(
                email = '',
                password = '',
                subid = ''
            )
        else:
            return ApiRegisterAccountBody(
                email = '',
                password = '',
                subid = '',
        )
        """

    def testApiRegisterAccountBody(self):
        """Test ApiRegisterAccountBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
