# coding: utf-8

"""
    modDNS REST API

    modDNS REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moddns.models.api_blocklists_updates import ApiBlocklistsUpdates

class TestApiBlocklistsUpdates(unittest.TestCase):
    """ApiBlocklistsUpdates unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiBlocklistsUpdates:
        """Test ApiBlocklistsUpdates
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiBlocklistsUpdates`
        """
        model = ApiBlocklistsUpdates()
        if include_optional:
            return ApiBlocklistsUpdates(
                blocklist_ids = [
                    ''
                    ]
            )
        else:
            return ApiBlocklistsUpdates(
                blocklist_ids = [
                    ''
                    ],
        )
        """

    def testApiBlocklistsUpdates(self):
        """Test ApiBlocklistsUpdates"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
