# coding: utf-8

"""
    modDNS REST API

    modDNS REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moddns.models.protocol_credential_assertion import ProtocolCredentialAssertion

class TestProtocolCredentialAssertion(unittest.TestCase):
    """ProtocolCredentialAssertion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProtocolCredentialAssertion:
        """Test ProtocolCredentialAssertion
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProtocolCredentialAssertion`
        """
        model = ProtocolCredentialAssertion()
        if include_optional:
            return ProtocolCredentialAssertion(
                mediation = 'silent',
                public_key = moddns.models.protocol/public_key_credential_request_options.protocol.PublicKeyCredentialRequestOptions(
                    allow_credentials = [
                        moddns.models.protocol/credential_descriptor.protocol.CredentialDescriptor(
                            id = [
                                56
                                ], 
                            transports = [
                                'usb'
                                ], 
                            type = moddns.models.type.type(), )
                        ], 
                    challenge = [
                        56
                        ], 
                    extensions = {
                        'key' : None
                        }, 
                    hints = [
                        'security-key'
                        ], 
                    rp_id = '', 
                    timeout = 56, 
                    user_verification = 'required', )
            )
        else:
            return ProtocolCredentialAssertion(
        )
        """

    def testProtocolCredentialAssertion(self):
        """Test ProtocolCredentialAssertion"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
