# coding: utf-8

"""
    modDNS REST API

    modDNS REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moddns.models.responses_deletion_code_response import ResponsesDeletionCodeResponse

class TestResponsesDeletionCodeResponse(unittest.TestCase):
    """ResponsesDeletionCodeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponsesDeletionCodeResponse:
        """Test ResponsesDeletionCodeResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponsesDeletionCodeResponse`
        """
        model = ResponsesDeletionCodeResponse()
        if include_optional:
            return ResponsesDeletionCodeResponse(
                code = '',
                expires_at = ''
            )
        else:
            return ResponsesDeletionCodeResponse(
        )
        """

    def testResponsesDeletionCodeResponse(self):
        """Test ResponsesDeletionCodeResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
