# coding: utf-8

"""
    modDNS REST API

    modDNS REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moddns.api.verification_api import VerificationApi


class TestVerificationApi(unittest.TestCase):
    """VerificationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = VerificationApi()

    def tearDown(self) -> None:
        pass

    def test_api_v1_verify_email_otp_confirm_post(self) -> None:
        """Test case for api_v1_verify_email_otp_confirm_post

        Confirm email verification OTP
        """
        pass

    def test_api_v1_verify_email_otp_request_post(self) -> None:
        """Test case for api_v1_verify_email_otp_request_post

        Request email verification OTP
        """
        pass

    def test_api_v1_verify_reset_password_post(self) -> None:
        """Test case for api_v1_verify_reset_password_post

        Confirm password reset
        """
        pass


if __name__ == '__main__':
    unittest.main()
