# coding: utf-8

"""
    modDNS REST API

    modDNS REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moddns.api.blocklists_api import BlocklistsApi


class TestBlocklistsApi(unittest.TestCase):
    """BlocklistsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BlocklistsApi()

    def tearDown(self) -> None:
        pass

    def test_api_v1_blocklists_get(self) -> None:
        """Test case for api_v1_blocklists_get

        Get blocklists data
        """
        pass


if __name__ == '__main__':
    unittest.main()
