# coding: utf-8

"""
    modDNS REST API

    modDNS REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moddns.models.requests_subscription_req import RequestsSubscriptionReq

class TestRequestsSubscriptionReq(unittest.TestCase):
    """RequestsSubscriptionReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestsSubscriptionReq:
        """Test RequestsSubscriptionReq
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestsSubscriptionReq`
        """
        model = RequestsSubscriptionReq()
        if include_optional:
            return RequestsSubscriptionReq(
                active_until = '',
                id = ''
            )
        else:
            return RequestsSubscriptionReq(
                active_until = '',
                id = '',
        )
        """

    def testRequestsSubscriptionReq(self):
        """Test RequestsSubscriptionReq"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
