# coding: utf-8

"""
    modDNS REST API

    modDNS REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moddns.models.model_blocklist import ModelBlocklist

class TestModelBlocklist(unittest.TestCase):
    """ModelBlocklist unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelBlocklist:
        """Test ModelBlocklist
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelBlocklist`
        """
        model = ModelBlocklist()
        if include_optional:
            return ModelBlocklist(
                blocklist_id = '',
                default = True,
                description = '',
                entries = 56,
                homepage = '',
                id = '',
                last_modified = '',
                name = '',
                source_url = '',
                tags = [
                    ''
                    ],
                type = ''
            )
        else:
            return ModelBlocklist(
                blocklist_id = '',
                description = '',
                name = '',
        )
        """

    def testModelBlocklist(self):
        """Test ModelBlocklist"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
