# coding: utf-8

"""
    modDNS REST API

    modDNS REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moddns.api.authentication_api import AuthenticationApi


class TestAuthenticationApi(unittest.TestCase):
    """AuthenticationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthenticationApi()

    def tearDown(self) -> None:
        pass

    def test_api_v1_accounts_logout_post(self) -> None:
        """Test case for api_v1_accounts_logout_post

        Logout
        """
        pass

    def test_api_v1_login_post(self) -> None:
        """Test case for api_v1_login_post

        Login
        """
        pass

    def test_api_v1_webauthn_login_begin_post(self) -> None:
        """Test case for api_v1_webauthn_login_begin_post

        Begin passkey login
        """
        pass

    def test_api_v1_webauthn_login_finish_post(self) -> None:
        """Test case for api_v1_webauthn_login_finish_post

        Finish passkey login
        """
        pass

    def test_api_v1_webauthn_passkey_add_begin_post(self) -> None:
        """Test case for api_v1_webauthn_passkey_add_begin_post

        Add new passkey
        """
        pass

    def test_api_v1_webauthn_passkey_add_finish_post(self) -> None:
        """Test case for api_v1_webauthn_passkey_add_finish_post

        Complete adding new passkey
        """
        pass

    def test_api_v1_webauthn_passkey_id_delete(self) -> None:
        """Test case for api_v1_webauthn_passkey_id_delete

        Delete passkey
        """
        pass

    def test_api_v1_webauthn_passkey_reauth_begin_post(self) -> None:
        """Test case for api_v1_webauthn_passkey_reauth_begin_post

        Begin reauthentication via passkey
        """
        pass

    def test_api_v1_webauthn_passkey_reauth_finish_post(self) -> None:
        """Test case for api_v1_webauthn_passkey_reauth_finish_post

        Finish reauthentication via passkey
        """
        pass

    def test_api_v1_webauthn_passkeys_get(self) -> None:
        """Test case for api_v1_webauthn_passkeys_get

        Get user passkeys
        """
        pass

    def test_api_v1_webauthn_register_begin_post(self) -> None:
        """Test case for api_v1_webauthn_register_begin_post

        Begin passkey registration
        """
        pass

    def test_api_v1_webauthn_register_finish_post(self) -> None:
        """Test case for api_v1_webauthn_register_finish_post

        Finish passkey registration
        """
        pass


if __name__ == '__main__':
    unittest.main()
