# coding: utf-8

"""
    modDNS REST API

    modDNS REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from moddns.models.protocol_attestation_format import ProtocolAttestationFormat
from moddns.models.protocol_authenticator_selection import ProtocolAuthenticatorSelection
from moddns.models.protocol_conveyance_preference import ProtocolConveyancePreference
from moddns.models.protocol_credential_descriptor import ProtocolCredentialDescriptor
from moddns.models.protocol_credential_parameter import ProtocolCredentialParameter
from moddns.models.protocol_public_key_credential_hints import ProtocolPublicKeyCredentialHints
from moddns.models.protocol_relying_party_entity import ProtocolRelyingPartyEntity
from moddns.models.protocol_user_entity import ProtocolUserEntity
from typing import Optional, Set
from typing_extensions import Self

class ProtocolPublicKeyCredentialCreationOptions(BaseModel):
    """
    ProtocolPublicKeyCredentialCreationOptions
    """ # noqa: E501
    attestation: Optional[ProtocolConveyancePreference] = None
    attestation_formats: Optional[List[ProtocolAttestationFormat]] = Field(default=None, alias="attestationFormats")
    authenticator_selection: Optional[ProtocolAuthenticatorSelection] = Field(default=None, alias="authenticatorSelection")
    challenge: Optional[List[StrictInt]] = None
    exclude_credentials: Optional[List[ProtocolCredentialDescriptor]] = Field(default=None, alias="excludeCredentials")
    extensions: Optional[Dict[str, Dict[str, Any]]] = None
    hints: Optional[List[ProtocolPublicKeyCredentialHints]] = None
    pub_key_cred_params: Optional[List[ProtocolCredentialParameter]] = Field(default=None, alias="pubKeyCredParams")
    rp: Optional[ProtocolRelyingPartyEntity] = None
    timeout: Optional[StrictInt] = None
    user: Optional[ProtocolUserEntity] = None
    __properties: ClassVar[List[str]] = ["attestation", "attestationFormats", "authenticatorSelection", "challenge", "excludeCredentials", "extensions", "hints", "pubKeyCredParams", "rp", "timeout", "user"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProtocolPublicKeyCredentialCreationOptions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of authenticator_selection
        if self.authenticator_selection:
            _dict['authenticatorSelection'] = self.authenticator_selection.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in exclude_credentials (list)
        _items = []
        if self.exclude_credentials:
            for _item_exclude_credentials in self.exclude_credentials:
                if _item_exclude_credentials:
                    _items.append(_item_exclude_credentials.to_dict())
            _dict['excludeCredentials'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in pub_key_cred_params (list)
        _items = []
        if self.pub_key_cred_params:
            for _item_pub_key_cred_params in self.pub_key_cred_params:
                if _item_pub_key_cred_params:
                    _items.append(_item_pub_key_cred_params.to_dict())
            _dict['pubKeyCredParams'] = _items
        # override the default output from pydantic by calling `to_dict()` of rp
        if self.rp:
            _dict['rp'] = self.rp.to_dict()
        # override the default output from pydantic by calling `to_dict()` of user
        if self.user:
            _dict['user'] = self.user.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProtocolPublicKeyCredentialCreationOptions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "attestation": obj.get("attestation"),
            "attestationFormats": obj.get("attestationFormats"),
            "authenticatorSelection": ProtocolAuthenticatorSelection.from_dict(obj["authenticatorSelection"]) if obj.get("authenticatorSelection") is not None else None,
            "challenge": obj.get("challenge"),
            "excludeCredentials": [ProtocolCredentialDescriptor.from_dict(_item) for _item in obj["excludeCredentials"]] if obj.get("excludeCredentials") is not None else None,
            "extensions": obj.get("extensions"),
            "hints": obj.get("hints"),
            "pubKeyCredParams": [ProtocolCredentialParameter.from_dict(_item) for _item in obj["pubKeyCredParams"]] if obj.get("pubKeyCredParams") is not None else None,
            "rp": ProtocolRelyingPartyEntity.from_dict(obj["rp"]) if obj.get("rp") is not None else None,
            "timeout": obj.get("timeout"),
            "user": ProtocolUserEntity.from_dict(obj["user"]) if obj.get("user") is not None else None
        })
        return _obj


