# coding: utf-8

"""
    modDNS REST API

    modDNS REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ProtocolPublicKeyCredentialHints(str, Enum):
    """
    ProtocolPublicKeyCredentialHints
    """

    """
    allowed enum values
    """
    SECURITY_MINUS_KEY = 'security-key'
    CLIENT_MINUS_DEVICE = 'client-device'
    HYBRID = 'hybrid'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ProtocolPublicKeyCredentialHints from a JSON string"""
        return cls(json.loads(json_str))


