# coding: utf-8

"""
    modDNS REST API

    modDNS REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ProtocolAuthenticatorAttachment(str, Enum):
    """
    ProtocolAuthenticatorAttachment
    """

    """
    allowed enum values
    """
    PLATFORM = 'platform'
    CROSS_MINUS_PLATFORM = 'cross-platform'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ProtocolAuthenticatorAttachment from a JSON string"""
        return cls(json.loads(json_str))


