# coding: utf-8

"""
    modDNS REST API

    modDNS REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from moddns.models.protocol_authenticator_attachment import ProtocolAuthenticatorAttachment
from moddns.models.protocol_resident_key_requirement import ProtocolResidentKeyRequirement
from moddns.models.protocol_user_verification_requirement import ProtocolUserVerificationRequirement
from typing import Optional, Set
from typing_extensions import Self

class ProtocolAuthenticatorSelection(BaseModel):
    """
    ProtocolAuthenticatorSelection
    """ # noqa: E501
    authenticator_attachment: Optional[ProtocolAuthenticatorAttachment] = Field(default=None, description="AuthenticatorAttachment If this member is present, eligible authenticators are filtered to only authenticators attached with the specified AuthenticatorAttachment enum.", alias="authenticatorAttachment")
    require_resident_key: Optional[StrictBool] = Field(default=None, description="RequireResidentKey this member describes the Relying Party's requirements regarding resident credentials. If the parameter is set to true, the authenticator MUST create a client-side-resident public key credential source when creating a public key credential.", alias="requireResidentKey")
    resident_key: Optional[ProtocolResidentKeyRequirement] = Field(default=None, description="ResidentKey this member describes the Relying Party's requirements regarding resident credentials per Webauthn Level 2.", alias="residentKey")
    user_verification: Optional[ProtocolUserVerificationRequirement] = Field(default=None, description="UserVerification This member describes the Relying Party's requirements regarding user verification for the create() operation. Eligible authenticators are filtered to only those capable of satisfying this requirement.", alias="userVerification")
    __properties: ClassVar[List[str]] = ["authenticatorAttachment", "requireResidentKey", "residentKey", "userVerification"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProtocolAuthenticatorSelection from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProtocolAuthenticatorSelection from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "authenticatorAttachment": obj.get("authenticatorAttachment"),
            "requireResidentKey": obj.get("requireResidentKey"),
            "residentKey": obj.get("residentKey"),
            "userVerification": obj.get("userVerification")
        })
        return _obj


