# coding: utf-8

"""
    modDNS REST API

    modDNS REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from moddns.models.responses_custom_rule_batch_created import ResponsesCustomRuleBatchCreated
from moddns.models.responses_custom_rule_batch_skipped import ResponsesCustomRuleBatchSkipped
from typing import Optional, Set
from typing_extensions import Self

class ResponsesCreateProfileCustomRulesBatchResponse(BaseModel):
    """
    ResponsesCreateProfileCustomRulesBatchResponse
    """ # noqa: E501
    action: Optional[StrictStr] = None
    created: Optional[List[ResponsesCustomRuleBatchCreated]] = None
    skipped: Optional[List[ResponsesCustomRuleBatchSkipped]] = None
    total_requested: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["action", "created", "skipped", "total_requested"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ResponsesCreateProfileCustomRulesBatchResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in created (list)
        _items = []
        if self.created:
            for _item_created in self.created:
                if _item_created:
                    _items.append(_item_created.to_dict())
            _dict['created'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in skipped (list)
        _items = []
        if self.skipped:
            for _item_skipped in self.skipped:
                if _item_skipped:
                    _items.append(_item_skipped.to_dict())
            _dict['skipped'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ResponsesCreateProfileCustomRulesBatchResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "action": obj.get("action"),
            "created": [ResponsesCustomRuleBatchCreated.from_dict(_item) for _item in obj["created"]] if obj.get("created") is not None else None,
            "skipped": [ResponsesCustomRuleBatchSkipped.from_dict(_item) for _item in obj["skipped"]] if obj.get("skipped") is not None else None,
            "total_requested": obj.get("total_requested")
        })
        return _obj


