# coding: utf-8

"""
    modDNS REST API

    modDNS REST API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class WebauthncoseCOSEAlgorithmIdentifier(int, Enum):
    """
    WebauthncoseCOSEAlgorithmIdentifier
    """

    """
    allowed enum values
    """
    AlgES256 = -7
    AlgEdDSA = -8
    AlgES384 = -35
    AlgES512 = -36
    AlgPS256 = -37
    AlgPS384 = -38
    AlgPS512 = -39
    AlgES256K = -47
    AlgRS256 = -257
    AlgRS384 = -258
    AlgRS512 = -259
    AlgRS1 = -65535

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of WebauthncoseCOSEAlgorithmIdentifier from a JSON string"""
        return cls(json.loads(json_str))


