FROM golang:1.24.5

RUN apt update; apt install -y make

WORKDIR /app

# Copy golang dependency manifests
COPY go.mod /app
COPY go.sum /app

# Cache the downloaded dependency in the layer.
RUN go mod download

COPY . /app/
RUN GOOS=linux GOARCH=amd64 go build -o /app/dnscheck -v .
CMD ["./dnscheck"]
