FROM golang:1.23.2

RUN apt update; apt install -y make

WORKDIR /app

# Copy golang dependency manifests
COPY proxy/go.mod .
COPY proxy/go.sum .

# Copy the DNS libs
COPY ../libs/ /libs

# Cache the downloaded dependency in the layer.
RUN go mod download
RUN go mod verify

COPY proxy/ .

RUN GOOS=linux GOARCH=amd64 go build -o /app/dnsfilter -v .
CMD ["./dnsfilter"]
