FROM golang:1.25.8

RUN apt update; apt install -y make

WORKDIR /app

# Copy golang dependency manifests
COPY blocklists/go.mod .
COPY blocklists/go.sum .

# Copy the DNS libs
COPY ../libs/ /libs

# Cache the downloaded dependency in the layer.
RUN go mod download
RUN go mod vendor

COPY blocklists/ .

RUN GOOS=linux GOARCH=amd64 go build -o /app/blocklists -v .
CMD ["./blocklists"]
