// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/ivpn/dns/api/model"
	mock "github.com/stretchr/testify/mock"
)

// NewAccountRepository creates a new instance of AccountRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountRepository {
	mock := &AccountRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AccountRepository is an autogenerated mock type for the AccountRepository type
type AccountRepository struct {
	mock.Mock
}

type AccountRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *AccountRepository) EXPECT() *AccountRepository_Expecter {
	return &AccountRepository_Expecter{mock: &_m.Mock}
}

// AddProfileToAccount provides a mock function for the type AccountRepository
func (_mock *AccountRepository) AddProfileToAccount(ctx context.Context, accountId string, profileId string) error {
	ret := _mock.Called(ctx, accountId, profileId)

	if len(ret) == 0 {
		panic("no return value specified for AddProfileToAccount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, accountId, profileId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AccountRepository_AddProfileToAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddProfileToAccount'
type AccountRepository_AddProfileToAccount_Call struct {
	*mock.Call
}

// AddProfileToAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
//   - profileId string
func (_e *AccountRepository_Expecter) AddProfileToAccount(ctx interface{}, accountId interface{}, profileId interface{}) *AccountRepository_AddProfileToAccount_Call {
	return &AccountRepository_AddProfileToAccount_Call{Call: _e.mock.On("AddProfileToAccount", ctx, accountId, profileId)}
}

func (_c *AccountRepository_AddProfileToAccount_Call) Run(run func(ctx context.Context, accountId string, profileId string)) *AccountRepository_AddProfileToAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AccountRepository_AddProfileToAccount_Call) Return(err error) *AccountRepository_AddProfileToAccount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AccountRepository_AddProfileToAccount_Call) RunAndReturn(run func(ctx context.Context, accountId string, profileId string) error) *AccountRepository_AddProfileToAccount_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAccount provides a mock function for the type AccountRepository
func (_mock *AccountRepository) CreateAccount(ctx context.Context, email string, password string, accountId string, profileId string) (*model.Account, error) {
	ret := _mock.Called(ctx, email, password, accountId, profileId)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccount")
	}

	var r0 *model.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*model.Account, error)); ok {
		return returnFunc(ctx, email, password, accountId, profileId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) *model.Account); ok {
		r0 = returnFunc(ctx, email, password, accountId, profileId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = returnFunc(ctx, email, password, accountId, profileId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AccountRepository_CreateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccount'
type AccountRepository_CreateAccount_Call struct {
	*mock.Call
}

// CreateAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
//   - accountId string
//   - profileId string
func (_e *AccountRepository_Expecter) CreateAccount(ctx interface{}, email interface{}, password interface{}, accountId interface{}, profileId interface{}) *AccountRepository_CreateAccount_Call {
	return &AccountRepository_CreateAccount_Call{Call: _e.mock.On("CreateAccount", ctx, email, password, accountId, profileId)}
}

func (_c *AccountRepository_CreateAccount_Call) Run(run func(ctx context.Context, email string, password string, accountId string, profileId string)) *AccountRepository_CreateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *AccountRepository_CreateAccount_Call) Return(account *model.Account, err error) *AccountRepository_CreateAccount_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *AccountRepository_CreateAccount_Call) RunAndReturn(run func(ctx context.Context, email string, password string, accountId string, profileId string) (*model.Account, error)) *AccountRepository_CreateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAccountById provides a mock function for the type AccountRepository
func (_mock *AccountRepository) DeleteAccountById(ctx context.Context, accountId string) error {
	ret := _mock.Called(ctx, accountId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAccountById")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, accountId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AccountRepository_DeleteAccountById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAccountById'
type AccountRepository_DeleteAccountById_Call struct {
	*mock.Call
}

// DeleteAccountById is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
func (_e *AccountRepository_Expecter) DeleteAccountById(ctx interface{}, accountId interface{}) *AccountRepository_DeleteAccountById_Call {
	return &AccountRepository_DeleteAccountById_Call{Call: _e.mock.On("DeleteAccountById", ctx, accountId)}
}

func (_c *AccountRepository_DeleteAccountById_Call) Run(run func(ctx context.Context, accountId string)) *AccountRepository_DeleteAccountById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AccountRepository_DeleteAccountById_Call) Return(err error) *AccountRepository_DeleteAccountById_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AccountRepository_DeleteAccountById_Call) RunAndReturn(run func(ctx context.Context, accountId string) error) *AccountRepository_DeleteAccountById_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccount provides a mock function for the type AccountRepository
func (_mock *AccountRepository) GetAccount(ctx context.Context, accountId string) (*model.Account, error) {
	ret := _mock.Called(ctx, accountId)

	if len(ret) == 0 {
		panic("no return value specified for GetAccount")
	}

	var r0 *model.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Account, error)); ok {
		return returnFunc(ctx, accountId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Account); ok {
		r0 = returnFunc(ctx, accountId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accountId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AccountRepository_GetAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccount'
type AccountRepository_GetAccount_Call struct {
	*mock.Call
}

// GetAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
func (_e *AccountRepository_Expecter) GetAccount(ctx interface{}, accountId interface{}) *AccountRepository_GetAccount_Call {
	return &AccountRepository_GetAccount_Call{Call: _e.mock.On("GetAccount", ctx, accountId)}
}

func (_c *AccountRepository_GetAccount_Call) Run(run func(ctx context.Context, accountId string)) *AccountRepository_GetAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AccountRepository_GetAccount_Call) Return(account *model.Account, err error) *AccountRepository_GetAccount_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *AccountRepository_GetAccount_Call) RunAndReturn(run func(ctx context.Context, accountId string) (*model.Account, error)) *AccountRepository_GetAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccountByEmail provides a mock function for the type AccountRepository
func (_mock *AccountRepository) GetAccountByEmail(ctx context.Context, email string) (*model.Account, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountByEmail")
	}

	var r0 *model.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Account, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Account); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AccountRepository_GetAccountByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountByEmail'
type AccountRepository_GetAccountByEmail_Call struct {
	*mock.Call
}

// GetAccountByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *AccountRepository_Expecter) GetAccountByEmail(ctx interface{}, email interface{}) *AccountRepository_GetAccountByEmail_Call {
	return &AccountRepository_GetAccountByEmail_Call{Call: _e.mock.On("GetAccountByEmail", ctx, email)}
}

func (_c *AccountRepository_GetAccountByEmail_Call) Run(run func(ctx context.Context, email string)) *AccountRepository_GetAccountByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AccountRepository_GetAccountByEmail_Call) Return(account *model.Account, err error) *AccountRepository_GetAccountByEmail_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *AccountRepository_GetAccountByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*model.Account, error)) *AccountRepository_GetAccountByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccountById provides a mock function for the type AccountRepository
func (_mock *AccountRepository) GetAccountById(ctx context.Context, accountId string) (*model.Account, error) {
	ret := _mock.Called(ctx, accountId)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountById")
	}

	var r0 *model.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Account, error)); ok {
		return returnFunc(ctx, accountId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Account); ok {
		r0 = returnFunc(ctx, accountId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accountId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AccountRepository_GetAccountById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountById'
type AccountRepository_GetAccountById_Call struct {
	*mock.Call
}

// GetAccountById is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
func (_e *AccountRepository_Expecter) GetAccountById(ctx interface{}, accountId interface{}) *AccountRepository_GetAccountById_Call {
	return &AccountRepository_GetAccountById_Call{Call: _e.mock.On("GetAccountById", ctx, accountId)}
}

func (_c *AccountRepository_GetAccountById_Call) Run(run func(ctx context.Context, accountId string)) *AccountRepository_GetAccountById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AccountRepository_GetAccountById_Call) Return(account *model.Account, err error) *AccountRepository_GetAccountById_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *AccountRepository_GetAccountById_Call) RunAndReturn(run func(ctx context.Context, accountId string) (*model.Account, error)) *AccountRepository_GetAccountById_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccountByToken provides a mock function for the type AccountRepository
func (_mock *AccountRepository) GetAccountByToken(ctx context.Context, token string, tokenType string) (*model.Account, error) {
	ret := _mock.Called(ctx, token, tokenType)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountByToken")
	}

	var r0 *model.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*model.Account, error)); ok {
		return returnFunc(ctx, token, tokenType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *model.Account); ok {
		r0 = returnFunc(ctx, token, tokenType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, token, tokenType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AccountRepository_GetAccountByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountByToken'
type AccountRepository_GetAccountByToken_Call struct {
	*mock.Call
}

// GetAccountByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - tokenType string
func (_e *AccountRepository_Expecter) GetAccountByToken(ctx interface{}, token interface{}, tokenType interface{}) *AccountRepository_GetAccountByToken_Call {
	return &AccountRepository_GetAccountByToken_Call{Call: _e.mock.On("GetAccountByToken", ctx, token, tokenType)}
}

func (_c *AccountRepository_GetAccountByToken_Call) Run(run func(ctx context.Context, token string, tokenType string)) *AccountRepository_GetAccountByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AccountRepository_GetAccountByToken_Call) Return(account *model.Account, err error) *AccountRepository_GetAccountByToken_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *AccountRepository_GetAccountByToken_Call) RunAndReturn(run func(ctx context.Context, token string, tokenType string) (*model.Account, error)) *AccountRepository_GetAccountByToken_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveProfileFromAccount provides a mock function for the type AccountRepository
func (_mock *AccountRepository) RemoveProfileFromAccount(ctx context.Context, accountId string, profileId string) error {
	ret := _mock.Called(ctx, accountId, profileId)

	if len(ret) == 0 {
		panic("no return value specified for RemoveProfileFromAccount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, accountId, profileId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AccountRepository_RemoveProfileFromAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveProfileFromAccount'
type AccountRepository_RemoveProfileFromAccount_Call struct {
	*mock.Call
}

// RemoveProfileFromAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
//   - profileId string
func (_e *AccountRepository_Expecter) RemoveProfileFromAccount(ctx interface{}, accountId interface{}, profileId interface{}) *AccountRepository_RemoveProfileFromAccount_Call {
	return &AccountRepository_RemoveProfileFromAccount_Call{Call: _e.mock.On("RemoveProfileFromAccount", ctx, accountId, profileId)}
}

func (_c *AccountRepository_RemoveProfileFromAccount_Call) Run(run func(ctx context.Context, accountId string, profileId string)) *AccountRepository_RemoveProfileFromAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AccountRepository_RemoveProfileFromAccount_Call) Return(err error) *AccountRepository_RemoveProfileFromAccount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AccountRepository_RemoveProfileFromAccount_Call) RunAndReturn(run func(ctx context.Context, accountId string, profileId string) error) *AccountRepository_RemoveProfileFromAccount_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAccount provides a mock function for the type AccountRepository
func (_mock *AccountRepository) UpdateAccount(ctx context.Context, account *model.Account) (*model.Account, error) {
	ret := _mock.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAccount")
	}

	var r0 *model.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Account) (*model.Account, error)); ok {
		return returnFunc(ctx, account)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Account) *model.Account); ok {
		r0 = returnFunc(ctx, account)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.Account) error); ok {
		r1 = returnFunc(ctx, account)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AccountRepository_UpdateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAccount'
type AccountRepository_UpdateAccount_Call struct {
	*mock.Call
}

// UpdateAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - account *model.Account
func (_e *AccountRepository_Expecter) UpdateAccount(ctx interface{}, account interface{}) *AccountRepository_UpdateAccount_Call {
	return &AccountRepository_UpdateAccount_Call{Call: _e.mock.On("UpdateAccount", ctx, account)}
}

func (_c *AccountRepository_UpdateAccount_Call) Run(run func(ctx context.Context, account *model.Account)) *AccountRepository_UpdateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Account
		if args[1] != nil {
			arg1 = args[1].(*model.Account)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AccountRepository_UpdateAccount_Call) Return(account1 *model.Account, err error) *AccountRepository_UpdateAccount_Call {
	_c.Call.Return(account1, err)
	return _c
}

func (_c *AccountRepository_UpdateAccount_Call) RunAndReturn(run func(ctx context.Context, account *model.Account) (*model.Account, error)) *AccountRepository_UpdateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDeletionCode provides a mock function for the type AccountRepository
func (_mock *AccountRepository) UpdateDeletionCode(ctx context.Context, accountId string, code string, expiresAt time.Time) error {
	ret := _mock.Called(ctx, accountId, code, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDeletionCode")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Time) error); ok {
		r0 = returnFunc(ctx, accountId, code, expiresAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AccountRepository_UpdateDeletionCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDeletionCode'
type AccountRepository_UpdateDeletionCode_Call struct {
	*mock.Call
}

// UpdateDeletionCode is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
//   - code string
//   - expiresAt time.Time
func (_e *AccountRepository_Expecter) UpdateDeletionCode(ctx interface{}, accountId interface{}, code interface{}, expiresAt interface{}) *AccountRepository_UpdateDeletionCode_Call {
	return &AccountRepository_UpdateDeletionCode_Call{Call: _e.mock.On("UpdateDeletionCode", ctx, accountId, code, expiresAt)}
}

func (_c *AccountRepository_UpdateDeletionCode_Call) Run(run func(ctx context.Context, accountId string, code string, expiresAt time.Time)) *AccountRepository_UpdateDeletionCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *AccountRepository_UpdateDeletionCode_Call) Return(err error) *AccountRepository_UpdateDeletionCode_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AccountRepository_UpdateDeletionCode_Call) RunAndReturn(run func(ctx context.Context, accountId string, code string, expiresAt time.Time) error) *AccountRepository_UpdateDeletionCode_Call {
	_c.Call.Return(run)
	return _c
}
