// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ivpn/dns/api/api/requests"
	mock "github.com/stretchr/testify/mock"
)

// NewAppleServicer creates a new instance of AppleServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAppleServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *AppleServicer {
	mock := &AppleServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AppleServicer is an autogenerated mock type for the AppleServicer type
type AppleServicer struct {
	mock.Mock
}

type AppleServicer_Expecter struct {
	mock *mock.Mock
}

func (_m *AppleServicer) EXPECT() *AppleServicer_Expecter {
	return &AppleServicer_Expecter{mock: &_m.Mock}
}

// GenerateMobileConfig provides a mock function for the type AppleServicer
func (_mock *AppleServicer) GenerateMobileConfig(ctx context.Context, req requests.MobileConfigReq, accountId string, genLink bool) ([]byte, string, error) {
	ret := _mock.Called(ctx, req, accountId, genLink)

	if len(ret) == 0 {
		panic("no return value specified for GenerateMobileConfig")
	}

	var r0 []byte
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, requests.MobileConfigReq, string, bool) ([]byte, string, error)); ok {
		return returnFunc(ctx, req, accountId, genLink)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, requests.MobileConfigReq, string, bool) []byte); ok {
		r0 = returnFunc(ctx, req, accountId, genLink)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, requests.MobileConfigReq, string, bool) string); ok {
		r1 = returnFunc(ctx, req, accountId, genLink)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, requests.MobileConfigReq, string, bool) error); ok {
		r2 = returnFunc(ctx, req, accountId, genLink)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// AppleServicer_GenerateMobileConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateMobileConfig'
type AppleServicer_GenerateMobileConfig_Call struct {
	*mock.Call
}

// GenerateMobileConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - req requests.MobileConfigReq
//   - accountId string
//   - genLink bool
func (_e *AppleServicer_Expecter) GenerateMobileConfig(ctx interface{}, req interface{}, accountId interface{}, genLink interface{}) *AppleServicer_GenerateMobileConfig_Call {
	return &AppleServicer_GenerateMobileConfig_Call{Call: _e.mock.On("GenerateMobileConfig", ctx, req, accountId, genLink)}
}

func (_c *AppleServicer_GenerateMobileConfig_Call) Run(run func(ctx context.Context, req requests.MobileConfigReq, accountId string, genLink bool)) *AppleServicer_GenerateMobileConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 requests.MobileConfigReq
		if args[1] != nil {
			arg1 = args[1].(requests.MobileConfigReq)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *AppleServicer_GenerateMobileConfig_Call) Return(data []byte, link string, err error) *AppleServicer_GenerateMobileConfig_Call {
	_c.Call.Return(data, link, err)
	return _c
}

func (_c *AppleServicer_GenerateMobileConfig_Call) RunAndReturn(run func(ctx context.Context, req requests.MobileConfigReq, accountId string, genLink bool) ([]byte, string, error)) *AppleServicer_GenerateMobileConfig_Call {
	_c.Call.Return(run)
	return _c
}
