// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/ivpn/dns/api/model"
	mock "github.com/stretchr/testify/mock"
)

// NewCachecache creates a new instance of Cachecache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCachecache(t interface {
	mock.TestingT
	Cleanup(func())
}) *Cachecache {
	mock := &Cachecache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Cachecache is an autogenerated mock type for the Cache type
type Cachecache struct {
	mock.Mock
}

type Cachecache_Expecter struct {
	mock *mock.Mock
}

func (_m *Cachecache) EXPECT() *Cachecache_Expecter {
	return &Cachecache_Expecter{mock: &_m.Mock}
}

// AddBlocklist provides a mock function for the type Cachecache
func (_mock *Cachecache) AddBlocklist(ctx context.Context, blocklistId string, data []byte) error {
	ret := _mock.Called(ctx, blocklistId, data)

	if len(ret) == 0 {
		panic("no return value specified for AddBlocklist")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = returnFunc(ctx, blocklistId, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Cachecache_AddBlocklist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddBlocklist'
type Cachecache_AddBlocklist_Call struct {
	*mock.Call
}

// AddBlocklist is a helper method to define mock.On call
//   - ctx context.Context
//   - blocklistId string
//   - data []byte
func (_e *Cachecache_Expecter) AddBlocklist(ctx interface{}, blocklistId interface{}, data interface{}) *Cachecache_AddBlocklist_Call {
	return &Cachecache_AddBlocklist_Call{Call: _e.mock.On("AddBlocklist", ctx, blocklistId, data)}
}

func (_c *Cachecache_AddBlocklist_Call) Run(run func(ctx context.Context, blocklistId string, data []byte)) *Cachecache_AddBlocklist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Cachecache_AddBlocklist_Call) Return(err error) *Cachecache_AddBlocklist_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Cachecache_AddBlocklist_Call) RunAndReturn(run func(ctx context.Context, blocklistId string, data []byte) error) *Cachecache_AddBlocklist_Call {
	_c.Call.Return(run)
	return _c
}

// AddCustomRule provides a mock function for the type Cachecache
func (_mock *Cachecache) AddCustomRule(ctx context.Context, profileId string, customRule *model.CustomRule) error {
	ret := _mock.Called(ctx, profileId, customRule)

	if len(ret) == 0 {
		panic("no return value specified for AddCustomRule")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.CustomRule) error); ok {
		r0 = returnFunc(ctx, profileId, customRule)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Cachecache_AddCustomRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddCustomRule'
type Cachecache_AddCustomRule_Call struct {
	*mock.Call
}

// AddCustomRule is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
//   - customRule *model.CustomRule
func (_e *Cachecache_Expecter) AddCustomRule(ctx interface{}, profileId interface{}, customRule interface{}) *Cachecache_AddCustomRule_Call {
	return &Cachecache_AddCustomRule_Call{Call: _e.mock.On("AddCustomRule", ctx, profileId, customRule)}
}

func (_c *Cachecache_AddCustomRule_Call) Run(run func(ctx context.Context, profileId string, customRule *model.CustomRule)) *Cachecache_AddCustomRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *model.CustomRule
		if args[2] != nil {
			arg2 = args[2].(*model.CustomRule)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Cachecache_AddCustomRule_Call) Return(err error) *Cachecache_AddCustomRule_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Cachecache_AddCustomRule_Call) RunAndReturn(run func(ctx context.Context, profileId string, customRule *model.CustomRule) error) *Cachecache_AddCustomRule_Call {
	_c.Call.Return(run)
	return _c
}

// AddSubscription provides a mock function for the type Cachecache
func (_mock *Cachecache) AddSubscription(ctx context.Context, subscriptionId string, activeUntil string, expiresIn time.Duration) error {
	ret := _mock.Called(ctx, subscriptionId, activeUntil, expiresIn)

	if len(ret) == 0 {
		panic("no return value specified for AddSubscription")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) error); ok {
		r0 = returnFunc(ctx, subscriptionId, activeUntil, expiresIn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Cachecache_AddSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddSubscription'
type Cachecache_AddSubscription_Call struct {
	*mock.Call
}

// AddSubscription is a helper method to define mock.On call
//   - ctx context.Context
//   - subscriptionId string
//   - activeUntil string
//   - expiresIn time.Duration
func (_e *Cachecache_Expecter) AddSubscription(ctx interface{}, subscriptionId interface{}, activeUntil interface{}, expiresIn interface{}) *Cachecache_AddSubscription_Call {
	return &Cachecache_AddSubscription_Call{Call: _e.mock.On("AddSubscription", ctx, subscriptionId, activeUntil, expiresIn)}
}

func (_c *Cachecache_AddSubscription_Call) Run(run func(ctx context.Context, subscriptionId string, activeUntil string, expiresIn time.Duration)) *Cachecache_AddSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Cachecache_AddSubscription_Call) Return(err error) *Cachecache_AddSubscription_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Cachecache_AddSubscription_Call) RunAndReturn(run func(ctx context.Context, subscriptionId string, activeUntil string, expiresIn time.Duration) error) *Cachecache_AddSubscription_Call {
	_c.Call.Return(run)
	return _c
}

// AppendBlocklistsToProfileSettings provides a mock function for the type Cachecache
func (_mock *Cachecache) AppendBlocklistsToProfileSettings(ctx context.Context, profileId string, blocklistIds ...string) error {
	var tmpRet mock.Arguments
	if len(blocklistIds) > 0 {
		tmpRet = _mock.Called(ctx, profileId, blocklistIds)
	} else {
		tmpRet = _mock.Called(ctx, profileId)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for AppendBlocklistsToProfileSettings")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...string) error); ok {
		r0 = returnFunc(ctx, profileId, blocklistIds...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Cachecache_AppendBlocklistsToProfileSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppendBlocklistsToProfileSettings'
type Cachecache_AppendBlocklistsToProfileSettings_Call struct {
	*mock.Call
}

// AppendBlocklistsToProfileSettings is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
//   - blocklistIds ...string
func (_e *Cachecache_Expecter) AppendBlocklistsToProfileSettings(ctx interface{}, profileId interface{}, blocklistIds ...interface{}) *Cachecache_AppendBlocklistsToProfileSettings_Call {
	return &Cachecache_AppendBlocklistsToProfileSettings_Call{Call: _e.mock.On("AppendBlocklistsToProfileSettings",
		append([]interface{}{ctx, profileId}, blocklistIds...)...)}
}

func (_c *Cachecache_AppendBlocklistsToProfileSettings_Call) Run(run func(ctx context.Context, profileId string, blocklistIds ...string)) *Cachecache_AppendBlocklistsToProfileSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		var variadicArgs []string
		if len(args) > 2 {
			variadicArgs = args[2].([]string)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Cachecache_AppendBlocklistsToProfileSettings_Call) Return(err error) *Cachecache_AppendBlocklistsToProfileSettings_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Cachecache_AppendBlocklistsToProfileSettings_Call) RunAndReturn(run func(ctx context.Context, profileId string, blocklistIds ...string) error) *Cachecache_AppendBlocklistsToProfileSettings_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrUpdateProfileSettings provides a mock function for the type Cachecache
func (_mock *Cachecache) CreateOrUpdateProfileSettings(ctx context.Context, settings *model.ProfileSettings, rollback bool) error {
	ret := _mock.Called(ctx, settings, rollback)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrUpdateProfileSettings")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ProfileSettings, bool) error); ok {
		r0 = returnFunc(ctx, settings, rollback)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Cachecache_CreateOrUpdateProfileSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrUpdateProfileSettings'
type Cachecache_CreateOrUpdateProfileSettings_Call struct {
	*mock.Call
}

// CreateOrUpdateProfileSettings is a helper method to define mock.On call
//   - ctx context.Context
//   - settings *model.ProfileSettings
//   - rollback bool
func (_e *Cachecache_Expecter) CreateOrUpdateProfileSettings(ctx interface{}, settings interface{}, rollback interface{}) *Cachecache_CreateOrUpdateProfileSettings_Call {
	return &Cachecache_CreateOrUpdateProfileSettings_Call{Call: _e.mock.On("CreateOrUpdateProfileSettings", ctx, settings, rollback)}
}

func (_c *Cachecache_CreateOrUpdateProfileSettings_Call) Run(run func(ctx context.Context, settings *model.ProfileSettings, rollback bool)) *Cachecache_CreateOrUpdateProfileSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.ProfileSettings
		if args[1] != nil {
			arg1 = args[1].(*model.ProfileSettings)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Cachecache_CreateOrUpdateProfileSettings_Call) Return(err error) *Cachecache_CreateOrUpdateProfileSettings_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Cachecache_CreateOrUpdateProfileSettings_Call) RunAndReturn(run func(ctx context.Context, settings *model.ProfileSettings, rollback bool) error) *Cachecache_CreateOrUpdateProfileSettings_Call {
	_c.Call.Return(run)
	return _c
}

// Del provides a mock function for the type Cachecache
func (_mock *Cachecache) Del(context1 context.Context, s string) error {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for Del")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Cachecache_Del_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Del'
type Cachecache_Del_Call struct {
	*mock.Call
}

// Del is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *Cachecache_Expecter) Del(context1 interface{}, s interface{}) *Cachecache_Del_Call {
	return &Cachecache_Del_Call{Call: _e.mock.On("Del", context1, s)}
}

func (_c *Cachecache_Del_Call) Run(run func(context1 context.Context, s string)) *Cachecache_Del_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cachecache_Del_Call) Return(err error) *Cachecache_Del_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Cachecache_Del_Call) RunAndReturn(run func(context1 context.Context, s string) error) *Cachecache_Del_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProfileSettings provides a mock function for the type Cachecache
func (_mock *Cachecache) DeleteProfileSettings(ctx context.Context, profileId string) error {
	ret := _mock.Called(ctx, profileId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProfileSettings")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, profileId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Cachecache_DeleteProfileSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProfileSettings'
type Cachecache_DeleteProfileSettings_Call struct {
	*mock.Call
}

// DeleteProfileSettings is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
func (_e *Cachecache_Expecter) DeleteProfileSettings(ctx interface{}, profileId interface{}) *Cachecache_DeleteProfileSettings_Call {
	return &Cachecache_DeleteProfileSettings_Call{Call: _e.mock.On("DeleteProfileSettings", ctx, profileId)}
}

func (_c *Cachecache_DeleteProfileSettings_Call) Run(run func(ctx context.Context, profileId string)) *Cachecache_DeleteProfileSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cachecache_DeleteProfileSettings_Call) Return(err error) *Cachecache_DeleteProfileSettings_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Cachecache_DeleteProfileSettings_Call) RunAndReturn(run func(ctx context.Context, profileId string) error) *Cachecache_DeleteProfileSettings_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type Cachecache
func (_mock *Cachecache) Get(context1 context.Context, s string) (string, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cachecache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Cachecache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *Cachecache_Expecter) Get(context1 interface{}, s interface{}) *Cachecache_Get_Call {
	return &Cachecache_Get_Call{Call: _e.mock.On("Get", context1, s)}
}

func (_c *Cachecache_Get_Call) Run(run func(context1 context.Context, s string)) *Cachecache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cachecache_Get_Call) Return(s1 string, err error) *Cachecache_Get_Call {
	_c.Call.Return(s1, err)
	return _c
}

func (_c *Cachecache_Get_Call) RunAndReturn(run func(context1 context.Context, s string) (string, error)) *Cachecache_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubscription provides a mock function for the type Cachecache
func (_mock *Cachecache) GetSubscription(ctx context.Context, subscriptionId string) (string, error) {
	ret := _mock.Called(ctx, subscriptionId)

	if len(ret) == 0 {
		panic("no return value specified for GetSubscription")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, subscriptionId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, subscriptionId)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, subscriptionId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cachecache_GetSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubscription'
type Cachecache_GetSubscription_Call struct {
	*mock.Call
}

// GetSubscription is a helper method to define mock.On call
//   - ctx context.Context
//   - subscriptionId string
func (_e *Cachecache_Expecter) GetSubscription(ctx interface{}, subscriptionId interface{}) *Cachecache_GetSubscription_Call {
	return &Cachecache_GetSubscription_Call{Call: _e.mock.On("GetSubscription", ctx, subscriptionId)}
}

func (_c *Cachecache_GetSubscription_Call) Run(run func(ctx context.Context, subscriptionId string)) *Cachecache_GetSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cachecache_GetSubscription_Call) Return(s string, err error) *Cachecache_GetSubscription_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Cachecache_GetSubscription_Call) RunAndReturn(run func(ctx context.Context, subscriptionId string) (string, error)) *Cachecache_GetSubscription_Call {
	_c.Call.Return(run)
	return _c
}

// GetTOTPSecret provides a mock function for the type Cachecache
func (_mock *Cachecache) GetTOTPSecret(ctx context.Context, accountId string) (string, error) {
	ret := _mock.Called(ctx, accountId)

	if len(ret) == 0 {
		panic("no return value specified for GetTOTPSecret")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, accountId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, accountId)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accountId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cachecache_GetTOTPSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTOTPSecret'
type Cachecache_GetTOTPSecret_Call struct {
	*mock.Call
}

// GetTOTPSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
func (_e *Cachecache_Expecter) GetTOTPSecret(ctx interface{}, accountId interface{}) *Cachecache_GetTOTPSecret_Call {
	return &Cachecache_GetTOTPSecret_Call{Call: _e.mock.On("GetTOTPSecret", ctx, accountId)}
}

func (_c *Cachecache_GetTOTPSecret_Call) Run(run func(ctx context.Context, accountId string)) *Cachecache_GetTOTPSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cachecache_GetTOTPSecret_Call) Return(s string, err error) *Cachecache_GetTOTPSecret_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Cachecache_GetTOTPSecret_Call) RunAndReturn(run func(ctx context.Context, accountId string) (string, error)) *Cachecache_GetTOTPSecret_Call {
	_c.Call.Return(run)
	return _c
}

// Incr provides a mock function for the type Cachecache
func (_mock *Cachecache) Incr(context1 context.Context, s string, duration time.Duration) (int64, error) {
	ret := _mock.Called(context1, s, duration)

	if len(ret) == 0 {
		panic("no return value specified for Incr")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) (int64, error)); ok {
		return returnFunc(context1, s, duration)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) int64); ok {
		r0 = returnFunc(context1, s, duration)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Duration) error); ok {
		r1 = returnFunc(context1, s, duration)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cachecache_Incr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Incr'
type Cachecache_Incr_Call struct {
	*mock.Call
}

// Incr is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - duration time.Duration
func (_e *Cachecache_Expecter) Incr(context1 interface{}, s interface{}, duration interface{}) *Cachecache_Incr_Call {
	return &Cachecache_Incr_Call{Call: _e.mock.On("Incr", context1, s, duration)}
}

func (_c *Cachecache_Incr_Call) Run(run func(context1 context.Context, s string, duration time.Duration)) *Cachecache_Incr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Cachecache_Incr_Call) Return(n int64, err error) *Cachecache_Incr_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *Cachecache_Incr_Call) RunAndReturn(run func(context1 context.Context, s string, duration time.Duration) (int64, error)) *Cachecache_Incr_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveBlocklistsFromProfileSettings provides a mock function for the type Cachecache
func (_mock *Cachecache) RemoveBlocklistsFromProfileSettings(ctx context.Context, profileId string, blocklistIds ...string) error {
	var tmpRet mock.Arguments
	if len(blocklistIds) > 0 {
		tmpRet = _mock.Called(ctx, profileId, blocklistIds)
	} else {
		tmpRet = _mock.Called(ctx, profileId)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for RemoveBlocklistsFromProfileSettings")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...string) error); ok {
		r0 = returnFunc(ctx, profileId, blocklistIds...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Cachecache_RemoveBlocklistsFromProfileSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveBlocklistsFromProfileSettings'
type Cachecache_RemoveBlocklistsFromProfileSettings_Call struct {
	*mock.Call
}

// RemoveBlocklistsFromProfileSettings is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
//   - blocklistIds ...string
func (_e *Cachecache_Expecter) RemoveBlocklistsFromProfileSettings(ctx interface{}, profileId interface{}, blocklistIds ...interface{}) *Cachecache_RemoveBlocklistsFromProfileSettings_Call {
	return &Cachecache_RemoveBlocklistsFromProfileSettings_Call{Call: _e.mock.On("RemoveBlocklistsFromProfileSettings",
		append([]interface{}{ctx, profileId}, blocklistIds...)...)}
}

func (_c *Cachecache_RemoveBlocklistsFromProfileSettings_Call) Run(run func(ctx context.Context, profileId string, blocklistIds ...string)) *Cachecache_RemoveBlocklistsFromProfileSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		var variadicArgs []string
		if len(args) > 2 {
			variadicArgs = args[2].([]string)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Cachecache_RemoveBlocklistsFromProfileSettings_Call) Return(err error) *Cachecache_RemoveBlocklistsFromProfileSettings_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Cachecache_RemoveBlocklistsFromProfileSettings_Call) RunAndReturn(run func(ctx context.Context, profileId string, blocklistIds ...string) error) *Cachecache_RemoveBlocklistsFromProfileSettings_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveCustomRule provides a mock function for the type Cachecache
func (_mock *Cachecache) RemoveCustomRule(ctx context.Context, profileId string, customRuleId string) error {
	ret := _mock.Called(ctx, profileId, customRuleId)

	if len(ret) == 0 {
		panic("no return value specified for RemoveCustomRule")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, profileId, customRuleId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Cachecache_RemoveCustomRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveCustomRule'
type Cachecache_RemoveCustomRule_Call struct {
	*mock.Call
}

// RemoveCustomRule is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
//   - customRuleId string
func (_e *Cachecache_Expecter) RemoveCustomRule(ctx interface{}, profileId interface{}, customRuleId interface{}) *Cachecache_RemoveCustomRule_Call {
	return &Cachecache_RemoveCustomRule_Call{Call: _e.mock.On("RemoveCustomRule", ctx, profileId, customRuleId)}
}

func (_c *Cachecache_RemoveCustomRule_Call) Run(run func(ctx context.Context, profileId string, customRuleId string)) *Cachecache_RemoveCustomRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Cachecache_RemoveCustomRule_Call) Return(err error) *Cachecache_RemoveCustomRule_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Cachecache_RemoveCustomRule_Call) RunAndReturn(run func(ctx context.Context, profileId string, customRuleId string) error) *Cachecache_RemoveCustomRule_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveSubscription provides a mock function for the type Cachecache
func (_mock *Cachecache) RemoveSubscription(ctx context.Context, subscriptionId string) error {
	ret := _mock.Called(ctx, subscriptionId)

	if len(ret) == 0 {
		panic("no return value specified for RemoveSubscription")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, subscriptionId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Cachecache_RemoveSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveSubscription'
type Cachecache_RemoveSubscription_Call struct {
	*mock.Call
}

// RemoveSubscription is a helper method to define mock.On call
//   - ctx context.Context
//   - subscriptionId string
func (_e *Cachecache_Expecter) RemoveSubscription(ctx interface{}, subscriptionId interface{}) *Cachecache_RemoveSubscription_Call {
	return &Cachecache_RemoveSubscription_Call{Call: _e.mock.On("RemoveSubscription", ctx, subscriptionId)}
}

func (_c *Cachecache_RemoveSubscription_Call) Run(run func(ctx context.Context, subscriptionId string)) *Cachecache_RemoveSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cachecache_RemoveSubscription_Call) Return(err error) *Cachecache_RemoveSubscription_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Cachecache_RemoveSubscription_Call) RunAndReturn(run func(ctx context.Context, subscriptionId string) error) *Cachecache_RemoveSubscription_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type Cachecache
func (_mock *Cachecache) Set(context1 context.Context, s string, v any, duration time.Duration) error {
	ret := _mock.Called(context1, s, v, duration)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any, time.Duration) error); ok {
		r0 = returnFunc(context1, s, v, duration)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Cachecache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type Cachecache_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - v any
//   - duration time.Duration
func (_e *Cachecache_Expecter) Set(context1 interface{}, s interface{}, v interface{}, duration interface{}) *Cachecache_Set_Call {
	return &Cachecache_Set_Call{Call: _e.mock.On("Set", context1, s, v, duration)}
}

func (_c *Cachecache_Set_Call) Run(run func(context1 context.Context, s string, v any, duration time.Duration)) *Cachecache_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Cachecache_Set_Call) Return(err error) *Cachecache_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Cachecache_Set_Call) RunAndReturn(run func(context1 context.Context, s string, v any, duration time.Duration) error) *Cachecache_Set_Call {
	_c.Call.Return(run)
	return _c
}

// SetTOTPSecret provides a mock function for the type Cachecache
func (_mock *Cachecache) SetTOTPSecret(ctx context.Context, accountID string, secret string, expiresIn time.Duration) error {
	ret := _mock.Called(ctx, accountID, secret, expiresIn)

	if len(ret) == 0 {
		panic("no return value specified for SetTOTPSecret")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) error); ok {
		r0 = returnFunc(ctx, accountID, secret, expiresIn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Cachecache_SetTOTPSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTOTPSecret'
type Cachecache_SetTOTPSecret_Call struct {
	*mock.Call
}

// SetTOTPSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - secret string
//   - expiresIn time.Duration
func (_e *Cachecache_Expecter) SetTOTPSecret(ctx interface{}, accountID interface{}, secret interface{}, expiresIn interface{}) *Cachecache_SetTOTPSecret_Call {
	return &Cachecache_SetTOTPSecret_Call{Call: _e.mock.On("SetTOTPSecret", ctx, accountID, secret, expiresIn)}
}

func (_c *Cachecache_SetTOTPSecret_Call) Run(run func(ctx context.Context, accountID string, secret string, expiresIn time.Duration)) *Cachecache_SetTOTPSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Cachecache_SetTOTPSecret_Call) Return(err error) *Cachecache_SetTOTPSecret_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Cachecache_SetTOTPSecret_Call) RunAndReturn(run func(ctx context.Context, accountID string, secret string, expiresIn time.Duration) error) *Cachecache_SetTOTPSecret_Call {
	_c.Call.Return(run)
	return _c
}
