// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/go-webauthn/webauthn/webauthn"
	"github.com/ivpn/dns/api/model"
	mock "github.com/stretchr/testify/mock"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

// NewCredentialServicer creates a new instance of CredentialServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCredentialServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *CredentialServicer {
	mock := &CredentialServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CredentialServicer is an autogenerated mock type for the CredentialServicer type
type CredentialServicer struct {
	mock.Mock
}

type CredentialServicer_Expecter struct {
	mock *mock.Mock
}

func (_m *CredentialServicer) EXPECT() *CredentialServicer_Expecter {
	return &CredentialServicer_Expecter{mock: &_m.Mock}
}

// DeleteCredential provides a mock function for the type CredentialServicer
func (_mock *CredentialServicer) DeleteCredential(ctx context.Context, credentialID []byte, accountID primitive.ObjectID) error {
	ret := _mock.Called(ctx, credentialID, accountID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCredential")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, primitive.ObjectID) error); ok {
		r0 = returnFunc(ctx, credentialID, accountID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CredentialServicer_DeleteCredential_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCredential'
type CredentialServicer_DeleteCredential_Call struct {
	*mock.Call
}

// DeleteCredential is a helper method to define mock.On call
//   - ctx context.Context
//   - credentialID []byte
//   - accountID primitive.ObjectID
func (_e *CredentialServicer_Expecter) DeleteCredential(ctx interface{}, credentialID interface{}, accountID interface{}) *CredentialServicer_DeleteCredential_Call {
	return &CredentialServicer_DeleteCredential_Call{Call: _e.mock.On("DeleteCredential", ctx, credentialID, accountID)}
}

func (_c *CredentialServicer_DeleteCredential_Call) Run(run func(ctx context.Context, credentialID []byte, accountID primitive.ObjectID)) *CredentialServicer_DeleteCredential_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 primitive.ObjectID
		if args[2] != nil {
			arg2 = args[2].(primitive.ObjectID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CredentialServicer_DeleteCredential_Call) Return(err error) *CredentialServicer_DeleteCredential_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CredentialServicer_DeleteCredential_Call) RunAndReturn(run func(ctx context.Context, credentialID []byte, accountID primitive.ObjectID) error) *CredentialServicer_DeleteCredential_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCredentialByID provides a mock function for the type CredentialServicer
func (_mock *CredentialServicer) DeleteCredentialByID(context1 context.Context, objectID primitive.ObjectID, objectID1 primitive.ObjectID) error {
	ret := _mock.Called(context1, objectID, objectID1)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCredentialByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, primitive.ObjectID) error); ok {
		r0 = returnFunc(context1, objectID, objectID1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CredentialServicer_DeleteCredentialByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCredentialByID'
type CredentialServicer_DeleteCredentialByID_Call struct {
	*mock.Call
}

// DeleteCredentialByID is a helper method to define mock.On call
//   - context1 context.Context
//   - objectID primitive.ObjectID
//   - objectID1 primitive.ObjectID
func (_e *CredentialServicer_Expecter) DeleteCredentialByID(context1 interface{}, objectID interface{}, objectID1 interface{}) *CredentialServicer_DeleteCredentialByID_Call {
	return &CredentialServicer_DeleteCredentialByID_Call{Call: _e.mock.On("DeleteCredentialByID", context1, objectID, objectID1)}
}

func (_c *CredentialServicer_DeleteCredentialByID_Call) Run(run func(context1 context.Context, objectID primitive.ObjectID, objectID1 primitive.ObjectID)) *CredentialServicer_DeleteCredentialByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 primitive.ObjectID
		if args[1] != nil {
			arg1 = args[1].(primitive.ObjectID)
		}
		var arg2 primitive.ObjectID
		if args[2] != nil {
			arg2 = args[2].(primitive.ObjectID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CredentialServicer_DeleteCredentialByID_Call) Return(err error) *CredentialServicer_DeleteCredentialByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CredentialServicer_DeleteCredentialByID_Call) RunAndReturn(run func(context1 context.Context, objectID primitive.ObjectID, objectID1 primitive.ObjectID) error) *CredentialServicer_DeleteCredentialByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCredentials provides a mock function for the type CredentialServicer
func (_mock *CredentialServicer) GetCredentials(context1 context.Context, objectID primitive.ObjectID) ([]model.Credential, error) {
	ret := _mock.Called(context1, objectID)

	if len(ret) == 0 {
		panic("no return value specified for GetCredentials")
	}

	var r0 []model.Credential
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) ([]model.Credential, error)); ok {
		return returnFunc(context1, objectID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) []model.Credential); ok {
		r0 = returnFunc(context1, objectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Credential)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = returnFunc(context1, objectID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CredentialServicer_GetCredentials_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCredentials'
type CredentialServicer_GetCredentials_Call struct {
	*mock.Call
}

// GetCredentials is a helper method to define mock.On call
//   - context1 context.Context
//   - objectID primitive.ObjectID
func (_e *CredentialServicer_Expecter) GetCredentials(context1 interface{}, objectID interface{}) *CredentialServicer_GetCredentials_Call {
	return &CredentialServicer_GetCredentials_Call{Call: _e.mock.On("GetCredentials", context1, objectID)}
}

func (_c *CredentialServicer_GetCredentials_Call) Run(run func(context1 context.Context, objectID primitive.ObjectID)) *CredentialServicer_GetCredentials_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 primitive.ObjectID
		if args[1] != nil {
			arg1 = args[1].(primitive.ObjectID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CredentialServicer_GetCredentials_Call) Return(credentials []model.Credential, err error) *CredentialServicer_GetCredentials_Call {
	_c.Call.Return(credentials, err)
	return _c
}

func (_c *CredentialServicer_GetCredentials_Call) RunAndReturn(run func(context1 context.Context, objectID primitive.ObjectID) ([]model.Credential, error)) *CredentialServicer_GetCredentials_Call {
	_c.Call.Return(run)
	return _c
}

// SaveCredential provides a mock function for the type CredentialServicer
func (_mock *CredentialServicer) SaveCredential(context1 context.Context, credential webauthn.Credential, objectID primitive.ObjectID) error {
	ret := _mock.Called(context1, credential, objectID)

	if len(ret) == 0 {
		panic("no return value specified for SaveCredential")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, webauthn.Credential, primitive.ObjectID) error); ok {
		r0 = returnFunc(context1, credential, objectID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CredentialServicer_SaveCredential_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveCredential'
type CredentialServicer_SaveCredential_Call struct {
	*mock.Call
}

// SaveCredential is a helper method to define mock.On call
//   - context1 context.Context
//   - credential webauthn.Credential
//   - objectID primitive.ObjectID
func (_e *CredentialServicer_Expecter) SaveCredential(context1 interface{}, credential interface{}, objectID interface{}) *CredentialServicer_SaveCredential_Call {
	return &CredentialServicer_SaveCredential_Call{Call: _e.mock.On("SaveCredential", context1, credential, objectID)}
}

func (_c *CredentialServicer_SaveCredential_Call) Run(run func(context1 context.Context, credential webauthn.Credential, objectID primitive.ObjectID)) *CredentialServicer_SaveCredential_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 webauthn.Credential
		if args[1] != nil {
			arg1 = args[1].(webauthn.Credential)
		}
		var arg2 primitive.ObjectID
		if args[2] != nil {
			arg2 = args[2].(primitive.ObjectID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CredentialServicer_SaveCredential_Call) Return(err error) *CredentialServicer_SaveCredential_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CredentialServicer_SaveCredential_Call) RunAndReturn(run func(context1 context.Context, credential webauthn.Credential, objectID primitive.ObjectID) error) *CredentialServicer_SaveCredential_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCredential provides a mock function for the type CredentialServicer
func (_mock *CredentialServicer) UpdateCredential(context1 context.Context, credential webauthn.Credential, objectID primitive.ObjectID) error {
	ret := _mock.Called(context1, credential, objectID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCredential")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, webauthn.Credential, primitive.ObjectID) error); ok {
		r0 = returnFunc(context1, credential, objectID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CredentialServicer_UpdateCredential_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCredential'
type CredentialServicer_UpdateCredential_Call struct {
	*mock.Call
}

// UpdateCredential is a helper method to define mock.On call
//   - context1 context.Context
//   - credential webauthn.Credential
//   - objectID primitive.ObjectID
func (_e *CredentialServicer_Expecter) UpdateCredential(context1 interface{}, credential interface{}, objectID interface{}) *CredentialServicer_UpdateCredential_Call {
	return &CredentialServicer_UpdateCredential_Call{Call: _e.mock.On("UpdateCredential", context1, credential, objectID)}
}

func (_c *CredentialServicer_UpdateCredential_Call) Run(run func(context1 context.Context, credential webauthn.Credential, objectID primitive.ObjectID)) *CredentialServicer_UpdateCredential_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 webauthn.Credential
		if args[1] != nil {
			arg1 = args[1].(webauthn.Credential)
		}
		var arg2 primitive.ObjectID
		if args[2] != nil {
			arg2 = args[2].(primitive.ObjectID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CredentialServicer_UpdateCredential_Call) Return(err error) *CredentialServicer_UpdateCredential_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CredentialServicer_UpdateCredential_Call) RunAndReturn(run func(context1 context.Context, credential webauthn.Credential, objectID primitive.ObjectID) error) *CredentialServicer_UpdateCredential_Call {
	_c.Call.Return(run)
	return _c
}
