// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/go-webauthn/webauthn/webauthn"
	"github.com/ivpn/dns/api/model"
	mock "github.com/stretchr/testify/mock"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
)

// NewDb creates a new instance of Db. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDb(t interface {
	mock.TestingT
	Cleanup(func())
}) *Db {
	mock := &Db{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Db is an autogenerated mock type for the Db type
type Db struct {
	mock.Mock
}

type Db_Expecter struct {
	mock *mock.Mock
}

func (_m *Db) EXPECT() *Db_Expecter {
	return &Db_Expecter{mock: &_m.Mock}
}

// AddProfileToAccount provides a mock function for the type Db
func (_mock *Db) AddProfileToAccount(ctx context.Context, accountId string, profileId string) error {
	ret := _mock.Called(ctx, accountId, profileId)

	if len(ret) == 0 {
		panic("no return value specified for AddProfileToAccount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, accountId, profileId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Db_AddProfileToAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddProfileToAccount'
type Db_AddProfileToAccount_Call struct {
	*mock.Call
}

// AddProfileToAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
//   - profileId string
func (_e *Db_Expecter) AddProfileToAccount(ctx interface{}, accountId interface{}, profileId interface{}) *Db_AddProfileToAccount_Call {
	return &Db_AddProfileToAccount_Call{Call: _e.mock.On("AddProfileToAccount", ctx, accountId, profileId)}
}

func (_c *Db_AddProfileToAccount_Call) Run(run func(ctx context.Context, accountId string, profileId string)) *Db_AddProfileToAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Db_AddProfileToAccount_Call) Return(err error) *Db_AddProfileToAccount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Db_AddProfileToAccount_Call) RunAndReturn(run func(ctx context.Context, accountId string, profileId string) error) *Db_AddProfileToAccount_Call {
	_c.Call.Return(run)
	return _c
}

// CountSessionsByAccountID provides a mock function for the type Db
func (_mock *Db) CountSessionsByAccountID(ctx context.Context, accID string) (int64, error) {
	ret := _mock.Called(ctx, accID)

	if len(ret) == 0 {
		panic("no return value specified for CountSessionsByAccountID")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return returnFunc(ctx, accID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, accID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Db_CountSessionsByAccountID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountSessionsByAccountID'
type Db_CountSessionsByAccountID_Call struct {
	*mock.Call
}

// CountSessionsByAccountID is a helper method to define mock.On call
//   - ctx context.Context
//   - accID string
func (_e *Db_Expecter) CountSessionsByAccountID(ctx interface{}, accID interface{}) *Db_CountSessionsByAccountID_Call {
	return &Db_CountSessionsByAccountID_Call{Call: _e.mock.On("CountSessionsByAccountID", ctx, accID)}
}

func (_c *Db_CountSessionsByAccountID_Call) Run(run func(ctx context.Context, accID string)) *Db_CountSessionsByAccountID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Db_CountSessionsByAccountID_Call) Return(n int64, err error) *Db_CountSessionsByAccountID_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *Db_CountSessionsByAccountID_Call) RunAndReturn(run func(ctx context.Context, accID string) (int64, error)) *Db_CountSessionsByAccountID_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type Db
func (_mock *Db) Create(ctx context.Context, subscription model.Subscription) error {
	ret := _mock.Called(ctx, subscription)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Subscription) error); ok {
		r0 = returnFunc(ctx, subscription)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Db_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Db_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - subscription model.Subscription
func (_e *Db_Expecter) Create(ctx interface{}, subscription interface{}) *Db_Create_Call {
	return &Db_Create_Call{Call: _e.mock.On("Create", ctx, subscription)}
}

func (_c *Db_Create_Call) Run(run func(ctx context.Context, subscription model.Subscription)) *Db_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Subscription
		if args[1] != nil {
			arg1 = args[1].(model.Subscription)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Db_Create_Call) Return(err error) *Db_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Db_Create_Call) RunAndReturn(run func(ctx context.Context, subscription model.Subscription) error) *Db_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAccount provides a mock function for the type Db
func (_mock *Db) CreateAccount(ctx context.Context, email string, password string, accountId string, profileId string) (*model.Account, error) {
	ret := _mock.Called(ctx, email, password, accountId, profileId)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccount")
	}

	var r0 *model.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*model.Account, error)); ok {
		return returnFunc(ctx, email, password, accountId, profileId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) *model.Account); ok {
		r0 = returnFunc(ctx, email, password, accountId, profileId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = returnFunc(ctx, email, password, accountId, profileId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Db_CreateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccount'
type Db_CreateAccount_Call struct {
	*mock.Call
}

// CreateAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
//   - accountId string
//   - profileId string
func (_e *Db_Expecter) CreateAccount(ctx interface{}, email interface{}, password interface{}, accountId interface{}, profileId interface{}) *Db_CreateAccount_Call {
	return &Db_CreateAccount_Call{Call: _e.mock.On("CreateAccount", ctx, email, password, accountId, profileId)}
}

func (_c *Db_CreateAccount_Call) Run(run func(ctx context.Context, email string, password string, accountId string, profileId string)) *Db_CreateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *Db_CreateAccount_Call) Return(account *model.Account, err error) *Db_CreateAccount_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *Db_CreateAccount_Call) RunAndReturn(run func(ctx context.Context, email string, password string, accountId string, profileId string) (*model.Account, error)) *Db_CreateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// CreateCustomRules provides a mock function for the type Db
func (_mock *Db) CreateCustomRules(ctx context.Context, profileId string, rules []*model.CustomRule) error {
	ret := _mock.Called(ctx, profileId, rules)

	if len(ret) == 0 {
		panic("no return value specified for CreateCustomRules")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []*model.CustomRule) error); ok {
		r0 = returnFunc(ctx, profileId, rules)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Db_CreateCustomRules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCustomRules'
type Db_CreateCustomRules_Call struct {
	*mock.Call
}

// CreateCustomRules is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
//   - rules []*model.CustomRule
func (_e *Db_Expecter) CreateCustomRules(ctx interface{}, profileId interface{}, rules interface{}) *Db_CreateCustomRules_Call {
	return &Db_CreateCustomRules_Call{Call: _e.mock.On("CreateCustomRules", ctx, profileId, rules)}
}

func (_c *Db_CreateCustomRules_Call) Run(run func(ctx context.Context, profileId string, rules []*model.CustomRule)) *Db_CreateCustomRules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []*model.CustomRule
		if args[2] != nil {
			arg2 = args[2].([]*model.CustomRule)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Db_CreateCustomRules_Call) Return(err error) *Db_CreateCustomRules_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Db_CreateCustomRules_Call) RunAndReturn(run func(ctx context.Context, profileId string, rules []*model.CustomRule) error) *Db_CreateCustomRules_Call {
	_c.Call.Return(run)
	return _c
}

// CreateProfile provides a mock function for the type Db
func (_mock *Db) CreateProfile(ctx context.Context, profile *model.Profile) error {
	ret := _mock.Called(ctx, profile)

	if len(ret) == 0 {
		panic("no return value specified for CreateProfile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Profile) error); ok {
		r0 = returnFunc(ctx, profile)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Db_CreateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProfile'
type Db_CreateProfile_Call struct {
	*mock.Call
}

// CreateProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - profile *model.Profile
func (_e *Db_Expecter) CreateProfile(ctx interface{}, profile interface{}) *Db_CreateProfile_Call {
	return &Db_CreateProfile_Call{Call: _e.mock.On("CreateProfile", ctx, profile)}
}

func (_c *Db_CreateProfile_Call) Run(run func(ctx context.Context, profile *model.Profile)) *Db_CreateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Profile
		if args[1] != nil {
			arg1 = args[1].(*model.Profile)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Db_CreateProfile_Call) Return(err error) *Db_CreateProfile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Db_CreateProfile_Call) RunAndReturn(run func(ctx context.Context, profile *model.Profile) error) *Db_CreateProfile_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAccountById provides a mock function for the type Db
func (_mock *Db) DeleteAccountById(ctx context.Context, accountId string) error {
	ret := _mock.Called(ctx, accountId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAccountById")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, accountId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Db_DeleteAccountById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAccountById'
type Db_DeleteAccountById_Call struct {
	*mock.Call
}

// DeleteAccountById is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
func (_e *Db_Expecter) DeleteAccountById(ctx interface{}, accountId interface{}) *Db_DeleteAccountById_Call {
	return &Db_DeleteAccountById_Call{Call: _e.mock.On("DeleteAccountById", ctx, accountId)}
}

func (_c *Db_DeleteAccountById_Call) Run(run func(ctx context.Context, accountId string)) *Db_DeleteAccountById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Db_DeleteAccountById_Call) Return(err error) *Db_DeleteAccountById_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Db_DeleteAccountById_Call) RunAndReturn(run func(ctx context.Context, accountId string) error) *Db_DeleteAccountById_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCredential provides a mock function for the type Db
func (_mock *Db) DeleteCredential(ctx context.Context, credentialID []byte, accountID primitive.ObjectID) error {
	ret := _mock.Called(ctx, credentialID, accountID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCredential")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, primitive.ObjectID) error); ok {
		r0 = returnFunc(ctx, credentialID, accountID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Db_DeleteCredential_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCredential'
type Db_DeleteCredential_Call struct {
	*mock.Call
}

// DeleteCredential is a helper method to define mock.On call
//   - ctx context.Context
//   - credentialID []byte
//   - accountID primitive.ObjectID
func (_e *Db_Expecter) DeleteCredential(ctx interface{}, credentialID interface{}, accountID interface{}) *Db_DeleteCredential_Call {
	return &Db_DeleteCredential_Call{Call: _e.mock.On("DeleteCredential", ctx, credentialID, accountID)}
}

func (_c *Db_DeleteCredential_Call) Run(run func(ctx context.Context, credentialID []byte, accountID primitive.ObjectID)) *Db_DeleteCredential_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 primitive.ObjectID
		if args[2] != nil {
			arg2 = args[2].(primitive.ObjectID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Db_DeleteCredential_Call) Return(err error) *Db_DeleteCredential_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Db_DeleteCredential_Call) RunAndReturn(run func(ctx context.Context, credentialID []byte, accountID primitive.ObjectID) error) *Db_DeleteCredential_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCredentialByID provides a mock function for the type Db
func (_mock *Db) DeleteCredentialByID(ctx context.Context, credentialID primitive.ObjectID, accountID primitive.ObjectID) error {
	ret := _mock.Called(ctx, credentialID, accountID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCredentialByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, primitive.ObjectID) error); ok {
		r0 = returnFunc(ctx, credentialID, accountID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Db_DeleteCredentialByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCredentialByID'
type Db_DeleteCredentialByID_Call struct {
	*mock.Call
}

// DeleteCredentialByID is a helper method to define mock.On call
//   - ctx context.Context
//   - credentialID primitive.ObjectID
//   - accountID primitive.ObjectID
func (_e *Db_Expecter) DeleteCredentialByID(ctx interface{}, credentialID interface{}, accountID interface{}) *Db_DeleteCredentialByID_Call {
	return &Db_DeleteCredentialByID_Call{Call: _e.mock.On("DeleteCredentialByID", ctx, credentialID, accountID)}
}

func (_c *Db_DeleteCredentialByID_Call) Run(run func(ctx context.Context, credentialID primitive.ObjectID, accountID primitive.ObjectID)) *Db_DeleteCredentialByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 primitive.ObjectID
		if args[1] != nil {
			arg1 = args[1].(primitive.ObjectID)
		}
		var arg2 primitive.ObjectID
		if args[2] != nil {
			arg2 = args[2].(primitive.ObjectID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Db_DeleteCredentialByID_Call) Return(err error) *Db_DeleteCredentialByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Db_DeleteCredentialByID_Call) RunAndReturn(run func(ctx context.Context, credentialID primitive.ObjectID, accountID primitive.ObjectID) error) *Db_DeleteCredentialByID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProfileById provides a mock function for the type Db
func (_mock *Db) DeleteProfileById(ctx context.Context, profileId string) error {
	ret := _mock.Called(ctx, profileId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProfileById")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, profileId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Db_DeleteProfileById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProfileById'
type Db_DeleteProfileById_Call struct {
	*mock.Call
}

// DeleteProfileById is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
func (_e *Db_Expecter) DeleteProfileById(ctx interface{}, profileId interface{}) *Db_DeleteProfileById_Call {
	return &Db_DeleteProfileById_Call{Call: _e.mock.On("DeleteProfileById", ctx, profileId)}
}

func (_c *Db_DeleteProfileById_Call) Run(run func(ctx context.Context, profileId string)) *Db_DeleteProfileById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Db_DeleteProfileById_Call) Return(err error) *Db_DeleteProfileById_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Db_DeleteProfileById_Call) RunAndReturn(run func(ctx context.Context, profileId string) error) *Db_DeleteProfileById_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteQueryLogs provides a mock function for the type Db
func (_mock *Db) DeleteQueryLogs(ctx context.Context, profileId string) error {
	ret := _mock.Called(ctx, profileId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteQueryLogs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, profileId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Db_DeleteQueryLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteQueryLogs'
type Db_DeleteQueryLogs_Call struct {
	*mock.Call
}

// DeleteQueryLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
func (_e *Db_Expecter) DeleteQueryLogs(ctx interface{}, profileId interface{}) *Db_DeleteQueryLogs_Call {
	return &Db_DeleteQueryLogs_Call{Call: _e.mock.On("DeleteQueryLogs", ctx, profileId)}
}

func (_c *Db_DeleteQueryLogs_Call) Run(run func(ctx context.Context, profileId string)) *Db_DeleteQueryLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Db_DeleteQueryLogs_Call) Return(err error) *Db_DeleteQueryLogs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Db_DeleteQueryLogs_Call) RunAndReturn(run func(ctx context.Context, profileId string) error) *Db_DeleteQueryLogs_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSession provides a mock function for the type Db
func (_mock *Db) DeleteSession(ctx context.Context, token string) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Db_DeleteSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSession'
type Db_DeleteSession_Call struct {
	*mock.Call
}

// DeleteSession is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *Db_Expecter) DeleteSession(ctx interface{}, token interface{}) *Db_DeleteSession_Call {
	return &Db_DeleteSession_Call{Call: _e.mock.On("DeleteSession", ctx, token)}
}

func (_c *Db_DeleteSession_Call) Run(run func(ctx context.Context, token string)) *Db_DeleteSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Db_DeleteSession_Call) Return(err error) *Db_DeleteSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Db_DeleteSession_Call) RunAndReturn(run func(ctx context.Context, token string) error) *Db_DeleteSession_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSessionsByAccountID provides a mock function for the type Db
func (_mock *Db) DeleteSessionsByAccountID(ctx context.Context, accID string) error {
	ret := _mock.Called(ctx, accID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSessionsByAccountID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, accID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Db_DeleteSessionsByAccountID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSessionsByAccountID'
type Db_DeleteSessionsByAccountID_Call struct {
	*mock.Call
}

// DeleteSessionsByAccountID is a helper method to define mock.On call
//   - ctx context.Context
//   - accID string
func (_e *Db_Expecter) DeleteSessionsByAccountID(ctx interface{}, accID interface{}) *Db_DeleteSessionsByAccountID_Call {
	return &Db_DeleteSessionsByAccountID_Call{Call: _e.mock.On("DeleteSessionsByAccountID", ctx, accID)}
}

func (_c *Db_DeleteSessionsByAccountID_Call) Run(run func(ctx context.Context, accID string)) *Db_DeleteSessionsByAccountID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Db_DeleteSessionsByAccountID_Call) Return(err error) *Db_DeleteSessionsByAccountID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Db_DeleteSessionsByAccountID_Call) RunAndReturn(run func(ctx context.Context, accID string) error) *Db_DeleteSessionsByAccountID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSessionsByAccountIDExceptCurrent provides a mock function for the type Db
func (_mock *Db) DeleteSessionsByAccountIDExceptCurrent(ctx context.Context, accID string, currentToken string) error {
	ret := _mock.Called(ctx, accID, currentToken)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSessionsByAccountIDExceptCurrent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, accID, currentToken)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Db_DeleteSessionsByAccountIDExceptCurrent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSessionsByAccountIDExceptCurrent'
type Db_DeleteSessionsByAccountIDExceptCurrent_Call struct {
	*mock.Call
}

// DeleteSessionsByAccountIDExceptCurrent is a helper method to define mock.On call
//   - ctx context.Context
//   - accID string
//   - currentToken string
func (_e *Db_Expecter) DeleteSessionsByAccountIDExceptCurrent(ctx interface{}, accID interface{}, currentToken interface{}) *Db_DeleteSessionsByAccountIDExceptCurrent_Call {
	return &Db_DeleteSessionsByAccountIDExceptCurrent_Call{Call: _e.mock.On("DeleteSessionsByAccountIDExceptCurrent", ctx, accID, currentToken)}
}

func (_c *Db_DeleteSessionsByAccountIDExceptCurrent_Call) Run(run func(ctx context.Context, accID string, currentToken string)) *Db_DeleteSessionsByAccountIDExceptCurrent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Db_DeleteSessionsByAccountIDExceptCurrent_Call) Return(err error) *Db_DeleteSessionsByAccountIDExceptCurrent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Db_DeleteSessionsByAccountIDExceptCurrent_Call) RunAndReturn(run func(ctx context.Context, accID string, currentToken string) error) *Db_DeleteSessionsByAccountIDExceptCurrent_Call {
	_c.Call.Return(run)
	return _c
}

// DisableBlocklists provides a mock function for the type Db
func (_mock *Db) DisableBlocklists(ctx context.Context, profileId string, blocklistIds []string) error {
	ret := _mock.Called(ctx, profileId, blocklistIds)

	if len(ret) == 0 {
		panic("no return value specified for DisableBlocklists")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = returnFunc(ctx, profileId, blocklistIds)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Db_DisableBlocklists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisableBlocklists'
type Db_DisableBlocklists_Call struct {
	*mock.Call
}

// DisableBlocklists is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
//   - blocklistIds []string
func (_e *Db_Expecter) DisableBlocklists(ctx interface{}, profileId interface{}, blocklistIds interface{}) *Db_DisableBlocklists_Call {
	return &Db_DisableBlocklists_Call{Call: _e.mock.On("DisableBlocklists", ctx, profileId, blocklistIds)}
}

func (_c *Db_DisableBlocklists_Call) Run(run func(ctx context.Context, profileId string, blocklistIds []string)) *Db_DisableBlocklists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Db_DisableBlocklists_Call) Return(err error) *Db_DisableBlocklists_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Db_DisableBlocklists_Call) RunAndReturn(run func(ctx context.Context, profileId string, blocklistIds []string) error) *Db_DisableBlocklists_Call {
	_c.Call.Return(run)
	return _c
}

// Disconnect provides a mock function for the type Db
func (_mock *Db) Disconnect() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Disconnect")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Db_Disconnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Disconnect'
type Db_Disconnect_Call struct {
	*mock.Call
}

// Disconnect is a helper method to define mock.On call
func (_e *Db_Expecter) Disconnect() *Db_Disconnect_Call {
	return &Db_Disconnect_Call{Call: _e.mock.On("Disconnect")}
}

func (_c *Db_Disconnect_Call) Run(run func()) *Db_Disconnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Db_Disconnect_Call) Return(err error) *Db_Disconnect_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Db_Disconnect_Call) RunAndReturn(run func() error) *Db_Disconnect_Call {
	_c.Call.Return(run)
	return _c
}

// EnableBlocklists provides a mock function for the type Db
func (_mock *Db) EnableBlocklists(ctx context.Context, profileId string, blocklistIds []string) error {
	ret := _mock.Called(ctx, profileId, blocklistIds)

	if len(ret) == 0 {
		panic("no return value specified for EnableBlocklists")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = returnFunc(ctx, profileId, blocklistIds)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Db_EnableBlocklists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableBlocklists'
type Db_EnableBlocklists_Call struct {
	*mock.Call
}

// EnableBlocklists is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
//   - blocklistIds []string
func (_e *Db_Expecter) EnableBlocklists(ctx interface{}, profileId interface{}, blocklistIds interface{}) *Db_EnableBlocklists_Call {
	return &Db_EnableBlocklists_Call{Call: _e.mock.On("EnableBlocklists", ctx, profileId, blocklistIds)}
}

func (_c *Db_EnableBlocklists_Call) Run(run func(ctx context.Context, profileId string, blocklistIds []string)) *Db_EnableBlocklists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Db_EnableBlocklists_Call) Return(err error) *Db_EnableBlocklists_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Db_EnableBlocklists_Call) RunAndReturn(run func(ctx context.Context, profileId string, blocklistIds []string) error) *Db_EnableBlocklists_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type Db
func (_mock *Db) Get(ctx context.Context, filter map[string]any) ([]*model.Blocklist, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []*model.Blocklist
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]any) ([]*model.Blocklist, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]any) []*model.Blocklist); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Blocklist)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, map[string]any) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Db_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Db_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - filter map[string]any
func (_e *Db_Expecter) Get(ctx interface{}, filter interface{}) *Db_Get_Call {
	return &Db_Get_Call{Call: _e.mock.On("Get", ctx, filter)}
}

func (_c *Db_Get_Call) Run(run func(ctx context.Context, filter map[string]any)) *Db_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string]any
		if args[1] != nil {
			arg1 = args[1].(map[string]any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Db_Get_Call) Return(blocklists []*model.Blocklist, err error) *Db_Get_Call {
	_c.Call.Return(blocklists, err)
	return _c
}

func (_c *Db_Get_Call) RunAndReturn(run func(ctx context.Context, filter map[string]any) ([]*model.Blocklist, error)) *Db_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccount provides a mock function for the type Db
func (_mock *Db) GetAccount(ctx context.Context, accountId string) (*model.Account, error) {
	ret := _mock.Called(ctx, accountId)

	if len(ret) == 0 {
		panic("no return value specified for GetAccount")
	}

	var r0 *model.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Account, error)); ok {
		return returnFunc(ctx, accountId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Account); ok {
		r0 = returnFunc(ctx, accountId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accountId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Db_GetAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccount'
type Db_GetAccount_Call struct {
	*mock.Call
}

// GetAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
func (_e *Db_Expecter) GetAccount(ctx interface{}, accountId interface{}) *Db_GetAccount_Call {
	return &Db_GetAccount_Call{Call: _e.mock.On("GetAccount", ctx, accountId)}
}

func (_c *Db_GetAccount_Call) Run(run func(ctx context.Context, accountId string)) *Db_GetAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Db_GetAccount_Call) Return(account *model.Account, err error) *Db_GetAccount_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *Db_GetAccount_Call) RunAndReturn(run func(ctx context.Context, accountId string) (*model.Account, error)) *Db_GetAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccountByEmail provides a mock function for the type Db
func (_mock *Db) GetAccountByEmail(ctx context.Context, email string) (*model.Account, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountByEmail")
	}

	var r0 *model.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Account, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Account); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Db_GetAccountByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountByEmail'
type Db_GetAccountByEmail_Call struct {
	*mock.Call
}

// GetAccountByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *Db_Expecter) GetAccountByEmail(ctx interface{}, email interface{}) *Db_GetAccountByEmail_Call {
	return &Db_GetAccountByEmail_Call{Call: _e.mock.On("GetAccountByEmail", ctx, email)}
}

func (_c *Db_GetAccountByEmail_Call) Run(run func(ctx context.Context, email string)) *Db_GetAccountByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Db_GetAccountByEmail_Call) Return(account *model.Account, err error) *Db_GetAccountByEmail_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *Db_GetAccountByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*model.Account, error)) *Db_GetAccountByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccountById provides a mock function for the type Db
func (_mock *Db) GetAccountById(ctx context.Context, accountId string) (*model.Account, error) {
	ret := _mock.Called(ctx, accountId)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountById")
	}

	var r0 *model.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Account, error)); ok {
		return returnFunc(ctx, accountId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Account); ok {
		r0 = returnFunc(ctx, accountId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accountId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Db_GetAccountById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountById'
type Db_GetAccountById_Call struct {
	*mock.Call
}

// GetAccountById is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
func (_e *Db_Expecter) GetAccountById(ctx interface{}, accountId interface{}) *Db_GetAccountById_Call {
	return &Db_GetAccountById_Call{Call: _e.mock.On("GetAccountById", ctx, accountId)}
}

func (_c *Db_GetAccountById_Call) Run(run func(ctx context.Context, accountId string)) *Db_GetAccountById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Db_GetAccountById_Call) Return(account *model.Account, err error) *Db_GetAccountById_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *Db_GetAccountById_Call) RunAndReturn(run func(ctx context.Context, accountId string) (*model.Account, error)) *Db_GetAccountById_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccountByToken provides a mock function for the type Db
func (_mock *Db) GetAccountByToken(ctx context.Context, token string, tokenType string) (*model.Account, error) {
	ret := _mock.Called(ctx, token, tokenType)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountByToken")
	}

	var r0 *model.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*model.Account, error)); ok {
		return returnFunc(ctx, token, tokenType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *model.Account); ok {
		r0 = returnFunc(ctx, token, tokenType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, token, tokenType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Db_GetAccountByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountByToken'
type Db_GetAccountByToken_Call struct {
	*mock.Call
}

// GetAccountByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - tokenType string
func (_e *Db_Expecter) GetAccountByToken(ctx interface{}, token interface{}, tokenType interface{}) *Db_GetAccountByToken_Call {
	return &Db_GetAccountByToken_Call{Call: _e.mock.On("GetAccountByToken", ctx, token, tokenType)}
}

func (_c *Db_GetAccountByToken_Call) Run(run func(ctx context.Context, token string, tokenType string)) *Db_GetAccountByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Db_GetAccountByToken_Call) Return(account *model.Account, err error) *Db_GetAccountByToken_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *Db_GetAccountByToken_Call) RunAndReturn(run func(ctx context.Context, token string, tokenType string) (*model.Account, error)) *Db_GetAccountByToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetClient provides a mock function for the type Db
func (_mock *Db) GetClient() *mongo.Client {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetClient")
	}

	var r0 *mongo.Client
	if returnFunc, ok := ret.Get(0).(func() *mongo.Client); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.Client)
		}
	}
	return r0
}

// Db_GetClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClient'
type Db_GetClient_Call struct {
	*mock.Call
}

// GetClient is a helper method to define mock.On call
func (_e *Db_Expecter) GetClient() *Db_GetClient_Call {
	return &Db_GetClient_Call{Call: _e.mock.On("GetClient")}
}

func (_c *Db_GetClient_Call) Run(run func()) *Db_GetClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Db_GetClient_Call) Return(client *mongo.Client) *Db_GetClient_Call {
	_c.Call.Return(client)
	return _c
}

func (_c *Db_GetClient_Call) RunAndReturn(run func() *mongo.Client) *Db_GetClient_Call {
	_c.Call.Return(run)
	return _c
}

// GetCredentialByID provides a mock function for the type Db
func (_mock *Db) GetCredentialByID(ctx context.Context, credentialID primitive.ObjectID) (*model.Credential, error) {
	ret := _mock.Called(ctx, credentialID)

	if len(ret) == 0 {
		panic("no return value specified for GetCredentialByID")
	}

	var r0 *model.Credential
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) (*model.Credential, error)); ok {
		return returnFunc(ctx, credentialID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) *model.Credential); ok {
		r0 = returnFunc(ctx, credentialID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Credential)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = returnFunc(ctx, credentialID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Db_GetCredentialByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCredentialByID'
type Db_GetCredentialByID_Call struct {
	*mock.Call
}

// GetCredentialByID is a helper method to define mock.On call
//   - ctx context.Context
//   - credentialID primitive.ObjectID
func (_e *Db_Expecter) GetCredentialByID(ctx interface{}, credentialID interface{}) *Db_GetCredentialByID_Call {
	return &Db_GetCredentialByID_Call{Call: _e.mock.On("GetCredentialByID", ctx, credentialID)}
}

func (_c *Db_GetCredentialByID_Call) Run(run func(ctx context.Context, credentialID primitive.ObjectID)) *Db_GetCredentialByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 primitive.ObjectID
		if args[1] != nil {
			arg1 = args[1].(primitive.ObjectID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Db_GetCredentialByID_Call) Return(credential *model.Credential, err error) *Db_GetCredentialByID_Call {
	_c.Call.Return(credential, err)
	return _c
}

func (_c *Db_GetCredentialByID_Call) RunAndReturn(run func(ctx context.Context, credentialID primitive.ObjectID) (*model.Credential, error)) *Db_GetCredentialByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCredentials provides a mock function for the type Db
func (_mock *Db) GetCredentials(ctx context.Context, accountID primitive.ObjectID) ([]model.Credential, error) {
	ret := _mock.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetCredentials")
	}

	var r0 []model.Credential
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) ([]model.Credential, error)); ok {
		return returnFunc(ctx, accountID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) []model.Credential); ok {
		r0 = returnFunc(ctx, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Credential)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = returnFunc(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Db_GetCredentials_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCredentials'
type Db_GetCredentials_Call struct {
	*mock.Call
}

// GetCredentials is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID primitive.ObjectID
func (_e *Db_Expecter) GetCredentials(ctx interface{}, accountID interface{}) *Db_GetCredentials_Call {
	return &Db_GetCredentials_Call{Call: _e.mock.On("GetCredentials", ctx, accountID)}
}

func (_c *Db_GetCredentials_Call) Run(run func(ctx context.Context, accountID primitive.ObjectID)) *Db_GetCredentials_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 primitive.ObjectID
		if args[1] != nil {
			arg1 = args[1].(primitive.ObjectID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Db_GetCredentials_Call) Return(credentials []model.Credential, err error) *Db_GetCredentials_Call {
	_c.Call.Return(credentials, err)
	return _c
}

func (_c *Db_GetCredentials_Call) RunAndReturn(run func(ctx context.Context, accountID primitive.ObjectID) ([]model.Credential, error)) *Db_GetCredentials_Call {
	_c.Call.Return(run)
	return _c
}

// GetCredentialsCount provides a mock function for the type Db
func (_mock *Db) GetCredentialsCount(ctx context.Context, accountID primitive.ObjectID) (int, error) {
	ret := _mock.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetCredentialsCount")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) (int, error)); ok {
		return returnFunc(ctx, accountID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) int); ok {
		r0 = returnFunc(ctx, accountID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = returnFunc(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Db_GetCredentialsCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCredentialsCount'
type Db_GetCredentialsCount_Call struct {
	*mock.Call
}

// GetCredentialsCount is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID primitive.ObjectID
func (_e *Db_Expecter) GetCredentialsCount(ctx interface{}, accountID interface{}) *Db_GetCredentialsCount_Call {
	return &Db_GetCredentialsCount_Call{Call: _e.mock.On("GetCredentialsCount", ctx, accountID)}
}

func (_c *Db_GetCredentialsCount_Call) Run(run func(ctx context.Context, accountID primitive.ObjectID)) *Db_GetCredentialsCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 primitive.ObjectID
		if args[1] != nil {
			arg1 = args[1].(primitive.ObjectID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Db_GetCredentialsCount_Call) Return(n int, err error) *Db_GetCredentialsCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *Db_GetCredentialsCount_Call) RunAndReturn(run func(ctx context.Context, accountID primitive.ObjectID) (int, error)) *Db_GetCredentialsCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfileById provides a mock function for the type Db
func (_mock *Db) GetProfileById(ctx context.Context, profileId string) (*model.Profile, error) {
	ret := _mock.Called(ctx, profileId)

	if len(ret) == 0 {
		panic("no return value specified for GetProfileById")
	}

	var r0 *model.Profile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Profile, error)); ok {
		return returnFunc(ctx, profileId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Profile); ok {
		r0 = returnFunc(ctx, profileId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Profile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, profileId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Db_GetProfileById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfileById'
type Db_GetProfileById_Call struct {
	*mock.Call
}

// GetProfileById is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
func (_e *Db_Expecter) GetProfileById(ctx interface{}, profileId interface{}) *Db_GetProfileById_Call {
	return &Db_GetProfileById_Call{Call: _e.mock.On("GetProfileById", ctx, profileId)}
}

func (_c *Db_GetProfileById_Call) Run(run func(ctx context.Context, profileId string)) *Db_GetProfileById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Db_GetProfileById_Call) Return(profile *model.Profile, err error) *Db_GetProfileById_Call {
	_c.Call.Return(profile, err)
	return _c
}

func (_c *Db_GetProfileById_Call) RunAndReturn(run func(ctx context.Context, profileId string) (*model.Profile, error)) *Db_GetProfileById_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfileStatistics provides a mock function for the type Db
func (_mock *Db) GetProfileStatistics(ctx context.Context, profileId string, timespan int) ([]model.StatisticsAggregated, error) {
	ret := _mock.Called(ctx, profileId, timespan)

	if len(ret) == 0 {
		panic("no return value specified for GetProfileStatistics")
	}

	var r0 []model.StatisticsAggregated
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) ([]model.StatisticsAggregated, error)); ok {
		return returnFunc(ctx, profileId, timespan)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) []model.StatisticsAggregated); ok {
		r0 = returnFunc(ctx, profileId, timespan)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.StatisticsAggregated)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = returnFunc(ctx, profileId, timespan)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Db_GetProfileStatistics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfileStatistics'
type Db_GetProfileStatistics_Call struct {
	*mock.Call
}

// GetProfileStatistics is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
//   - timespan int
func (_e *Db_Expecter) GetProfileStatistics(ctx interface{}, profileId interface{}, timespan interface{}) *Db_GetProfileStatistics_Call {
	return &Db_GetProfileStatistics_Call{Call: _e.mock.On("GetProfileStatistics", ctx, profileId, timespan)}
}

func (_c *Db_GetProfileStatistics_Call) Run(run func(ctx context.Context, profileId string, timespan int)) *Db_GetProfileStatistics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Db_GetProfileStatistics_Call) Return(statisticsAggregateds []model.StatisticsAggregated, err error) *Db_GetProfileStatistics_Call {
	_c.Call.Return(statisticsAggregateds, err)
	return _c
}

func (_c *Db_GetProfileStatistics_Call) RunAndReturn(run func(ctx context.Context, profileId string, timespan int) ([]model.StatisticsAggregated, error)) *Db_GetProfileStatistics_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfilesByAccountId provides a mock function for the type Db
func (_mock *Db) GetProfilesByAccountId(ctx context.Context, accountId string) ([]model.Profile, error) {
	ret := _mock.Called(ctx, accountId)

	if len(ret) == 0 {
		panic("no return value specified for GetProfilesByAccountId")
	}

	var r0 []model.Profile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]model.Profile, error)); ok {
		return returnFunc(ctx, accountId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []model.Profile); ok {
		r0 = returnFunc(ctx, accountId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Profile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accountId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Db_GetProfilesByAccountId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfilesByAccountId'
type Db_GetProfilesByAccountId_Call struct {
	*mock.Call
}

// GetProfilesByAccountId is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
func (_e *Db_Expecter) GetProfilesByAccountId(ctx interface{}, accountId interface{}) *Db_GetProfilesByAccountId_Call {
	return &Db_GetProfilesByAccountId_Call{Call: _e.mock.On("GetProfilesByAccountId", ctx, accountId)}
}

func (_c *Db_GetProfilesByAccountId_Call) Run(run func(ctx context.Context, accountId string)) *Db_GetProfilesByAccountId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Db_GetProfilesByAccountId_Call) Return(profiles []model.Profile, err error) *Db_GetProfilesByAccountId_Call {
	_c.Call.Return(profiles, err)
	return _c
}

func (_c *Db_GetProfilesByAccountId_Call) RunAndReturn(run func(ctx context.Context, accountId string) ([]model.Profile, error)) *Db_GetProfilesByAccountId_Call {
	_c.Call.Return(run)
	return _c
}

// GetQueryLogs provides a mock function for the type Db
func (_mock *Db) GetQueryLogs(ctx context.Context, profileId string, retention model.Retention, status string, timespan int, deviceId string, search string, page int, limit int) ([]model.QueryLog, error) {
	ret := _mock.Called(ctx, profileId, retention, status, timespan, deviceId, search, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetQueryLogs")
	}

	var r0 []model.QueryLog
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.Retention, string, int, string, string, int, int) ([]model.QueryLog, error)); ok {
		return returnFunc(ctx, profileId, retention, status, timespan, deviceId, search, page, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.Retention, string, int, string, string, int, int) []model.QueryLog); ok {
		r0 = returnFunc(ctx, profileId, retention, status, timespan, deviceId, search, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.QueryLog)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, model.Retention, string, int, string, string, int, int) error); ok {
		r1 = returnFunc(ctx, profileId, retention, status, timespan, deviceId, search, page, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Db_GetQueryLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQueryLogs'
type Db_GetQueryLogs_Call struct {
	*mock.Call
}

// GetQueryLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
//   - retention model.Retention
//   - status string
//   - timespan int
//   - deviceId string
//   - search string
//   - page int
//   - limit int
func (_e *Db_Expecter) GetQueryLogs(ctx interface{}, profileId interface{}, retention interface{}, status interface{}, timespan interface{}, deviceId interface{}, search interface{}, page interface{}, limit interface{}) *Db_GetQueryLogs_Call {
	return &Db_GetQueryLogs_Call{Call: _e.mock.On("GetQueryLogs", ctx, profileId, retention, status, timespan, deviceId, search, page, limit)}
}

func (_c *Db_GetQueryLogs_Call) Run(run func(ctx context.Context, profileId string, retention model.Retention, status string, timespan int, deviceId string, search string, page int, limit int)) *Db_GetQueryLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 model.Retention
		if args[2] != nil {
			arg2 = args[2].(model.Retention)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		var arg6 string
		if args[6] != nil {
			arg6 = args[6].(string)
		}
		var arg7 int
		if args[7] != nil {
			arg7 = args[7].(int)
		}
		var arg8 int
		if args[8] != nil {
			arg8 = args[8].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
			arg7,
			arg8,
		)
	})
	return _c
}

func (_c *Db_GetQueryLogs_Call) Return(queryLogs []model.QueryLog, err error) *Db_GetQueryLogs_Call {
	_c.Call.Return(queryLogs, err)
	return _c
}

func (_c *Db_GetQueryLogs_Call) RunAndReturn(run func(ctx context.Context, profileId string, retention model.Retention, status string, timespan int, deviceId string, search string, page int, limit int) ([]model.QueryLog, error)) *Db_GetQueryLogs_Call {
	_c.Call.Return(run)
	return _c
}

// GetSession provides a mock function for the type Db
func (_mock *Db) GetSession(ctx context.Context, token string) (model.Session, bool, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 model.Session
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.Session, bool, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.Session); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Get(0).(model.Session)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, token)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// Db_GetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSession'
type Db_GetSession_Call struct {
	*mock.Call
}

// GetSession is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *Db_Expecter) GetSession(ctx interface{}, token interface{}) *Db_GetSession_Call {
	return &Db_GetSession_Call{Call: _e.mock.On("GetSession", ctx, token)}
}

func (_c *Db_GetSession_Call) Run(run func(ctx context.Context, token string)) *Db_GetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Db_GetSession_Call) Return(session model.Session, b bool, err error) *Db_GetSession_Call {
	_c.Call.Return(session, b, err)
	return _c
}

func (_c *Db_GetSession_Call) RunAndReturn(run func(ctx context.Context, token string) (model.Session, bool, error)) *Db_GetSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubscriptionByAccountId provides a mock function for the type Db
func (_mock *Db) GetSubscriptionByAccountId(ctx context.Context, accountId string) (*model.Subscription, error) {
	ret := _mock.Called(ctx, accountId)

	if len(ret) == 0 {
		panic("no return value specified for GetSubscriptionByAccountId")
	}

	var r0 *model.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Subscription, error)); ok {
		return returnFunc(ctx, accountId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Subscription); ok {
		r0 = returnFunc(ctx, accountId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accountId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Db_GetSubscriptionByAccountId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubscriptionByAccountId'
type Db_GetSubscriptionByAccountId_Call struct {
	*mock.Call
}

// GetSubscriptionByAccountId is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
func (_e *Db_Expecter) GetSubscriptionByAccountId(ctx interface{}, accountId interface{}) *Db_GetSubscriptionByAccountId_Call {
	return &Db_GetSubscriptionByAccountId_Call{Call: _e.mock.On("GetSubscriptionByAccountId", ctx, accountId)}
}

func (_c *Db_GetSubscriptionByAccountId_Call) Run(run func(ctx context.Context, accountId string)) *Db_GetSubscriptionByAccountId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Db_GetSubscriptionByAccountId_Call) Return(subscription *model.Subscription, err error) *Db_GetSubscriptionByAccountId_Call {
	_c.Call.Return(subscription, err)
	return _c
}

func (_c *Db_GetSubscriptionByAccountId_Call) RunAndReturn(run func(ctx context.Context, accountId string) (*model.Subscription, error)) *Db_GetSubscriptionByAccountId_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubscriptionById provides a mock function for the type Db
func (_mock *Db) GetSubscriptionById(ctx context.Context, subscriptionId string) (*model.Subscription, error) {
	ret := _mock.Called(ctx, subscriptionId)

	if len(ret) == 0 {
		panic("no return value specified for GetSubscriptionById")
	}

	var r0 *model.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Subscription, error)); ok {
		return returnFunc(ctx, subscriptionId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Subscription); ok {
		r0 = returnFunc(ctx, subscriptionId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, subscriptionId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Db_GetSubscriptionById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubscriptionById'
type Db_GetSubscriptionById_Call struct {
	*mock.Call
}

// GetSubscriptionById is a helper method to define mock.On call
//   - ctx context.Context
//   - subscriptionId string
func (_e *Db_Expecter) GetSubscriptionById(ctx interface{}, subscriptionId interface{}) *Db_GetSubscriptionById_Call {
	return &Db_GetSubscriptionById_Call{Call: _e.mock.On("GetSubscriptionById", ctx, subscriptionId)}
}

func (_c *Db_GetSubscriptionById_Call) Run(run func(ctx context.Context, subscriptionId string)) *Db_GetSubscriptionById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Db_GetSubscriptionById_Call) Return(subscription *model.Subscription, err error) *Db_GetSubscriptionById_Call {
	_c.Call.Return(subscription, err)
	return _c
}

func (_c *Db_GetSubscriptionById_Call) RunAndReturn(run func(ctx context.Context, subscriptionId string) (*model.Subscription, error)) *Db_GetSubscriptionById_Call {
	_c.Call.Return(run)
	return _c
}

// Migrate provides a mock function for the type Db
func (_mock *Db) Migrate() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Migrate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Db_Migrate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Migrate'
type Db_Migrate_Call struct {
	*mock.Call
}

// Migrate is a helper method to define mock.On call
func (_e *Db_Expecter) Migrate() *Db_Migrate_Call {
	return &Db_Migrate_Call{Call: _e.mock.On("Migrate")}
}

func (_c *Db_Migrate_Call) Run(run func()) *Db_Migrate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Db_Migrate_Call) Return(err error) *Db_Migrate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Db_Migrate_Call) RunAndReturn(run func() error) *Db_Migrate_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveCustomRules provides a mock function for the type Db
func (_mock *Db) RemoveCustomRules(ctx context.Context, profileId string, ruleIds []string) error {
	ret := _mock.Called(ctx, profileId, ruleIds)

	if len(ret) == 0 {
		panic("no return value specified for RemoveCustomRules")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = returnFunc(ctx, profileId, ruleIds)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Db_RemoveCustomRules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveCustomRules'
type Db_RemoveCustomRules_Call struct {
	*mock.Call
}

// RemoveCustomRules is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
//   - ruleIds []string
func (_e *Db_Expecter) RemoveCustomRules(ctx interface{}, profileId interface{}, ruleIds interface{}) *Db_RemoveCustomRules_Call {
	return &Db_RemoveCustomRules_Call{Call: _e.mock.On("RemoveCustomRules", ctx, profileId, ruleIds)}
}

func (_c *Db_RemoveCustomRules_Call) Run(run func(ctx context.Context, profileId string, ruleIds []string)) *Db_RemoveCustomRules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Db_RemoveCustomRules_Call) Return(err error) *Db_RemoveCustomRules_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Db_RemoveCustomRules_Call) RunAndReturn(run func(ctx context.Context, profileId string, ruleIds []string) error) *Db_RemoveCustomRules_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveProfileFromAccount provides a mock function for the type Db
func (_mock *Db) RemoveProfileFromAccount(ctx context.Context, accountId string, profileId string) error {
	ret := _mock.Called(ctx, accountId, profileId)

	if len(ret) == 0 {
		panic("no return value specified for RemoveProfileFromAccount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, accountId, profileId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Db_RemoveProfileFromAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveProfileFromAccount'
type Db_RemoveProfileFromAccount_Call struct {
	*mock.Call
}

// RemoveProfileFromAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
//   - profileId string
func (_e *Db_Expecter) RemoveProfileFromAccount(ctx interface{}, accountId interface{}, profileId interface{}) *Db_RemoveProfileFromAccount_Call {
	return &Db_RemoveProfileFromAccount_Call{Call: _e.mock.On("RemoveProfileFromAccount", ctx, accountId, profileId)}
}

func (_c *Db_RemoveProfileFromAccount_Call) Run(run func(ctx context.Context, accountId string, profileId string)) *Db_RemoveProfileFromAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Db_RemoveProfileFromAccount_Call) Return(err error) *Db_RemoveProfileFromAccount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Db_RemoveProfileFromAccount_Call) RunAndReturn(run func(ctx context.Context, accountId string, profileId string) error) *Db_RemoveProfileFromAccount_Call {
	_c.Call.Return(run)
	return _c
}

// SaveCredential provides a mock function for the type Db
func (_mock *Db) SaveCredential(ctx context.Context, credential webauthn.Credential, accountID primitive.ObjectID) error {
	ret := _mock.Called(ctx, credential, accountID)

	if len(ret) == 0 {
		panic("no return value specified for SaveCredential")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, webauthn.Credential, primitive.ObjectID) error); ok {
		r0 = returnFunc(ctx, credential, accountID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Db_SaveCredential_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveCredential'
type Db_SaveCredential_Call struct {
	*mock.Call
}

// SaveCredential is a helper method to define mock.On call
//   - ctx context.Context
//   - credential webauthn.Credential
//   - accountID primitive.ObjectID
func (_e *Db_Expecter) SaveCredential(ctx interface{}, credential interface{}, accountID interface{}) *Db_SaveCredential_Call {
	return &Db_SaveCredential_Call{Call: _e.mock.On("SaveCredential", ctx, credential, accountID)}
}

func (_c *Db_SaveCredential_Call) Run(run func(ctx context.Context, credential webauthn.Credential, accountID primitive.ObjectID)) *Db_SaveCredential_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 webauthn.Credential
		if args[1] != nil {
			arg1 = args[1].(webauthn.Credential)
		}
		var arg2 primitive.ObjectID
		if args[2] != nil {
			arg2 = args[2].(primitive.ObjectID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Db_SaveCredential_Call) Return(err error) *Db_SaveCredential_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Db_SaveCredential_Call) RunAndReturn(run func(ctx context.Context, credential webauthn.Credential, accountID primitive.ObjectID) error) *Db_SaveCredential_Call {
	_c.Call.Return(run)
	return _c
}

// SaveSession provides a mock function for the type Db
func (_mock *Db) SaveSession(ctx context.Context, sessionData webauthn.SessionData, token string, userID string, purpose string) error {
	ret := _mock.Called(ctx, sessionData, token, userID, purpose)

	if len(ret) == 0 {
		panic("no return value specified for SaveSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, webauthn.SessionData, string, string, string) error); ok {
		r0 = returnFunc(ctx, sessionData, token, userID, purpose)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Db_SaveSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveSession'
type Db_SaveSession_Call struct {
	*mock.Call
}

// SaveSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionData webauthn.SessionData
//   - token string
//   - userID string
//   - purpose string
func (_e *Db_Expecter) SaveSession(ctx interface{}, sessionData interface{}, token interface{}, userID interface{}, purpose interface{}) *Db_SaveSession_Call {
	return &Db_SaveSession_Call{Call: _e.mock.On("SaveSession", ctx, sessionData, token, userID, purpose)}
}

func (_c *Db_SaveSession_Call) Run(run func(ctx context.Context, sessionData webauthn.SessionData, token string, userID string, purpose string)) *Db_SaveSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 webauthn.SessionData
		if args[1] != nil {
			arg1 = args[1].(webauthn.SessionData)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *Db_SaveSession_Call) Return(err error) *Db_SaveSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Db_SaveSession_Call) RunAndReturn(run func(ctx context.Context, sessionData webauthn.SessionData, token string, userID string, purpose string) error) *Db_SaveSession_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type Db
func (_mock *Db) Update(ctx context.Context, profileId string, profile *model.Profile) error {
	ret := _mock.Called(ctx, profileId, profile)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.Profile) error); ok {
		r0 = returnFunc(ctx, profileId, profile)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Db_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type Db_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
//   - profile *model.Profile
func (_e *Db_Expecter) Update(ctx interface{}, profileId interface{}, profile interface{}) *Db_Update_Call {
	return &Db_Update_Call{Call: _e.mock.On("Update", ctx, profileId, profile)}
}

func (_c *Db_Update_Call) Run(run func(ctx context.Context, profileId string, profile *model.Profile)) *Db_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *model.Profile
		if args[2] != nil {
			arg2 = args[2].(*model.Profile)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Db_Update_Call) Return(err error) *Db_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Db_Update_Call) RunAndReturn(run func(ctx context.Context, profileId string, profile *model.Profile) error) *Db_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAccount provides a mock function for the type Db
func (_mock *Db) UpdateAccount(ctx context.Context, account *model.Account) (*model.Account, error) {
	ret := _mock.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAccount")
	}

	var r0 *model.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Account) (*model.Account, error)); ok {
		return returnFunc(ctx, account)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Account) *model.Account); ok {
		r0 = returnFunc(ctx, account)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.Account) error); ok {
		r1 = returnFunc(ctx, account)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Db_UpdateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAccount'
type Db_UpdateAccount_Call struct {
	*mock.Call
}

// UpdateAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - account *model.Account
func (_e *Db_Expecter) UpdateAccount(ctx interface{}, account interface{}) *Db_UpdateAccount_Call {
	return &Db_UpdateAccount_Call{Call: _e.mock.On("UpdateAccount", ctx, account)}
}

func (_c *Db_UpdateAccount_Call) Run(run func(ctx context.Context, account *model.Account)) *Db_UpdateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Account
		if args[1] != nil {
			arg1 = args[1].(*model.Account)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Db_UpdateAccount_Call) Return(account1 *model.Account, err error) *Db_UpdateAccount_Call {
	_c.Call.Return(account1, err)
	return _c
}

func (_c *Db_UpdateAccount_Call) RunAndReturn(run func(ctx context.Context, account *model.Account) (*model.Account, error)) *Db_UpdateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCredential provides a mock function for the type Db
func (_mock *Db) UpdateCredential(ctx context.Context, credential webauthn.Credential, accountID primitive.ObjectID) error {
	ret := _mock.Called(ctx, credential, accountID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCredential")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, webauthn.Credential, primitive.ObjectID) error); ok {
		r0 = returnFunc(ctx, credential, accountID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Db_UpdateCredential_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCredential'
type Db_UpdateCredential_Call struct {
	*mock.Call
}

// UpdateCredential is a helper method to define mock.On call
//   - ctx context.Context
//   - credential webauthn.Credential
//   - accountID primitive.ObjectID
func (_e *Db_Expecter) UpdateCredential(ctx interface{}, credential interface{}, accountID interface{}) *Db_UpdateCredential_Call {
	return &Db_UpdateCredential_Call{Call: _e.mock.On("UpdateCredential", ctx, credential, accountID)}
}

func (_c *Db_UpdateCredential_Call) Run(run func(ctx context.Context, credential webauthn.Credential, accountID primitive.ObjectID)) *Db_UpdateCredential_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 webauthn.Credential
		if args[1] != nil {
			arg1 = args[1].(webauthn.Credential)
		}
		var arg2 primitive.ObjectID
		if args[2] != nil {
			arg2 = args[2].(primitive.ObjectID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Db_UpdateCredential_Call) Return(err error) *Db_UpdateCredential_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Db_UpdateCredential_Call) RunAndReturn(run func(ctx context.Context, credential webauthn.Credential, accountID primitive.ObjectID) error) *Db_UpdateCredential_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDeletionCode provides a mock function for the type Db
func (_mock *Db) UpdateDeletionCode(ctx context.Context, accountId string, code string, expiresAt time.Time) error {
	ret := _mock.Called(ctx, accountId, code, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDeletionCode")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Time) error); ok {
		r0 = returnFunc(ctx, accountId, code, expiresAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Db_UpdateDeletionCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDeletionCode'
type Db_UpdateDeletionCode_Call struct {
	*mock.Call
}

// UpdateDeletionCode is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
//   - code string
//   - expiresAt time.Time
func (_e *Db_Expecter) UpdateDeletionCode(ctx interface{}, accountId interface{}, code interface{}, expiresAt interface{}) *Db_UpdateDeletionCode_Call {
	return &Db_UpdateDeletionCode_Call{Call: _e.mock.On("UpdateDeletionCode", ctx, accountId, code, expiresAt)}
}

func (_c *Db_UpdateDeletionCode_Call) Run(run func(ctx context.Context, accountId string, code string, expiresAt time.Time)) *Db_UpdateDeletionCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Db_UpdateDeletionCode_Call) Return(err error) *Db_UpdateDeletionCode_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Db_UpdateDeletionCode_Call) RunAndReturn(run func(ctx context.Context, accountId string, code string, expiresAt time.Time) error) *Db_UpdateDeletionCode_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSettings provides a mock function for the type Db
func (_mock *Db) UpdateSettings(ctx context.Context, profileId string, settings *model.ProfileSettings) error {
	ret := _mock.Called(ctx, profileId, settings)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSettings")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.ProfileSettings) error); ok {
		r0 = returnFunc(ctx, profileId, settings)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Db_UpdateSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSettings'
type Db_UpdateSettings_Call struct {
	*mock.Call
}

// UpdateSettings is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
//   - settings *model.ProfileSettings
func (_e *Db_Expecter) UpdateSettings(ctx interface{}, profileId interface{}, settings interface{}) *Db_UpdateSettings_Call {
	return &Db_UpdateSettings_Call{Call: _e.mock.On("UpdateSettings", ctx, profileId, settings)}
}

func (_c *Db_UpdateSettings_Call) Run(run func(ctx context.Context, profileId string, settings *model.ProfileSettings)) *Db_UpdateSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *model.ProfileSettings
		if args[2] != nil {
			arg2 = args[2].(*model.ProfileSettings)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Db_UpdateSettings_Call) Return(err error) *Db_UpdateSettings_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Db_UpdateSettings_Call) RunAndReturn(run func(ctx context.Context, profileId string, settings *model.ProfileSettings) error) *Db_UpdateSettings_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type Db
func (_mock *Db) Upsert(ctx context.Context, subscription model.Subscription) error {
	ret := _mock.Called(ctx, subscription)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Subscription) error); ok {
		r0 = returnFunc(ctx, subscription)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Db_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type Db_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - subscription model.Subscription
func (_e *Db_Expecter) Upsert(ctx interface{}, subscription interface{}) *Db_Upsert_Call {
	return &Db_Upsert_Call{Call: _e.mock.On("Upsert", ctx, subscription)}
}

func (_c *Db_Upsert_Call) Run(run func(ctx context.Context, subscription model.Subscription)) *Db_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Subscription
		if args[1] != nil {
			arg1 = args[1].(model.Subscription)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Db_Upsert_Call) Return(err error) *Db_Upsert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Db_Upsert_Call) RunAndReturn(run func(ctx context.Context, subscription model.Subscription) error) *Db_Upsert_Call {
	_c.Call.Return(run)
	return _c
}
