// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewGeneratoridgen creates a new instance of Generatoridgen. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGeneratoridgen(t interface {
	mock.TestingT
	Cleanup(func())
}) *Generatoridgen {
	mock := &Generatoridgen{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Generatoridgen is an autogenerated mock type for the Generator type
type Generatoridgen struct {
	mock.Mock
}

type Generatoridgen_Expecter struct {
	mock *mock.Mock
}

func (_m *Generatoridgen) EXPECT() *Generatoridgen_Expecter {
	return &Generatoridgen_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function for the type Generatoridgen
func (_mock *Generatoridgen) Generate() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Generatoridgen_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type Generatoridgen_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
func (_e *Generatoridgen_Expecter) Generate() *Generatoridgen_Generate_Call {
	return &Generatoridgen_Generate_Call{Call: _e.mock.On("Generate")}
}

func (_c *Generatoridgen_Generate_Call) Run(run func()) *Generatoridgen_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Generatoridgen_Generate_Call) Return(s string, err error) *Generatoridgen_Generate_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Generatoridgen_Generate_Call) RunAndReturn(run func() (string, error)) *Generatoridgen_Generate_Call {
	_c.Call.Return(run)
	return _c
}
