// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMaileremail creates a new instance of Maileremail. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMaileremail(t interface {
	mock.TestingT
	Cleanup(func())
}) *Maileremail {
	mock := &Maileremail{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Maileremail is an autogenerated mock type for the Mailer type
type Maileremail struct {
	mock.Mock
}

type Maileremail_Expecter struct {
	mock *mock.Mock
}

func (_m *Maileremail) EXPECT() *Maileremail_Expecter {
	return &Maileremail_Expecter{mock: &_m.Mock}
}

// SendEmailVerificationOTP provides a mock function for the type Maileremail
func (_mock *Maileremail) SendEmailVerificationOTP(ctx context.Context, sendTo string, otp string) error {
	ret := _mock.Called(ctx, sendTo, otp)

	if len(ret) == 0 {
		panic("no return value specified for SendEmailVerificationOTP")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, sendTo, otp)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Maileremail_SendEmailVerificationOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendEmailVerificationOTP'
type Maileremail_SendEmailVerificationOTP_Call struct {
	*mock.Call
}

// SendEmailVerificationOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - sendTo string
//   - otp string
func (_e *Maileremail_Expecter) SendEmailVerificationOTP(ctx interface{}, sendTo interface{}, otp interface{}) *Maileremail_SendEmailVerificationOTP_Call {
	return &Maileremail_SendEmailVerificationOTP_Call{Call: _e.mock.On("SendEmailVerificationOTP", ctx, sendTo, otp)}
}

func (_c *Maileremail_SendEmailVerificationOTP_Call) Run(run func(ctx context.Context, sendTo string, otp string)) *Maileremail_SendEmailVerificationOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Maileremail_SendEmailVerificationOTP_Call) Return(err error) *Maileremail_SendEmailVerificationOTP_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Maileremail_SendEmailVerificationOTP_Call) RunAndReturn(run func(ctx context.Context, sendTo string, otp string) error) *Maileremail_SendEmailVerificationOTP_Call {
	_c.Call.Return(run)
	return _c
}

// SendPasswordResetEmail provides a mock function for the type Maileremail
func (_mock *Maileremail) SendPasswordResetEmail(ctx context.Context, sendTo string, passwordResetToken string) error {
	ret := _mock.Called(ctx, sendTo, passwordResetToken)

	if len(ret) == 0 {
		panic("no return value specified for SendPasswordResetEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, sendTo, passwordResetToken)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Maileremail_SendPasswordResetEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendPasswordResetEmail'
type Maileremail_SendPasswordResetEmail_Call struct {
	*mock.Call
}

// SendPasswordResetEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - sendTo string
//   - passwordResetToken string
func (_e *Maileremail_Expecter) SendPasswordResetEmail(ctx interface{}, sendTo interface{}, passwordResetToken interface{}) *Maileremail_SendPasswordResetEmail_Call {
	return &Maileremail_SendPasswordResetEmail_Call{Call: _e.mock.On("SendPasswordResetEmail", ctx, sendTo, passwordResetToken)}
}

func (_c *Maileremail_SendPasswordResetEmail_Call) Run(run func(ctx context.Context, sendTo string, passwordResetToken string)) *Maileremail_SendPasswordResetEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Maileremail_SendPasswordResetEmail_Call) Return(err error) *Maileremail_SendPasswordResetEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Maileremail_SendPasswordResetEmail_Call) RunAndReturn(run func(ctx context.Context, sendTo string, passwordResetToken string) error) *Maileremail_SendPasswordResetEmail_Call {
	_c.Call.Return(run)
	return _c
}

// SendWelcomeEmail provides a mock function for the type Maileremail
func (_mock *Maileremail) SendWelcomeEmail(ctx context.Context, sendTo string, confirmationToken string) error {
	ret := _mock.Called(ctx, sendTo, confirmationToken)

	if len(ret) == 0 {
		panic("no return value specified for SendWelcomeEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, sendTo, confirmationToken)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Maileremail_SendWelcomeEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendWelcomeEmail'
type Maileremail_SendWelcomeEmail_Call struct {
	*mock.Call
}

// SendWelcomeEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - sendTo string
//   - confirmationToken string
func (_e *Maileremail_Expecter) SendWelcomeEmail(ctx interface{}, sendTo interface{}, confirmationToken interface{}) *Maileremail_SendWelcomeEmail_Call {
	return &Maileremail_SendWelcomeEmail_Call{Call: _e.mock.On("SendWelcomeEmail", ctx, sendTo, confirmationToken)}
}

func (_c *Maileremail_SendWelcomeEmail_Call) Run(run func(ctx context.Context, sendTo string, confirmationToken string)) *Maileremail_SendWelcomeEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Maileremail_SendWelcomeEmail_Call) Return(err error) *Maileremail_SendWelcomeEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Maileremail_SendWelcomeEmail_Call) RunAndReturn(run func(ctx context.Context, sendTo string, confirmationToken string) error) *Maileremail_SendWelcomeEmail_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function for the type Maileremail
func (_mock *Maileremail) Verify(email string) error {
	ret := _mock.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(email)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Maileremail_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type Maileremail_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - email string
func (_e *Maileremail_Expecter) Verify(email interface{}) *Maileremail_Verify_Call {
	return &Maileremail_Verify_Call{Call: _e.mock.On("Verify", email)}
}

func (_c *Maileremail_Verify_Call) Run(run func(email string)) *Maileremail_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Maileremail_Verify_Call) Return(err error) *Maileremail_Verify_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Maileremail_Verify_Call) RunAndReturn(run func(email string) error) *Maileremail_Verify_Call {
	_c.Call.Return(run)
	return _c
}
