// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"net/http"

	"github.com/go-webauthn/webauthn/protocol"
	"github.com/ivpn/dns/api/model"
	mock "github.com/stretchr/testify/mock"
)

// NewPasskeyServicer creates a new instance of PasskeyServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPasskeyServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *PasskeyServicer {
	mock := &PasskeyServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PasskeyServicer is an autogenerated mock type for the PasskeyServicer type
type PasskeyServicer struct {
	mock.Mock
}

type PasskeyServicer_Expecter struct {
	mock *mock.Mock
}

func (_m *PasskeyServicer) EXPECT() *PasskeyServicer_Expecter {
	return &PasskeyServicer_Expecter{mock: &_m.Mock}
}

// BeginLogin provides a mock function for the type PasskeyServicer
func (_mock *PasskeyServicer) BeginLogin(ctx context.Context, email string) (*protocol.CredentialAssertion, string, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for BeginLogin")
	}

	var r0 *protocol.CredentialAssertion
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*protocol.CredentialAssertion, string, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *protocol.CredentialAssertion); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*protocol.CredentialAssertion)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, email)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// PasskeyServicer_BeginLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginLogin'
type PasskeyServicer_BeginLogin_Call struct {
	*mock.Call
}

// BeginLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *PasskeyServicer_Expecter) BeginLogin(ctx interface{}, email interface{}) *PasskeyServicer_BeginLogin_Call {
	return &PasskeyServicer_BeginLogin_Call{Call: _e.mock.On("BeginLogin", ctx, email)}
}

func (_c *PasskeyServicer_BeginLogin_Call) Run(run func(ctx context.Context, email string)) *PasskeyServicer_BeginLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PasskeyServicer_BeginLogin_Call) Return(credentialAssertion *protocol.CredentialAssertion, s string, err error) *PasskeyServicer_BeginLogin_Call {
	_c.Call.Return(credentialAssertion, s, err)
	return _c
}

func (_c *PasskeyServicer_BeginLogin_Call) RunAndReturn(run func(ctx context.Context, email string) (*protocol.CredentialAssertion, string, error)) *PasskeyServicer_BeginLogin_Call {
	_c.Call.Return(run)
	return _c
}

// BeginReauth provides a mock function for the type PasskeyServicer
func (_mock *PasskeyServicer) BeginReauth(ctx context.Context, purpose string, accountID string) (*protocol.CredentialAssertion, string, error) {
	ret := _mock.Called(ctx, purpose, accountID)

	if len(ret) == 0 {
		panic("no return value specified for BeginReauth")
	}

	var r0 *protocol.CredentialAssertion
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*protocol.CredentialAssertion, string, error)); ok {
		return returnFunc(ctx, purpose, accountID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *protocol.CredentialAssertion); ok {
		r0 = returnFunc(ctx, purpose, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*protocol.CredentialAssertion)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = returnFunc(ctx, purpose, accountID)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, purpose, accountID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// PasskeyServicer_BeginReauth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginReauth'
type PasskeyServicer_BeginReauth_Call struct {
	*mock.Call
}

// BeginReauth is a helper method to define mock.On call
//   - ctx context.Context
//   - purpose string
//   - accountID string
func (_e *PasskeyServicer_Expecter) BeginReauth(ctx interface{}, purpose interface{}, accountID interface{}) *PasskeyServicer_BeginReauth_Call {
	return &PasskeyServicer_BeginReauth_Call{Call: _e.mock.On("BeginReauth", ctx, purpose, accountID)}
}

func (_c *PasskeyServicer_BeginReauth_Call) Run(run func(ctx context.Context, purpose string, accountID string)) *PasskeyServicer_BeginReauth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *PasskeyServicer_BeginReauth_Call) Return(credentialAssertion *protocol.CredentialAssertion, s string, err error) *PasskeyServicer_BeginReauth_Call {
	_c.Call.Return(credentialAssertion, s, err)
	return _c
}

func (_c *PasskeyServicer_BeginReauth_Call) RunAndReturn(run func(ctx context.Context, purpose string, accountID string) (*protocol.CredentialAssertion, string, error)) *PasskeyServicer_BeginReauth_Call {
	_c.Call.Return(run)
	return _c
}

// BeginRegistration provides a mock function for the type PasskeyServicer
func (_mock *PasskeyServicer) BeginRegistration(ctx context.Context, account *model.Account) (*protocol.CredentialCreation, string, error) {
	ret := _mock.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for BeginRegistration")
	}

	var r0 *protocol.CredentialCreation
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Account) (*protocol.CredentialCreation, string, error)); ok {
		return returnFunc(ctx, account)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Account) *protocol.CredentialCreation); ok {
		r0 = returnFunc(ctx, account)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*protocol.CredentialCreation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.Account) string); ok {
		r1 = returnFunc(ctx, account)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *model.Account) error); ok {
		r2 = returnFunc(ctx, account)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// PasskeyServicer_BeginRegistration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginRegistration'
type PasskeyServicer_BeginRegistration_Call struct {
	*mock.Call
}

// BeginRegistration is a helper method to define mock.On call
//   - ctx context.Context
//   - account *model.Account
func (_e *PasskeyServicer_Expecter) BeginRegistration(ctx interface{}, account interface{}) *PasskeyServicer_BeginRegistration_Call {
	return &PasskeyServicer_BeginRegistration_Call{Call: _e.mock.On("BeginRegistration", ctx, account)}
}

func (_c *PasskeyServicer_BeginRegistration_Call) Run(run func(ctx context.Context, account *model.Account)) *PasskeyServicer_BeginRegistration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Account
		if args[1] != nil {
			arg1 = args[1].(*model.Account)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PasskeyServicer_BeginRegistration_Call) Return(credentialCreation *protocol.CredentialCreation, s string, err error) *PasskeyServicer_BeginRegistration_Call {
	_c.Call.Return(credentialCreation, s, err)
	return _c
}

func (_c *PasskeyServicer_BeginRegistration_Call) RunAndReturn(run func(ctx context.Context, account *model.Account) (*protocol.CredentialCreation, string, error)) *PasskeyServicer_BeginRegistration_Call {
	_c.Call.Return(run)
	return _c
}

// FinishLogin provides a mock function for the type PasskeyServicer
func (_mock *PasskeyServicer) FinishLogin(ctx context.Context, token string, httpReq *http.Request, saveSession bool) (*model.Account, string, string, error) {
	ret := _mock.Called(ctx, token, httpReq, saveSession)

	if len(ret) == 0 {
		panic("no return value specified for FinishLogin")
	}

	var r0 *model.Account
	var r1 string
	var r2 string
	var r3 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *http.Request, bool) (*model.Account, string, string, error)); ok {
		return returnFunc(ctx, token, httpReq, saveSession)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *http.Request, bool) *model.Account); ok {
		r0 = returnFunc(ctx, token, httpReq, saveSession)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *http.Request, bool) string); ok {
		r1 = returnFunc(ctx, token, httpReq, saveSession)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, *http.Request, bool) string); ok {
		r2 = returnFunc(ctx, token, httpReq, saveSession)
	} else {
		r2 = ret.Get(2).(string)
	}
	if returnFunc, ok := ret.Get(3).(func(context.Context, string, *http.Request, bool) error); ok {
		r3 = returnFunc(ctx, token, httpReq, saveSession)
	} else {
		r3 = ret.Error(3)
	}
	return r0, r1, r2, r3
}

// PasskeyServicer_FinishLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FinishLogin'
type PasskeyServicer_FinishLogin_Call struct {
	*mock.Call
}

// FinishLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - httpReq *http.Request
//   - saveSession bool
func (_e *PasskeyServicer_Expecter) FinishLogin(ctx interface{}, token interface{}, httpReq interface{}, saveSession interface{}) *PasskeyServicer_FinishLogin_Call {
	return &PasskeyServicer_FinishLogin_Call{Call: _e.mock.On("FinishLogin", ctx, token, httpReq, saveSession)}
}

func (_c *PasskeyServicer_FinishLogin_Call) Run(run func(ctx context.Context, token string, httpReq *http.Request, saveSession bool)) *PasskeyServicer_FinishLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *http.Request
		if args[2] != nil {
			arg2 = args[2].(*http.Request)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *PasskeyServicer_FinishLogin_Call) Return(account *model.Account, s string, s1 string, err error) *PasskeyServicer_FinishLogin_Call {
	_c.Call.Return(account, s, s1, err)
	return _c
}

func (_c *PasskeyServicer_FinishLogin_Call) RunAndReturn(run func(ctx context.Context, token string, httpReq *http.Request, saveSession bool) (*model.Account, string, string, error)) *PasskeyServicer_FinishLogin_Call {
	_c.Call.Return(run)
	return _c
}

// FinishReauth provides a mock function for the type PasskeyServicer
func (_mock *PasskeyServicer) FinishReauth(ctx context.Context, token string, httpReq *http.Request) (*model.Token, error) {
	ret := _mock.Called(ctx, token, httpReq)

	if len(ret) == 0 {
		panic("no return value specified for FinishReauth")
	}

	var r0 *model.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *http.Request) (*model.Token, error)); ok {
		return returnFunc(ctx, token, httpReq)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *http.Request) *model.Token); ok {
		r0 = returnFunc(ctx, token, httpReq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *http.Request) error); ok {
		r1 = returnFunc(ctx, token, httpReq)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PasskeyServicer_FinishReauth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FinishReauth'
type PasskeyServicer_FinishReauth_Call struct {
	*mock.Call
}

// FinishReauth is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - httpReq *http.Request
func (_e *PasskeyServicer_Expecter) FinishReauth(ctx interface{}, token interface{}, httpReq interface{}) *PasskeyServicer_FinishReauth_Call {
	return &PasskeyServicer_FinishReauth_Call{Call: _e.mock.On("FinishReauth", ctx, token, httpReq)}
}

func (_c *PasskeyServicer_FinishReauth_Call) Run(run func(ctx context.Context, token string, httpReq *http.Request)) *PasskeyServicer_FinishReauth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *http.Request
		if args[2] != nil {
			arg2 = args[2].(*http.Request)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *PasskeyServicer_FinishReauth_Call) Return(token1 *model.Token, err error) *PasskeyServicer_FinishReauth_Call {
	_c.Call.Return(token1, err)
	return _c
}

func (_c *PasskeyServicer_FinishReauth_Call) RunAndReturn(run func(ctx context.Context, token string, httpReq *http.Request) (*model.Token, error)) *PasskeyServicer_FinishReauth_Call {
	_c.Call.Return(run)
	return _c
}

// FinishRegistration provides a mock function for the type PasskeyServicer
func (_mock *PasskeyServicer) FinishRegistration(ctx context.Context, token string, httpReq *http.Request) error {
	ret := _mock.Called(ctx, token, httpReq)

	if len(ret) == 0 {
		panic("no return value specified for FinishRegistration")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *http.Request) error); ok {
		r0 = returnFunc(ctx, token, httpReq)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PasskeyServicer_FinishRegistration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FinishRegistration'
type PasskeyServicer_FinishRegistration_Call struct {
	*mock.Call
}

// FinishRegistration is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - httpReq *http.Request
func (_e *PasskeyServicer_Expecter) FinishRegistration(ctx interface{}, token interface{}, httpReq interface{}) *PasskeyServicer_FinishRegistration_Call {
	return &PasskeyServicer_FinishRegistration_Call{Call: _e.mock.On("FinishRegistration", ctx, token, httpReq)}
}

func (_c *PasskeyServicer_FinishRegistration_Call) Run(run func(ctx context.Context, token string, httpReq *http.Request)) *PasskeyServicer_FinishRegistration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *http.Request
		if args[2] != nil {
			arg2 = args[2].(*http.Request)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *PasskeyServicer_FinishRegistration_Call) Return(err error) *PasskeyServicer_FinishRegistration_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PasskeyServicer_FinishRegistration_Call) RunAndReturn(run func(ctx context.Context, token string, httpReq *http.Request) error) *PasskeyServicer_FinishRegistration_Call {
	_c.Call.Return(run)
	return _c
}

// GetPasskeys provides a mock function for the type PasskeyServicer
func (_mock *PasskeyServicer) GetPasskeys(ctx context.Context, account *model.Account) ([]model.Credential, error) {
	ret := _mock.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for GetPasskeys")
	}

	var r0 []model.Credential
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Account) ([]model.Credential, error)); ok {
		return returnFunc(ctx, account)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Account) []model.Credential); ok {
		r0 = returnFunc(ctx, account)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Credential)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.Account) error); ok {
		r1 = returnFunc(ctx, account)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PasskeyServicer_GetPasskeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPasskeys'
type PasskeyServicer_GetPasskeys_Call struct {
	*mock.Call
}

// GetPasskeys is a helper method to define mock.On call
//   - ctx context.Context
//   - account *model.Account
func (_e *PasskeyServicer_Expecter) GetPasskeys(ctx interface{}, account interface{}) *PasskeyServicer_GetPasskeys_Call {
	return &PasskeyServicer_GetPasskeys_Call{Call: _e.mock.On("GetPasskeys", ctx, account)}
}

func (_c *PasskeyServicer_GetPasskeys_Call) Run(run func(ctx context.Context, account *model.Account)) *PasskeyServicer_GetPasskeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Account
		if args[1] != nil {
			arg1 = args[1].(*model.Account)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PasskeyServicer_GetPasskeys_Call) Return(credentials []model.Credential, err error) *PasskeyServicer_GetPasskeys_Call {
	_c.Call.Return(credentials, err)
	return _c
}

func (_c *PasskeyServicer_GetPasskeys_Call) RunAndReturn(run func(ctx context.Context, account *model.Account) ([]model.Credential, error)) *PasskeyServicer_GetPasskeys_Call {
	_c.Call.Return(run)
	return _c
}
