// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ivpn/dns/api/model"
	"github.com/ivpn/dns/api/service/profile"
	mock "github.com/stretchr/testify/mock"
)

// NewProfileServicer creates a new instance of ProfileServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProfileServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProfileServicer {
	mock := &ProfileServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ProfileServicer is an autogenerated mock type for the ProfileServicer type
type ProfileServicer struct {
	mock.Mock
}

type ProfileServicer_Expecter struct {
	mock *mock.Mock
}

func (_m *ProfileServicer) EXPECT() *ProfileServicer_Expecter {
	return &ProfileServicer_Expecter{mock: &_m.Mock}
}

// CreateCustomRule provides a mock function for the type ProfileServicer
func (_mock *ProfileServicer) CreateCustomRule(ctx context.Context, accountId string, profileId string, action string, value string) error {
	ret := _mock.Called(ctx, accountId, profileId, action, value)

	if len(ret) == 0 {
		panic("no return value specified for CreateCustomRule")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = returnFunc(ctx, accountId, profileId, action, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProfileServicer_CreateCustomRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCustomRule'
type ProfileServicer_CreateCustomRule_Call struct {
	*mock.Call
}

// CreateCustomRule is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
//   - profileId string
//   - action string
//   - value string
func (_e *ProfileServicer_Expecter) CreateCustomRule(ctx interface{}, accountId interface{}, profileId interface{}, action interface{}, value interface{}) *ProfileServicer_CreateCustomRule_Call {
	return &ProfileServicer_CreateCustomRule_Call{Call: _e.mock.On("CreateCustomRule", ctx, accountId, profileId, action, value)}
}

func (_c *ProfileServicer_CreateCustomRule_Call) Run(run func(ctx context.Context, accountId string, profileId string, action string, value string)) *ProfileServicer_CreateCustomRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *ProfileServicer_CreateCustomRule_Call) Return(err error) *ProfileServicer_CreateCustomRule_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProfileServicer_CreateCustomRule_Call) RunAndReturn(run func(ctx context.Context, accountId string, profileId string, action string, value string) error) *ProfileServicer_CreateCustomRule_Call {
	_c.Call.Return(run)
	return _c
}

// CreateCustomRulesBulk provides a mock function for the type ProfileServicer
func (_mock *ProfileServicer) CreateCustomRulesBulk(ctx context.Context, accountId string, profileId string, action string, values []string) (*profile.BulkCustomRuleResult, error) {
	ret := _mock.Called(ctx, accountId, profileId, action, values)

	if len(ret) == 0 {
		panic("no return value specified for CreateCustomRulesBulk")
	}

	var r0 *profile.BulkCustomRuleResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, []string) (*profile.BulkCustomRuleResult, error)); ok {
		return returnFunc(ctx, accountId, profileId, action, values)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, []string) *profile.BulkCustomRuleResult); ok {
		r0 = returnFunc(ctx, accountId, profileId, action, values)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*profile.BulkCustomRuleResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, []string) error); ok {
		r1 = returnFunc(ctx, accountId, profileId, action, values)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProfileServicer_CreateCustomRulesBulk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCustomRulesBulk'
type ProfileServicer_CreateCustomRulesBulk_Call struct {
	*mock.Call
}

// CreateCustomRulesBulk is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
//   - profileId string
//   - action string
//   - values []string
func (_e *ProfileServicer_Expecter) CreateCustomRulesBulk(ctx interface{}, accountId interface{}, profileId interface{}, action interface{}, values interface{}) *ProfileServicer_CreateCustomRulesBulk_Call {
	return &ProfileServicer_CreateCustomRulesBulk_Call{Call: _e.mock.On("CreateCustomRulesBulk", ctx, accountId, profileId, action, values)}
}

func (_c *ProfileServicer_CreateCustomRulesBulk_Call) Run(run func(ctx context.Context, accountId string, profileId string, action string, values []string)) *ProfileServicer_CreateCustomRulesBulk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []string
		if args[4] != nil {
			arg4 = args[4].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *ProfileServicer_CreateCustomRulesBulk_Call) Return(bulkCustomRuleResult *profile.BulkCustomRuleResult, err error) *ProfileServicer_CreateCustomRulesBulk_Call {
	_c.Call.Return(bulkCustomRuleResult, err)
	return _c
}

func (_c *ProfileServicer_CreateCustomRulesBulk_Call) RunAndReturn(run func(ctx context.Context, accountId string, profileId string, action string, values []string) (*profile.BulkCustomRuleResult, error)) *ProfileServicer_CreateCustomRulesBulk_Call {
	_c.Call.Return(run)
	return _c
}

// CreateProfile provides a mock function for the type ProfileServicer
func (_mock *ProfileServicer) CreateProfile(ctx context.Context, name string, accountId string) (*model.Profile, error) {
	ret := _mock.Called(ctx, name, accountId)

	if len(ret) == 0 {
		panic("no return value specified for CreateProfile")
	}

	var r0 *model.Profile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*model.Profile, error)); ok {
		return returnFunc(ctx, name, accountId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *model.Profile); ok {
		r0 = returnFunc(ctx, name, accountId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Profile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, name, accountId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProfileServicer_CreateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProfile'
type ProfileServicer_CreateProfile_Call struct {
	*mock.Call
}

// CreateProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - accountId string
func (_e *ProfileServicer_Expecter) CreateProfile(ctx interface{}, name interface{}, accountId interface{}) *ProfileServicer_CreateProfile_Call {
	return &ProfileServicer_CreateProfile_Call{Call: _e.mock.On("CreateProfile", ctx, name, accountId)}
}

func (_c *ProfileServicer_CreateProfile_Call) Run(run func(ctx context.Context, name string, accountId string)) *ProfileServicer_CreateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ProfileServicer_CreateProfile_Call) Return(profile1 *model.Profile, err error) *ProfileServicer_CreateProfile_Call {
	_c.Call.Return(profile1, err)
	return _c
}

func (_c *ProfileServicer_CreateProfile_Call) RunAndReturn(run func(ctx context.Context, name string, accountId string) (*model.Profile, error)) *ProfileServicer_CreateProfile_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCustomRule provides a mock function for the type ProfileServicer
func (_mock *ProfileServicer) DeleteCustomRule(ctx context.Context, accountId string, profileId string, customRuleId string) error {
	ret := _mock.Called(ctx, accountId, profileId, customRuleId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCustomRule")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, accountId, profileId, customRuleId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProfileServicer_DeleteCustomRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCustomRule'
type ProfileServicer_DeleteCustomRule_Call struct {
	*mock.Call
}

// DeleteCustomRule is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
//   - profileId string
//   - customRuleId string
func (_e *ProfileServicer_Expecter) DeleteCustomRule(ctx interface{}, accountId interface{}, profileId interface{}, customRuleId interface{}) *ProfileServicer_DeleteCustomRule_Call {
	return &ProfileServicer_DeleteCustomRule_Call{Call: _e.mock.On("DeleteCustomRule", ctx, accountId, profileId, customRuleId)}
}

func (_c *ProfileServicer_DeleteCustomRule_Call) Run(run func(ctx context.Context, accountId string, profileId string, customRuleId string)) *ProfileServicer_DeleteCustomRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ProfileServicer_DeleteCustomRule_Call) Return(err error) *ProfileServicer_DeleteCustomRule_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProfileServicer_DeleteCustomRule_Call) RunAndReturn(run func(ctx context.Context, accountId string, profileId string, customRuleId string) error) *ProfileServicer_DeleteCustomRule_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProfile provides a mock function for the type ProfileServicer
func (_mock *ProfileServicer) DeleteProfile(ctx context.Context, accountId string, profileId string, removeLast bool) error {
	ret := _mock.Called(ctx, accountId, profileId, removeLast)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProfile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, bool) error); ok {
		r0 = returnFunc(ctx, accountId, profileId, removeLast)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProfileServicer_DeleteProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProfile'
type ProfileServicer_DeleteProfile_Call struct {
	*mock.Call
}

// DeleteProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
//   - profileId string
//   - removeLast bool
func (_e *ProfileServicer_Expecter) DeleteProfile(ctx interface{}, accountId interface{}, profileId interface{}, removeLast interface{}) *ProfileServicer_DeleteProfile_Call {
	return &ProfileServicer_DeleteProfile_Call{Call: _e.mock.On("DeleteProfile", ctx, accountId, profileId, removeLast)}
}

func (_c *ProfileServicer_DeleteProfile_Call) Run(run func(ctx context.Context, accountId string, profileId string, removeLast bool)) *ProfileServicer_DeleteProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ProfileServicer_DeleteProfile_Call) Return(err error) *ProfileServicer_DeleteProfile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProfileServicer_DeleteProfile_Call) RunAndReturn(run func(ctx context.Context, accountId string, profileId string, removeLast bool) error) *ProfileServicer_DeleteProfile_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProfileQueryLogs provides a mock function for the type ProfileServicer
func (_mock *ProfileServicer) DeleteProfileQueryLogs(ctx context.Context, accountId string, profileId string) error {
	ret := _mock.Called(ctx, accountId, profileId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProfileQueryLogs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, accountId, profileId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProfileServicer_DeleteProfileQueryLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProfileQueryLogs'
type ProfileServicer_DeleteProfileQueryLogs_Call struct {
	*mock.Call
}

// DeleteProfileQueryLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
//   - profileId string
func (_e *ProfileServicer_Expecter) DeleteProfileQueryLogs(ctx interface{}, accountId interface{}, profileId interface{}) *ProfileServicer_DeleteProfileQueryLogs_Call {
	return &ProfileServicer_DeleteProfileQueryLogs_Call{Call: _e.mock.On("DeleteProfileQueryLogs", ctx, accountId, profileId)}
}

func (_c *ProfileServicer_DeleteProfileQueryLogs_Call) Run(run func(ctx context.Context, accountId string, profileId string)) *ProfileServicer_DeleteProfileQueryLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ProfileServicer_DeleteProfileQueryLogs_Call) Return(err error) *ProfileServicer_DeleteProfileQueryLogs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProfileServicer_DeleteProfileQueryLogs_Call) RunAndReturn(run func(ctx context.Context, accountId string, profileId string) error) *ProfileServicer_DeleteProfileQueryLogs_Call {
	_c.Call.Return(run)
	return _c
}

// DisableBlocklists provides a mock function for the type ProfileServicer
func (_mock *ProfileServicer) DisableBlocklists(ctx context.Context, accountId string, profileId string, blocklistIds []string) error {
	ret := _mock.Called(ctx, accountId, profileId, blocklistIds)

	if len(ret) == 0 {
		panic("no return value specified for DisableBlocklists")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []string) error); ok {
		r0 = returnFunc(ctx, accountId, profileId, blocklistIds)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProfileServicer_DisableBlocklists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisableBlocklists'
type ProfileServicer_DisableBlocklists_Call struct {
	*mock.Call
}

// DisableBlocklists is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
//   - profileId string
//   - blocklistIds []string
func (_e *ProfileServicer_Expecter) DisableBlocklists(ctx interface{}, accountId interface{}, profileId interface{}, blocklistIds interface{}) *ProfileServicer_DisableBlocklists_Call {
	return &ProfileServicer_DisableBlocklists_Call{Call: _e.mock.On("DisableBlocklists", ctx, accountId, profileId, blocklistIds)}
}

func (_c *ProfileServicer_DisableBlocklists_Call) Run(run func(ctx context.Context, accountId string, profileId string, blocklistIds []string)) *ProfileServicer_DisableBlocklists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []string
		if args[3] != nil {
			arg3 = args[3].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ProfileServicer_DisableBlocklists_Call) Return(err error) *ProfileServicer_DisableBlocklists_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProfileServicer_DisableBlocklists_Call) RunAndReturn(run func(ctx context.Context, accountId string, profileId string, blocklistIds []string) error) *ProfileServicer_DisableBlocklists_Call {
	_c.Call.Return(run)
	return _c
}

// DisableServices provides a mock function for the type ProfileServicer
func (_mock *ProfileServicer) DisableServices(ctx context.Context, accountId string, profileId string, serviceIds []string) error {
	ret := _mock.Called(ctx, accountId, profileId, serviceIds)

	if len(ret) == 0 {
		panic("no return value specified for DisableServices")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []string) error); ok {
		r0 = returnFunc(ctx, accountId, profileId, serviceIds)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProfileServicer_DisableServices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisableServices'
type ProfileServicer_DisableServices_Call struct {
	*mock.Call
}

// DisableServices is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
//   - profileId string
//   - serviceIds []string
func (_e *ProfileServicer_Expecter) DisableServices(ctx interface{}, accountId interface{}, profileId interface{}, serviceIds interface{}) *ProfileServicer_DisableServices_Call {
	return &ProfileServicer_DisableServices_Call{Call: _e.mock.On("DisableServices", ctx, accountId, profileId, serviceIds)}
}

func (_c *ProfileServicer_DisableServices_Call) Run(run func(ctx context.Context, accountId string, profileId string, serviceIds []string)) *ProfileServicer_DisableServices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []string
		if args[3] != nil {
			arg3 = args[3].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ProfileServicer_DisableServices_Call) Return(err error) *ProfileServicer_DisableServices_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProfileServicer_DisableServices_Call) RunAndReturn(run func(ctx context.Context, accountId string, profileId string, serviceIds []string) error) *ProfileServicer_DisableServices_Call {
	_c.Call.Return(run)
	return _c
}

// DownloadProfileQueryLogs provides a mock function for the type ProfileServicer
func (_mock *ProfileServicer) DownloadProfileQueryLogs(ctx context.Context, accountId string, profileId string, page int, limit int) ([]model.QueryLog, error) {
	ret := _mock.Called(ctx, accountId, profileId, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for DownloadProfileQueryLogs")
	}

	var r0 []model.QueryLog
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int, int) ([]model.QueryLog, error)); ok {
		return returnFunc(ctx, accountId, profileId, page, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int, int) []model.QueryLog); ok {
		r0 = returnFunc(ctx, accountId, profileId, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.QueryLog)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int, int) error); ok {
		r1 = returnFunc(ctx, accountId, profileId, page, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProfileServicer_DownloadProfileQueryLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadProfileQueryLogs'
type ProfileServicer_DownloadProfileQueryLogs_Call struct {
	*mock.Call
}

// DownloadProfileQueryLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
//   - profileId string
//   - page int
//   - limit int
func (_e *ProfileServicer_Expecter) DownloadProfileQueryLogs(ctx interface{}, accountId interface{}, profileId interface{}, page interface{}, limit interface{}) *ProfileServicer_DownloadProfileQueryLogs_Call {
	return &ProfileServicer_DownloadProfileQueryLogs_Call{Call: _e.mock.On("DownloadProfileQueryLogs", ctx, accountId, profileId, page, limit)}
}

func (_c *ProfileServicer_DownloadProfileQueryLogs_Call) Run(run func(ctx context.Context, accountId string, profileId string, page int, limit int)) *ProfileServicer_DownloadProfileQueryLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *ProfileServicer_DownloadProfileQueryLogs_Call) Return(queryLogs []model.QueryLog, err error) *ProfileServicer_DownloadProfileQueryLogs_Call {
	_c.Call.Return(queryLogs, err)
	return _c
}

func (_c *ProfileServicer_DownloadProfileQueryLogs_Call) RunAndReturn(run func(ctx context.Context, accountId string, profileId string, page int, limit int) ([]model.QueryLog, error)) *ProfileServicer_DownloadProfileQueryLogs_Call {
	_c.Call.Return(run)
	return _c
}

// EnableBlocklists provides a mock function for the type ProfileServicer
func (_mock *ProfileServicer) EnableBlocklists(ctx context.Context, accountId string, profileId string, blocklistIds []string) error {
	ret := _mock.Called(ctx, accountId, profileId, blocklistIds)

	if len(ret) == 0 {
		panic("no return value specified for EnableBlocklists")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []string) error); ok {
		r0 = returnFunc(ctx, accountId, profileId, blocklistIds)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProfileServicer_EnableBlocklists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableBlocklists'
type ProfileServicer_EnableBlocklists_Call struct {
	*mock.Call
}

// EnableBlocklists is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
//   - profileId string
//   - blocklistIds []string
func (_e *ProfileServicer_Expecter) EnableBlocklists(ctx interface{}, accountId interface{}, profileId interface{}, blocklistIds interface{}) *ProfileServicer_EnableBlocklists_Call {
	return &ProfileServicer_EnableBlocklists_Call{Call: _e.mock.On("EnableBlocklists", ctx, accountId, profileId, blocklistIds)}
}

func (_c *ProfileServicer_EnableBlocklists_Call) Run(run func(ctx context.Context, accountId string, profileId string, blocklistIds []string)) *ProfileServicer_EnableBlocklists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []string
		if args[3] != nil {
			arg3 = args[3].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ProfileServicer_EnableBlocklists_Call) Return(err error) *ProfileServicer_EnableBlocklists_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProfileServicer_EnableBlocklists_Call) RunAndReturn(run func(ctx context.Context, accountId string, profileId string, blocklistIds []string) error) *ProfileServicer_EnableBlocklists_Call {
	_c.Call.Return(run)
	return _c
}

// EnableServices provides a mock function for the type ProfileServicer
func (_mock *ProfileServicer) EnableServices(ctx context.Context, accountId string, profileId string, serviceIds []string) error {
	ret := _mock.Called(ctx, accountId, profileId, serviceIds)

	if len(ret) == 0 {
		panic("no return value specified for EnableServices")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []string) error); ok {
		r0 = returnFunc(ctx, accountId, profileId, serviceIds)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProfileServicer_EnableServices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableServices'
type ProfileServicer_EnableServices_Call struct {
	*mock.Call
}

// EnableServices is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
//   - profileId string
//   - serviceIds []string
func (_e *ProfileServicer_Expecter) EnableServices(ctx interface{}, accountId interface{}, profileId interface{}, serviceIds interface{}) *ProfileServicer_EnableServices_Call {
	return &ProfileServicer_EnableServices_Call{Call: _e.mock.On("EnableServices", ctx, accountId, profileId, serviceIds)}
}

func (_c *ProfileServicer_EnableServices_Call) Run(run func(ctx context.Context, accountId string, profileId string, serviceIds []string)) *ProfileServicer_EnableServices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []string
		if args[3] != nil {
			arg3 = args[3].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ProfileServicer_EnableServices_Call) Return(err error) *ProfileServicer_EnableServices_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProfileServicer_EnableServices_Call) RunAndReturn(run func(ctx context.Context, accountId string, profileId string, serviceIds []string) error) *ProfileServicer_EnableServices_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfile provides a mock function for the type ProfileServicer
func (_mock *ProfileServicer) GetProfile(ctx context.Context, accountId string, profileId string) (*model.Profile, error) {
	ret := _mock.Called(ctx, accountId, profileId)

	if len(ret) == 0 {
		panic("no return value specified for GetProfile")
	}

	var r0 *model.Profile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*model.Profile, error)); ok {
		return returnFunc(ctx, accountId, profileId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *model.Profile); ok {
		r0 = returnFunc(ctx, accountId, profileId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Profile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, accountId, profileId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProfileServicer_GetProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfile'
type ProfileServicer_GetProfile_Call struct {
	*mock.Call
}

// GetProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
//   - profileId string
func (_e *ProfileServicer_Expecter) GetProfile(ctx interface{}, accountId interface{}, profileId interface{}) *ProfileServicer_GetProfile_Call {
	return &ProfileServicer_GetProfile_Call{Call: _e.mock.On("GetProfile", ctx, accountId, profileId)}
}

func (_c *ProfileServicer_GetProfile_Call) Run(run func(ctx context.Context, accountId string, profileId string)) *ProfileServicer_GetProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ProfileServicer_GetProfile_Call) Return(profile1 *model.Profile, err error) *ProfileServicer_GetProfile_Call {
	_c.Call.Return(profile1, err)
	return _c
}

func (_c *ProfileServicer_GetProfile_Call) RunAndReturn(run func(ctx context.Context, accountId string, profileId string) (*model.Profile, error)) *ProfileServicer_GetProfile_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfileQueryLogs provides a mock function for the type ProfileServicer
func (_mock *ProfileServicer) GetProfileQueryLogs(ctx context.Context, accountId string, profileId string, status string, timespan string, deviceId string, search string, sortBy string, page int, limit int) ([]model.QueryLog, error) {
	ret := _mock.Called(ctx, accountId, profileId, status, timespan, deviceId, search, sortBy, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetProfileQueryLogs")
	}

	var r0 []model.QueryLog
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, string, string, int, int) ([]model.QueryLog, error)); ok {
		return returnFunc(ctx, accountId, profileId, status, timespan, deviceId, search, sortBy, page, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, string, string, int, int) []model.QueryLog); ok {
		r0 = returnFunc(ctx, accountId, profileId, status, timespan, deviceId, search, sortBy, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.QueryLog)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string, string, string, string, int, int) error); ok {
		r1 = returnFunc(ctx, accountId, profileId, status, timespan, deviceId, search, sortBy, page, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProfileServicer_GetProfileQueryLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfileQueryLogs'
type ProfileServicer_GetProfileQueryLogs_Call struct {
	*mock.Call
}

// GetProfileQueryLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
//   - profileId string
//   - status string
//   - timespan string
//   - deviceId string
//   - search string
//   - sortBy string
//   - page int
//   - limit int
func (_e *ProfileServicer_Expecter) GetProfileQueryLogs(ctx interface{}, accountId interface{}, profileId interface{}, status interface{}, timespan interface{}, deviceId interface{}, search interface{}, sortBy interface{}, page interface{}, limit interface{}) *ProfileServicer_GetProfileQueryLogs_Call {
	return &ProfileServicer_GetProfileQueryLogs_Call{Call: _e.mock.On("GetProfileQueryLogs", ctx, accountId, profileId, status, timespan, deviceId, search, sortBy, page, limit)}
}

func (_c *ProfileServicer_GetProfileQueryLogs_Call) Run(run func(ctx context.Context, accountId string, profileId string, status string, timespan string, deviceId string, search string, sortBy string, page int, limit int)) *ProfileServicer_GetProfileQueryLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		var arg6 string
		if args[6] != nil {
			arg6 = args[6].(string)
		}
		var arg7 string
		if args[7] != nil {
			arg7 = args[7].(string)
		}
		var arg8 int
		if args[8] != nil {
			arg8 = args[8].(int)
		}
		var arg9 int
		if args[9] != nil {
			arg9 = args[9].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
			arg7,
			arg8,
			arg9,
		)
	})
	return _c
}

func (_c *ProfileServicer_GetProfileQueryLogs_Call) Return(queryLogs []model.QueryLog, err error) *ProfileServicer_GetProfileQueryLogs_Call {
	_c.Call.Return(queryLogs, err)
	return _c
}

func (_c *ProfileServicer_GetProfileQueryLogs_Call) RunAndReturn(run func(ctx context.Context, accountId string, profileId string, status string, timespan string, deviceId string, search string, sortBy string, page int, limit int) ([]model.QueryLog, error)) *ProfileServicer_GetProfileQueryLogs_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfiles provides a mock function for the type ProfileServicer
func (_mock *ProfileServicer) GetProfiles(ctx context.Context, accountId string) ([]model.Profile, error) {
	ret := _mock.Called(ctx, accountId)

	if len(ret) == 0 {
		panic("no return value specified for GetProfiles")
	}

	var r0 []model.Profile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]model.Profile, error)); ok {
		return returnFunc(ctx, accountId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []model.Profile); ok {
		r0 = returnFunc(ctx, accountId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Profile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accountId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProfileServicer_GetProfiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfiles'
type ProfileServicer_GetProfiles_Call struct {
	*mock.Call
}

// GetProfiles is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
func (_e *ProfileServicer_Expecter) GetProfiles(ctx interface{}, accountId interface{}) *ProfileServicer_GetProfiles_Call {
	return &ProfileServicer_GetProfiles_Call{Call: _e.mock.On("GetProfiles", ctx, accountId)}
}

func (_c *ProfileServicer_GetProfiles_Call) Run(run func(ctx context.Context, accountId string)) *ProfileServicer_GetProfiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProfileServicer_GetProfiles_Call) Return(profiles []model.Profile, err error) *ProfileServicer_GetProfiles_Call {
	_c.Call.Return(profiles, err)
	return _c
}

func (_c *ProfileServicer_GetProfiles_Call) RunAndReturn(run func(ctx context.Context, accountId string) ([]model.Profile, error)) *ProfileServicer_GetProfiles_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatistics provides a mock function for the type ProfileServicer
func (_mock *ProfileServicer) GetStatistics(ctx context.Context, accountId string, profileId string, timespan string) ([]model.StatisticsAggregated, error) {
	ret := _mock.Called(ctx, accountId, profileId, timespan)

	if len(ret) == 0 {
		panic("no return value specified for GetStatistics")
	}

	var r0 []model.StatisticsAggregated
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) ([]model.StatisticsAggregated, error)); ok {
		return returnFunc(ctx, accountId, profileId, timespan)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) []model.StatisticsAggregated); ok {
		r0 = returnFunc(ctx, accountId, profileId, timespan)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.StatisticsAggregated)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, accountId, profileId, timespan)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProfileServicer_GetStatistics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatistics'
type ProfileServicer_GetStatistics_Call struct {
	*mock.Call
}

// GetStatistics is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
//   - profileId string
//   - timespan string
func (_e *ProfileServicer_Expecter) GetStatistics(ctx interface{}, accountId interface{}, profileId interface{}, timespan interface{}) *ProfileServicer_GetStatistics_Call {
	return &ProfileServicer_GetStatistics_Call{Call: _e.mock.On("GetStatistics", ctx, accountId, profileId, timespan)}
}

func (_c *ProfileServicer_GetStatistics_Call) Run(run func(ctx context.Context, accountId string, profileId string, timespan string)) *ProfileServicer_GetStatistics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ProfileServicer_GetStatistics_Call) Return(statisticsAggregateds []model.StatisticsAggregated, err error) *ProfileServicer_GetStatistics_Call {
	_c.Call.Return(statisticsAggregateds, err)
	return _c
}

func (_c *ProfileServicer_GetStatistics_Call) RunAndReturn(run func(ctx context.Context, accountId string, profileId string, timespan string) ([]model.StatisticsAggregated, error)) *ProfileServicer_GetStatistics_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfile provides a mock function for the type ProfileServicer
func (_mock *ProfileServicer) UpdateProfile(ctx context.Context, accountId string, profileId string, updates []model.ProfileUpdate) (*model.Profile, error) {
	ret := _mock.Called(ctx, accountId, profileId, updates)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 *model.Profile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []model.ProfileUpdate) (*model.Profile, error)); ok {
		return returnFunc(ctx, accountId, profileId, updates)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []model.ProfileUpdate) *model.Profile); ok {
		r0 = returnFunc(ctx, accountId, profileId, updates)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Profile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, []model.ProfileUpdate) error); ok {
		r1 = returnFunc(ctx, accountId, profileId, updates)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProfileServicer_UpdateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfile'
type ProfileServicer_UpdateProfile_Call struct {
	*mock.Call
}

// UpdateProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
//   - profileId string
//   - updates []model.ProfileUpdate
func (_e *ProfileServicer_Expecter) UpdateProfile(ctx interface{}, accountId interface{}, profileId interface{}, updates interface{}) *ProfileServicer_UpdateProfile_Call {
	return &ProfileServicer_UpdateProfile_Call{Call: _e.mock.On("UpdateProfile", ctx, accountId, profileId, updates)}
}

func (_c *ProfileServicer_UpdateProfile_Call) Run(run func(ctx context.Context, accountId string, profileId string, updates []model.ProfileUpdate)) *ProfileServicer_UpdateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []model.ProfileUpdate
		if args[3] != nil {
			arg3 = args[3].([]model.ProfileUpdate)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ProfileServicer_UpdateProfile_Call) Return(profile1 *model.Profile, err error) *ProfileServicer_UpdateProfile_Call {
	_c.Call.Return(profile1, err)
	return _c
}

func (_c *ProfileServicer_UpdateProfile_Call) RunAndReturn(run func(ctx context.Context, accountId string, profileId string, updates []model.ProfileUpdate) (*model.Profile, error)) *ProfileServicer_UpdateProfile_Call {
	_c.Call.Return(run)
	return _c
}
