// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ivpn/dns/api/model"
	mock "github.com/stretchr/testify/mock"
)

// NewQueryLogsServicer creates a new instance of QueryLogsServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQueryLogsServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *QueryLogsServicer {
	mock := &QueryLogsServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// QueryLogsServicer is an autogenerated mock type for the QueryLogsServicer type
type QueryLogsServicer struct {
	mock.Mock
}

type QueryLogsServicer_Expecter struct {
	mock *mock.Mock
}

func (_m *QueryLogsServicer) EXPECT() *QueryLogsServicer_Expecter {
	return &QueryLogsServicer_Expecter{mock: &_m.Mock}
}

// DeleteProfileQueryLogs provides a mock function for the type QueryLogsServicer
func (_mock *QueryLogsServicer) DeleteProfileQueryLogs(ctx context.Context, profileId string) error {
	ret := _mock.Called(ctx, profileId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProfileQueryLogs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, profileId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// QueryLogsServicer_DeleteProfileQueryLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProfileQueryLogs'
type QueryLogsServicer_DeleteProfileQueryLogs_Call struct {
	*mock.Call
}

// DeleteProfileQueryLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
func (_e *QueryLogsServicer_Expecter) DeleteProfileQueryLogs(ctx interface{}, profileId interface{}) *QueryLogsServicer_DeleteProfileQueryLogs_Call {
	return &QueryLogsServicer_DeleteProfileQueryLogs_Call{Call: _e.mock.On("DeleteProfileQueryLogs", ctx, profileId)}
}

func (_c *QueryLogsServicer_DeleteProfileQueryLogs_Call) Run(run func(ctx context.Context, profileId string)) *QueryLogsServicer_DeleteProfileQueryLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *QueryLogsServicer_DeleteProfileQueryLogs_Call) Return(err error) *QueryLogsServicer_DeleteProfileQueryLogs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *QueryLogsServicer_DeleteProfileQueryLogs_Call) RunAndReturn(run func(ctx context.Context, profileId string) error) *QueryLogsServicer_DeleteProfileQueryLogs_Call {
	_c.Call.Return(run)
	return _c
}

// DownloadProfileQueryLogs provides a mock function for the type QueryLogsServicer
func (_mock *QueryLogsServicer) DownloadProfileQueryLogs(ctx context.Context, profileId string, retention model.Retention, page int, limit int) ([]model.QueryLog, error) {
	ret := _mock.Called(ctx, profileId, retention, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for DownloadProfileQueryLogs")
	}

	var r0 []model.QueryLog
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.Retention, int, int) ([]model.QueryLog, error)); ok {
		return returnFunc(ctx, profileId, retention, page, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.Retention, int, int) []model.QueryLog); ok {
		r0 = returnFunc(ctx, profileId, retention, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.QueryLog)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, model.Retention, int, int) error); ok {
		r1 = returnFunc(ctx, profileId, retention, page, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// QueryLogsServicer_DownloadProfileQueryLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadProfileQueryLogs'
type QueryLogsServicer_DownloadProfileQueryLogs_Call struct {
	*mock.Call
}

// DownloadProfileQueryLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
//   - retention model.Retention
//   - page int
//   - limit int
func (_e *QueryLogsServicer_Expecter) DownloadProfileQueryLogs(ctx interface{}, profileId interface{}, retention interface{}, page interface{}, limit interface{}) *QueryLogsServicer_DownloadProfileQueryLogs_Call {
	return &QueryLogsServicer_DownloadProfileQueryLogs_Call{Call: _e.mock.On("DownloadProfileQueryLogs", ctx, profileId, retention, page, limit)}
}

func (_c *QueryLogsServicer_DownloadProfileQueryLogs_Call) Run(run func(ctx context.Context, profileId string, retention model.Retention, page int, limit int)) *QueryLogsServicer_DownloadProfileQueryLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 model.Retention
		if args[2] != nil {
			arg2 = args[2].(model.Retention)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *QueryLogsServicer_DownloadProfileQueryLogs_Call) Return(queryLogs []model.QueryLog, err error) *QueryLogsServicer_DownloadProfileQueryLogs_Call {
	_c.Call.Return(queryLogs, err)
	return _c
}

func (_c *QueryLogsServicer_DownloadProfileQueryLogs_Call) RunAndReturn(run func(ctx context.Context, profileId string, retention model.Retention, page int, limit int) ([]model.QueryLog, error)) *QueryLogsServicer_DownloadProfileQueryLogs_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfileQueryLogs provides a mock function for the type QueryLogsServicer
func (_mock *QueryLogsServicer) GetProfileQueryLogs(ctx context.Context, profileId string, retention model.Retention, status string, timespan string, deviceId string, search string, page int, limit int) ([]model.QueryLog, error) {
	ret := _mock.Called(ctx, profileId, retention, status, timespan, deviceId, search, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetProfileQueryLogs")
	}

	var r0 []model.QueryLog
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.Retention, string, string, string, string, int, int) ([]model.QueryLog, error)); ok {
		return returnFunc(ctx, profileId, retention, status, timespan, deviceId, search, page, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.Retention, string, string, string, string, int, int) []model.QueryLog); ok {
		r0 = returnFunc(ctx, profileId, retention, status, timespan, deviceId, search, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.QueryLog)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, model.Retention, string, string, string, string, int, int) error); ok {
		r1 = returnFunc(ctx, profileId, retention, status, timespan, deviceId, search, page, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// QueryLogsServicer_GetProfileQueryLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfileQueryLogs'
type QueryLogsServicer_GetProfileQueryLogs_Call struct {
	*mock.Call
}

// GetProfileQueryLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
//   - retention model.Retention
//   - status string
//   - timespan string
//   - deviceId string
//   - search string
//   - page int
//   - limit int
func (_e *QueryLogsServicer_Expecter) GetProfileQueryLogs(ctx interface{}, profileId interface{}, retention interface{}, status interface{}, timespan interface{}, deviceId interface{}, search interface{}, page interface{}, limit interface{}) *QueryLogsServicer_GetProfileQueryLogs_Call {
	return &QueryLogsServicer_GetProfileQueryLogs_Call{Call: _e.mock.On("GetProfileQueryLogs", ctx, profileId, retention, status, timespan, deviceId, search, page, limit)}
}

func (_c *QueryLogsServicer_GetProfileQueryLogs_Call) Run(run func(ctx context.Context, profileId string, retention model.Retention, status string, timespan string, deviceId string, search string, page int, limit int)) *QueryLogsServicer_GetProfileQueryLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 model.Retention
		if args[2] != nil {
			arg2 = args[2].(model.Retention)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		var arg6 string
		if args[6] != nil {
			arg6 = args[6].(string)
		}
		var arg7 int
		if args[7] != nil {
			arg7 = args[7].(int)
		}
		var arg8 int
		if args[8] != nil {
			arg8 = args[8].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
			arg7,
			arg8,
		)
	})
	return _c
}

func (_c *QueryLogsServicer_GetProfileQueryLogs_Call) Return(queryLogs []model.QueryLog, err error) *QueryLogsServicer_GetProfileQueryLogs_Call {
	_c.Call.Return(queryLogs, err)
	return _c
}

func (_c *QueryLogsServicer_GetProfileQueryLogs_Call) RunAndReturn(run func(ctx context.Context, profileId string, retention model.Retention, status string, timespan string, deviceId string, search string, page int, limit int) ([]model.QueryLog, error)) *QueryLogsServicer_GetProfileQueryLogs_Call {
	_c.Call.Return(run)
	return _c
}
