// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ivpn/dns/api/model"
	mock "github.com/stretchr/testify/mock"
)

// NewQueryLogsRepository creates a new instance of QueryLogsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQueryLogsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *QueryLogsRepository {
	mock := &QueryLogsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// QueryLogsRepository is an autogenerated mock type for the QueryLogsRepository type
type QueryLogsRepository struct {
	mock.Mock
}

type QueryLogsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *QueryLogsRepository) EXPECT() *QueryLogsRepository_Expecter {
	return &QueryLogsRepository_Expecter{mock: &_m.Mock}
}

// DeleteQueryLogs provides a mock function for the type QueryLogsRepository
func (_mock *QueryLogsRepository) DeleteQueryLogs(ctx context.Context, profileId string) error {
	ret := _mock.Called(ctx, profileId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteQueryLogs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, profileId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// QueryLogsRepository_DeleteQueryLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteQueryLogs'
type QueryLogsRepository_DeleteQueryLogs_Call struct {
	*mock.Call
}

// DeleteQueryLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
func (_e *QueryLogsRepository_Expecter) DeleteQueryLogs(ctx interface{}, profileId interface{}) *QueryLogsRepository_DeleteQueryLogs_Call {
	return &QueryLogsRepository_DeleteQueryLogs_Call{Call: _e.mock.On("DeleteQueryLogs", ctx, profileId)}
}

func (_c *QueryLogsRepository_DeleteQueryLogs_Call) Run(run func(ctx context.Context, profileId string)) *QueryLogsRepository_DeleteQueryLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *QueryLogsRepository_DeleteQueryLogs_Call) Return(err error) *QueryLogsRepository_DeleteQueryLogs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *QueryLogsRepository_DeleteQueryLogs_Call) RunAndReturn(run func(ctx context.Context, profileId string) error) *QueryLogsRepository_DeleteQueryLogs_Call {
	_c.Call.Return(run)
	return _c
}

// GetQueryLogs provides a mock function for the type QueryLogsRepository
func (_mock *QueryLogsRepository) GetQueryLogs(ctx context.Context, profileId string, retention model.Retention, status string, timespan int, deviceId string, search string, page int, limit int) ([]model.QueryLog, error) {
	ret := _mock.Called(ctx, profileId, retention, status, timespan, deviceId, search, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetQueryLogs")
	}

	var r0 []model.QueryLog
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.Retention, string, int, string, string, int, int) ([]model.QueryLog, error)); ok {
		return returnFunc(ctx, profileId, retention, status, timespan, deviceId, search, page, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.Retention, string, int, string, string, int, int) []model.QueryLog); ok {
		r0 = returnFunc(ctx, profileId, retention, status, timespan, deviceId, search, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.QueryLog)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, model.Retention, string, int, string, string, int, int) error); ok {
		r1 = returnFunc(ctx, profileId, retention, status, timespan, deviceId, search, page, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// QueryLogsRepository_GetQueryLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQueryLogs'
type QueryLogsRepository_GetQueryLogs_Call struct {
	*mock.Call
}

// GetQueryLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
//   - retention model.Retention
//   - status string
//   - timespan int
//   - deviceId string
//   - search string
//   - page int
//   - limit int
func (_e *QueryLogsRepository_Expecter) GetQueryLogs(ctx interface{}, profileId interface{}, retention interface{}, status interface{}, timespan interface{}, deviceId interface{}, search interface{}, page interface{}, limit interface{}) *QueryLogsRepository_GetQueryLogs_Call {
	return &QueryLogsRepository_GetQueryLogs_Call{Call: _e.mock.On("GetQueryLogs", ctx, profileId, retention, status, timespan, deviceId, search, page, limit)}
}

func (_c *QueryLogsRepository_GetQueryLogs_Call) Run(run func(ctx context.Context, profileId string, retention model.Retention, status string, timespan int, deviceId string, search string, page int, limit int)) *QueryLogsRepository_GetQueryLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 model.Retention
		if args[2] != nil {
			arg2 = args[2].(model.Retention)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		var arg6 string
		if args[6] != nil {
			arg6 = args[6].(string)
		}
		var arg7 int
		if args[7] != nil {
			arg7 = args[7].(int)
		}
		var arg8 int
		if args[8] != nil {
			arg8 = args[8].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
			arg7,
			arg8,
		)
	})
	return _c
}

func (_c *QueryLogsRepository_GetQueryLogs_Call) Return(queryLogs []model.QueryLog, err error) *QueryLogsRepository_GetQueryLogs_Call {
	_c.Call.Return(queryLogs, err)
	return _c
}

func (_c *QueryLogsRepository_GetQueryLogs_Call) RunAndReturn(run func(ctx context.Context, profileId string, retention model.Retention, status string, timespan int, deviceId string, search string, page int, limit int) ([]model.QueryLog, error)) *QueryLogsRepository_GetQueryLogs_Call {
	_c.Call.Return(run)
	return _c
}
