// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/go-webauthn/webauthn/webauthn"
	"github.com/ivpn/dns/api/model"
	mock "github.com/stretchr/testify/mock"
)

// NewSessionRepository creates a new instance of SessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionRepository {
	mock := &SessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SessionRepository is an autogenerated mock type for the SessionRepository type
type SessionRepository struct {
	mock.Mock
}

type SessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionRepository) EXPECT() *SessionRepository_Expecter {
	return &SessionRepository_Expecter{mock: &_m.Mock}
}

// CountSessionsByAccountID provides a mock function for the type SessionRepository
func (_mock *SessionRepository) CountSessionsByAccountID(ctx context.Context, accID string) (int64, error) {
	ret := _mock.Called(ctx, accID)

	if len(ret) == 0 {
		panic("no return value specified for CountSessionsByAccountID")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return returnFunc(ctx, accID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, accID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SessionRepository_CountSessionsByAccountID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountSessionsByAccountID'
type SessionRepository_CountSessionsByAccountID_Call struct {
	*mock.Call
}

// CountSessionsByAccountID is a helper method to define mock.On call
//   - ctx context.Context
//   - accID string
func (_e *SessionRepository_Expecter) CountSessionsByAccountID(ctx interface{}, accID interface{}) *SessionRepository_CountSessionsByAccountID_Call {
	return &SessionRepository_CountSessionsByAccountID_Call{Call: _e.mock.On("CountSessionsByAccountID", ctx, accID)}
}

func (_c *SessionRepository_CountSessionsByAccountID_Call) Run(run func(ctx context.Context, accID string)) *SessionRepository_CountSessionsByAccountID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRepository_CountSessionsByAccountID_Call) Return(n int64, err error) *SessionRepository_CountSessionsByAccountID_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *SessionRepository_CountSessionsByAccountID_Call) RunAndReturn(run func(ctx context.Context, accID string) (int64, error)) *SessionRepository_CountSessionsByAccountID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSession provides a mock function for the type SessionRepository
func (_mock *SessionRepository) DeleteSession(ctx context.Context, token string) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionRepository_DeleteSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSession'
type SessionRepository_DeleteSession_Call struct {
	*mock.Call
}

// DeleteSession is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *SessionRepository_Expecter) DeleteSession(ctx interface{}, token interface{}) *SessionRepository_DeleteSession_Call {
	return &SessionRepository_DeleteSession_Call{Call: _e.mock.On("DeleteSession", ctx, token)}
}

func (_c *SessionRepository_DeleteSession_Call) Run(run func(ctx context.Context, token string)) *SessionRepository_DeleteSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRepository_DeleteSession_Call) Return(err error) *SessionRepository_DeleteSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionRepository_DeleteSession_Call) RunAndReturn(run func(ctx context.Context, token string) error) *SessionRepository_DeleteSession_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSessionsByAccountID provides a mock function for the type SessionRepository
func (_mock *SessionRepository) DeleteSessionsByAccountID(ctx context.Context, accID string) error {
	ret := _mock.Called(ctx, accID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSessionsByAccountID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, accID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionRepository_DeleteSessionsByAccountID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSessionsByAccountID'
type SessionRepository_DeleteSessionsByAccountID_Call struct {
	*mock.Call
}

// DeleteSessionsByAccountID is a helper method to define mock.On call
//   - ctx context.Context
//   - accID string
func (_e *SessionRepository_Expecter) DeleteSessionsByAccountID(ctx interface{}, accID interface{}) *SessionRepository_DeleteSessionsByAccountID_Call {
	return &SessionRepository_DeleteSessionsByAccountID_Call{Call: _e.mock.On("DeleteSessionsByAccountID", ctx, accID)}
}

func (_c *SessionRepository_DeleteSessionsByAccountID_Call) Run(run func(ctx context.Context, accID string)) *SessionRepository_DeleteSessionsByAccountID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRepository_DeleteSessionsByAccountID_Call) Return(err error) *SessionRepository_DeleteSessionsByAccountID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionRepository_DeleteSessionsByAccountID_Call) RunAndReturn(run func(ctx context.Context, accID string) error) *SessionRepository_DeleteSessionsByAccountID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSessionsByAccountIDExceptCurrent provides a mock function for the type SessionRepository
func (_mock *SessionRepository) DeleteSessionsByAccountIDExceptCurrent(ctx context.Context, accID string, currentToken string) error {
	ret := _mock.Called(ctx, accID, currentToken)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSessionsByAccountIDExceptCurrent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, accID, currentToken)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionRepository_DeleteSessionsByAccountIDExceptCurrent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSessionsByAccountIDExceptCurrent'
type SessionRepository_DeleteSessionsByAccountIDExceptCurrent_Call struct {
	*mock.Call
}

// DeleteSessionsByAccountIDExceptCurrent is a helper method to define mock.On call
//   - ctx context.Context
//   - accID string
//   - currentToken string
func (_e *SessionRepository_Expecter) DeleteSessionsByAccountIDExceptCurrent(ctx interface{}, accID interface{}, currentToken interface{}) *SessionRepository_DeleteSessionsByAccountIDExceptCurrent_Call {
	return &SessionRepository_DeleteSessionsByAccountIDExceptCurrent_Call{Call: _e.mock.On("DeleteSessionsByAccountIDExceptCurrent", ctx, accID, currentToken)}
}

func (_c *SessionRepository_DeleteSessionsByAccountIDExceptCurrent_Call) Run(run func(ctx context.Context, accID string, currentToken string)) *SessionRepository_DeleteSessionsByAccountIDExceptCurrent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SessionRepository_DeleteSessionsByAccountIDExceptCurrent_Call) Return(err error) *SessionRepository_DeleteSessionsByAccountIDExceptCurrent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionRepository_DeleteSessionsByAccountIDExceptCurrent_Call) RunAndReturn(run func(ctx context.Context, accID string, currentToken string) error) *SessionRepository_DeleteSessionsByAccountIDExceptCurrent_Call {
	_c.Call.Return(run)
	return _c
}

// GetSession provides a mock function for the type SessionRepository
func (_mock *SessionRepository) GetSession(ctx context.Context, token string) (model.Session, bool, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 model.Session
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.Session, bool, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.Session); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Get(0).(model.Session)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, token)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// SessionRepository_GetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSession'
type SessionRepository_GetSession_Call struct {
	*mock.Call
}

// GetSession is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *SessionRepository_Expecter) GetSession(ctx interface{}, token interface{}) *SessionRepository_GetSession_Call {
	return &SessionRepository_GetSession_Call{Call: _e.mock.On("GetSession", ctx, token)}
}

func (_c *SessionRepository_GetSession_Call) Run(run func(ctx context.Context, token string)) *SessionRepository_GetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRepository_GetSession_Call) Return(session model.Session, b bool, err error) *SessionRepository_GetSession_Call {
	_c.Call.Return(session, b, err)
	return _c
}

func (_c *SessionRepository_GetSession_Call) RunAndReturn(run func(ctx context.Context, token string) (model.Session, bool, error)) *SessionRepository_GetSession_Call {
	_c.Call.Return(run)
	return _c
}

// SaveSession provides a mock function for the type SessionRepository
func (_mock *SessionRepository) SaveSession(ctx context.Context, sessionData webauthn.SessionData, token string, userID string, purpose string) error {
	ret := _mock.Called(ctx, sessionData, token, userID, purpose)

	if len(ret) == 0 {
		panic("no return value specified for SaveSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, webauthn.SessionData, string, string, string) error); ok {
		r0 = returnFunc(ctx, sessionData, token, userID, purpose)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionRepository_SaveSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveSession'
type SessionRepository_SaveSession_Call struct {
	*mock.Call
}

// SaveSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionData webauthn.SessionData
//   - token string
//   - userID string
//   - purpose string
func (_e *SessionRepository_Expecter) SaveSession(ctx interface{}, sessionData interface{}, token interface{}, userID interface{}, purpose interface{}) *SessionRepository_SaveSession_Call {
	return &SessionRepository_SaveSession_Call{Call: _e.mock.On("SaveSession", ctx, sessionData, token, userID, purpose)}
}

func (_c *SessionRepository_SaveSession_Call) Run(run func(ctx context.Context, sessionData webauthn.SessionData, token string, userID string, purpose string)) *SessionRepository_SaveSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 webauthn.SessionData
		if args[1] != nil {
			arg1 = args[1].(webauthn.SessionData)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *SessionRepository_SaveSession_Call) Return(err error) *SessionRepository_SaveSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionRepository_SaveSession_Call) RunAndReturn(run func(ctx context.Context, sessionData webauthn.SessionData, token string, userID string, purpose string) error) *SessionRepository_SaveSession_Call {
	_c.Call.Return(run)
	return _c
}
