// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ivpn/dns/api/model"
	mock "github.com/stretchr/testify/mock"
)

// NewStatisticsRepository creates a new instance of StatisticsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStatisticsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *StatisticsRepository {
	mock := &StatisticsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// StatisticsRepository is an autogenerated mock type for the StatisticsRepository type
type StatisticsRepository struct {
	mock.Mock
}

type StatisticsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *StatisticsRepository) EXPECT() *StatisticsRepository_Expecter {
	return &StatisticsRepository_Expecter{mock: &_m.Mock}
}

// GetProfileStatistics provides a mock function for the type StatisticsRepository
func (_mock *StatisticsRepository) GetProfileStatistics(ctx context.Context, profileId string, timespan int) ([]model.StatisticsAggregated, error) {
	ret := _mock.Called(ctx, profileId, timespan)

	if len(ret) == 0 {
		panic("no return value specified for GetProfileStatistics")
	}

	var r0 []model.StatisticsAggregated
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) ([]model.StatisticsAggregated, error)); ok {
		return returnFunc(ctx, profileId, timespan)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) []model.StatisticsAggregated); ok {
		r0 = returnFunc(ctx, profileId, timespan)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.StatisticsAggregated)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = returnFunc(ctx, profileId, timespan)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StatisticsRepository_GetProfileStatistics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfileStatistics'
type StatisticsRepository_GetProfileStatistics_Call struct {
	*mock.Call
}

// GetProfileStatistics is a helper method to define mock.On call
//   - ctx context.Context
//   - profileId string
//   - timespan int
func (_e *StatisticsRepository_Expecter) GetProfileStatistics(ctx interface{}, profileId interface{}, timespan interface{}) *StatisticsRepository_GetProfileStatistics_Call {
	return &StatisticsRepository_GetProfileStatistics_Call{Call: _e.mock.On("GetProfileStatistics", ctx, profileId, timespan)}
}

func (_c *StatisticsRepository_GetProfileStatistics_Call) Run(run func(ctx context.Context, profileId string, timespan int)) *StatisticsRepository_GetProfileStatistics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *StatisticsRepository_GetProfileStatistics_Call) Return(statisticsAggregateds []model.StatisticsAggregated, err error) *StatisticsRepository_GetProfileStatistics_Call {
	_c.Call.Return(statisticsAggregateds, err)
	return _c
}

func (_c *StatisticsRepository_GetProfileStatistics_Call) RunAndReturn(run func(ctx context.Context, profileId string, timespan int) ([]model.StatisticsAggregated, error)) *StatisticsRepository_GetProfileStatistics_Call {
	_c.Call.Return(run)
	return _c
}
