// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ivpn/dns/api/model"
	mock "github.com/stretchr/testify/mock"
)

// NewSubscriptionRepository creates a new instance of SubscriptionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSubscriptionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SubscriptionRepository {
	mock := &SubscriptionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SubscriptionRepository is an autogenerated mock type for the SubscriptionRepository type
type SubscriptionRepository struct {
	mock.Mock
}

type SubscriptionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *SubscriptionRepository) EXPECT() *SubscriptionRepository_Expecter {
	return &SubscriptionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type SubscriptionRepository
func (_mock *SubscriptionRepository) Create(ctx context.Context, subscription model.Subscription) error {
	ret := _mock.Called(ctx, subscription)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Subscription) error); ok {
		r0 = returnFunc(ctx, subscription)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SubscriptionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type SubscriptionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - subscription model.Subscription
func (_e *SubscriptionRepository_Expecter) Create(ctx interface{}, subscription interface{}) *SubscriptionRepository_Create_Call {
	return &SubscriptionRepository_Create_Call{Call: _e.mock.On("Create", ctx, subscription)}
}

func (_c *SubscriptionRepository_Create_Call) Run(run func(ctx context.Context, subscription model.Subscription)) *SubscriptionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Subscription
		if args[1] != nil {
			arg1 = args[1].(model.Subscription)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SubscriptionRepository_Create_Call) Return(err error) *SubscriptionRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SubscriptionRepository_Create_Call) RunAndReturn(run func(ctx context.Context, subscription model.Subscription) error) *SubscriptionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubscriptionByAccountId provides a mock function for the type SubscriptionRepository
func (_mock *SubscriptionRepository) GetSubscriptionByAccountId(ctx context.Context, accountId string) (*model.Subscription, error) {
	ret := _mock.Called(ctx, accountId)

	if len(ret) == 0 {
		panic("no return value specified for GetSubscriptionByAccountId")
	}

	var r0 *model.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Subscription, error)); ok {
		return returnFunc(ctx, accountId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Subscription); ok {
		r0 = returnFunc(ctx, accountId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accountId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SubscriptionRepository_GetSubscriptionByAccountId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubscriptionByAccountId'
type SubscriptionRepository_GetSubscriptionByAccountId_Call struct {
	*mock.Call
}

// GetSubscriptionByAccountId is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
func (_e *SubscriptionRepository_Expecter) GetSubscriptionByAccountId(ctx interface{}, accountId interface{}) *SubscriptionRepository_GetSubscriptionByAccountId_Call {
	return &SubscriptionRepository_GetSubscriptionByAccountId_Call{Call: _e.mock.On("GetSubscriptionByAccountId", ctx, accountId)}
}

func (_c *SubscriptionRepository_GetSubscriptionByAccountId_Call) Run(run func(ctx context.Context, accountId string)) *SubscriptionRepository_GetSubscriptionByAccountId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SubscriptionRepository_GetSubscriptionByAccountId_Call) Return(subscription *model.Subscription, err error) *SubscriptionRepository_GetSubscriptionByAccountId_Call {
	_c.Call.Return(subscription, err)
	return _c
}

func (_c *SubscriptionRepository_GetSubscriptionByAccountId_Call) RunAndReturn(run func(ctx context.Context, accountId string) (*model.Subscription, error)) *SubscriptionRepository_GetSubscriptionByAccountId_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubscriptionById provides a mock function for the type SubscriptionRepository
func (_mock *SubscriptionRepository) GetSubscriptionById(ctx context.Context, subscriptionId string) (*model.Subscription, error) {
	ret := _mock.Called(ctx, subscriptionId)

	if len(ret) == 0 {
		panic("no return value specified for GetSubscriptionById")
	}

	var r0 *model.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Subscription, error)); ok {
		return returnFunc(ctx, subscriptionId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Subscription); ok {
		r0 = returnFunc(ctx, subscriptionId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, subscriptionId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SubscriptionRepository_GetSubscriptionById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubscriptionById'
type SubscriptionRepository_GetSubscriptionById_Call struct {
	*mock.Call
}

// GetSubscriptionById is a helper method to define mock.On call
//   - ctx context.Context
//   - subscriptionId string
func (_e *SubscriptionRepository_Expecter) GetSubscriptionById(ctx interface{}, subscriptionId interface{}) *SubscriptionRepository_GetSubscriptionById_Call {
	return &SubscriptionRepository_GetSubscriptionById_Call{Call: _e.mock.On("GetSubscriptionById", ctx, subscriptionId)}
}

func (_c *SubscriptionRepository_GetSubscriptionById_Call) Run(run func(ctx context.Context, subscriptionId string)) *SubscriptionRepository_GetSubscriptionById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SubscriptionRepository_GetSubscriptionById_Call) Return(subscription *model.Subscription, err error) *SubscriptionRepository_GetSubscriptionById_Call {
	_c.Call.Return(subscription, err)
	return _c
}

func (_c *SubscriptionRepository_GetSubscriptionById_Call) RunAndReturn(run func(ctx context.Context, subscriptionId string) (*model.Subscription, error)) *SubscriptionRepository_GetSubscriptionById_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type SubscriptionRepository
func (_mock *SubscriptionRepository) Upsert(ctx context.Context, subscription model.Subscription) error {
	ret := _mock.Called(ctx, subscription)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Subscription) error); ok {
		r0 = returnFunc(ctx, subscription)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SubscriptionRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type SubscriptionRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - subscription model.Subscription
func (_e *SubscriptionRepository_Expecter) Upsert(ctx interface{}, subscription interface{}) *SubscriptionRepository_Upsert_Call {
	return &SubscriptionRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, subscription)}
}

func (_c *SubscriptionRepository_Upsert_Call) Run(run func(ctx context.Context, subscription model.Subscription)) *SubscriptionRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Subscription
		if args[1] != nil {
			arg1 = args[1].(model.Subscription)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SubscriptionRepository_Upsert_Call) Return(err error) *SubscriptionRepository_Upsert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SubscriptionRepository_Upsert_Call) RunAndReturn(run func(ctx context.Context, subscription model.Subscription) error) *SubscriptionRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}
