// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ivpn/dns/api/model"
	mock "github.com/stretchr/testify/mock"
)

// NewSubscriptionServicer creates a new instance of SubscriptionServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSubscriptionServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *SubscriptionServicer {
	mock := &SubscriptionServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SubscriptionServicer is an autogenerated mock type for the SubscriptionServicer type
type SubscriptionServicer struct {
	mock.Mock
}

type SubscriptionServicer_Expecter struct {
	mock *mock.Mock
}

func (_m *SubscriptionServicer) EXPECT() *SubscriptionServicer_Expecter {
	return &SubscriptionServicer_Expecter{mock: &_m.Mock}
}

// AddSubscription provides a mock function for the type SubscriptionServicer
func (_mock *SubscriptionServicer) AddSubscription(ctx context.Context, subscriptionId string, activeUntil string) error {
	ret := _mock.Called(ctx, subscriptionId, activeUntil)

	if len(ret) == 0 {
		panic("no return value specified for AddSubscription")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, subscriptionId, activeUntil)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SubscriptionServicer_AddSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddSubscription'
type SubscriptionServicer_AddSubscription_Call struct {
	*mock.Call
}

// AddSubscription is a helper method to define mock.On call
//   - ctx context.Context
//   - subscriptionId string
//   - activeUntil string
func (_e *SubscriptionServicer_Expecter) AddSubscription(ctx interface{}, subscriptionId interface{}, activeUntil interface{}) *SubscriptionServicer_AddSubscription_Call {
	return &SubscriptionServicer_AddSubscription_Call{Call: _e.mock.On("AddSubscription", ctx, subscriptionId, activeUntil)}
}

func (_c *SubscriptionServicer_AddSubscription_Call) Run(run func(ctx context.Context, subscriptionId string, activeUntil string)) *SubscriptionServicer_AddSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SubscriptionServicer_AddSubscription_Call) Return(err error) *SubscriptionServicer_AddSubscription_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SubscriptionServicer_AddSubscription_Call) RunAndReturn(run func(ctx context.Context, subscriptionId string, activeUntil string) error) *SubscriptionServicer_AddSubscription_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSubscription provides a mock function for the type SubscriptionServicer
func (_mock *SubscriptionServicer) CreateSubscription(ctx context.Context, accountId string, subscriptionId string, activeUntil string) error {
	ret := _mock.Called(ctx, accountId, subscriptionId, activeUntil)

	if len(ret) == 0 {
		panic("no return value specified for CreateSubscription")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, accountId, subscriptionId, activeUntil)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SubscriptionServicer_CreateSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSubscription'
type SubscriptionServicer_CreateSubscription_Call struct {
	*mock.Call
}

// CreateSubscription is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
//   - subscriptionId string
//   - activeUntil string
func (_e *SubscriptionServicer_Expecter) CreateSubscription(ctx interface{}, accountId interface{}, subscriptionId interface{}, activeUntil interface{}) *SubscriptionServicer_CreateSubscription_Call {
	return &SubscriptionServicer_CreateSubscription_Call{Call: _e.mock.On("CreateSubscription", ctx, accountId, subscriptionId, activeUntil)}
}

func (_c *SubscriptionServicer_CreateSubscription_Call) Run(run func(ctx context.Context, accountId string, subscriptionId string, activeUntil string)) *SubscriptionServicer_CreateSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *SubscriptionServicer_CreateSubscription_Call) Return(err error) *SubscriptionServicer_CreateSubscription_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SubscriptionServicer_CreateSubscription_Call) RunAndReturn(run func(ctx context.Context, accountId string, subscriptionId string, activeUntil string) error) *SubscriptionServicer_CreateSubscription_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubscription provides a mock function for the type SubscriptionServicer
func (_mock *SubscriptionServicer) GetSubscription(ctx context.Context, accountId string) (*model.Subscription, error) {
	ret := _mock.Called(ctx, accountId)

	if len(ret) == 0 {
		panic("no return value specified for GetSubscription")
	}

	var r0 *model.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Subscription, error)); ok {
		return returnFunc(ctx, accountId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Subscription); ok {
		r0 = returnFunc(ctx, accountId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accountId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SubscriptionServicer_GetSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubscription'
type SubscriptionServicer_GetSubscription_Call struct {
	*mock.Call
}

// GetSubscription is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
func (_e *SubscriptionServicer_Expecter) GetSubscription(ctx interface{}, accountId interface{}) *SubscriptionServicer_GetSubscription_Call {
	return &SubscriptionServicer_GetSubscription_Call{Call: _e.mock.On("GetSubscription", ctx, accountId)}
}

func (_c *SubscriptionServicer_GetSubscription_Call) Run(run func(ctx context.Context, accountId string)) *SubscriptionServicer_GetSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SubscriptionServicer_GetSubscription_Call) Return(subscription *model.Subscription, err error) *SubscriptionServicer_GetSubscription_Call {
	_c.Call.Return(subscription, err)
	return _c
}

func (_c *SubscriptionServicer_GetSubscription_Call) RunAndReturn(run func(ctx context.Context, accountId string) (*model.Subscription, error)) *SubscriptionServicer_GetSubscription_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSubscription provides a mock function for the type SubscriptionServicer
func (_mock *SubscriptionServicer) UpdateSubscription(ctx context.Context, accountId string, updates []model.SubscriptionUpdate) (*model.Subscription, error) {
	ret := _mock.Called(ctx, accountId, updates)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSubscription")
	}

	var r0 *model.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []model.SubscriptionUpdate) (*model.Subscription, error)); ok {
		return returnFunc(ctx, accountId, updates)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []model.SubscriptionUpdate) *model.Subscription); ok {
		r0 = returnFunc(ctx, accountId, updates)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []model.SubscriptionUpdate) error); ok {
		r1 = returnFunc(ctx, accountId, updates)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SubscriptionServicer_UpdateSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSubscription'
type SubscriptionServicer_UpdateSubscription_Call struct {
	*mock.Call
}

// UpdateSubscription is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
//   - updates []model.SubscriptionUpdate
func (_e *SubscriptionServicer_Expecter) UpdateSubscription(ctx interface{}, accountId interface{}, updates interface{}) *SubscriptionServicer_UpdateSubscription_Call {
	return &SubscriptionServicer_UpdateSubscription_Call{Call: _e.mock.On("UpdateSubscription", ctx, accountId, updates)}
}

func (_c *SubscriptionServicer_UpdateSubscription_Call) Run(run func(ctx context.Context, accountId string, updates []model.SubscriptionUpdate)) *SubscriptionServicer_UpdateSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []model.SubscriptionUpdate
		if args[2] != nil {
			arg2 = args[2].([]model.SubscriptionUpdate)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SubscriptionServicer_UpdateSubscription_Call) Return(subscription *model.Subscription, err error) *SubscriptionServicer_UpdateSubscription_Call {
	_c.Call.Return(subscription, err)
	return _c
}

func (_c *SubscriptionServicer_UpdateSubscription_Call) RunAndReturn(run func(ctx context.Context, accountId string, updates []model.SubscriptionUpdate) (*model.Subscription, error)) *SubscriptionServicer_UpdateSubscription_Call {
	_c.Call.Return(run)
	return _c
}
