// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/go-webauthn/webauthn/webauthn"
	"github.com/ivpn/dns/api/model"
	mock "github.com/stretchr/testify/mock"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

// NewWebAuthnCredentialRepository creates a new instance of WebAuthnCredentialRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWebAuthnCredentialRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *WebAuthnCredentialRepository {
	mock := &WebAuthnCredentialRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WebAuthnCredentialRepository is an autogenerated mock type for the WebAuthnCredentialRepository type
type WebAuthnCredentialRepository struct {
	mock.Mock
}

type WebAuthnCredentialRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *WebAuthnCredentialRepository) EXPECT() *WebAuthnCredentialRepository_Expecter {
	return &WebAuthnCredentialRepository_Expecter{mock: &_m.Mock}
}

// DeleteCredential provides a mock function for the type WebAuthnCredentialRepository
func (_mock *WebAuthnCredentialRepository) DeleteCredential(ctx context.Context, credentialID []byte, accountID primitive.ObjectID) error {
	ret := _mock.Called(ctx, credentialID, accountID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCredential")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, primitive.ObjectID) error); ok {
		r0 = returnFunc(ctx, credentialID, accountID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WebAuthnCredentialRepository_DeleteCredential_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCredential'
type WebAuthnCredentialRepository_DeleteCredential_Call struct {
	*mock.Call
}

// DeleteCredential is a helper method to define mock.On call
//   - ctx context.Context
//   - credentialID []byte
//   - accountID primitive.ObjectID
func (_e *WebAuthnCredentialRepository_Expecter) DeleteCredential(ctx interface{}, credentialID interface{}, accountID interface{}) *WebAuthnCredentialRepository_DeleteCredential_Call {
	return &WebAuthnCredentialRepository_DeleteCredential_Call{Call: _e.mock.On("DeleteCredential", ctx, credentialID, accountID)}
}

func (_c *WebAuthnCredentialRepository_DeleteCredential_Call) Run(run func(ctx context.Context, credentialID []byte, accountID primitive.ObjectID)) *WebAuthnCredentialRepository_DeleteCredential_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 primitive.ObjectID
		if args[2] != nil {
			arg2 = args[2].(primitive.ObjectID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *WebAuthnCredentialRepository_DeleteCredential_Call) Return(err error) *WebAuthnCredentialRepository_DeleteCredential_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WebAuthnCredentialRepository_DeleteCredential_Call) RunAndReturn(run func(ctx context.Context, credentialID []byte, accountID primitive.ObjectID) error) *WebAuthnCredentialRepository_DeleteCredential_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCredentialByID provides a mock function for the type WebAuthnCredentialRepository
func (_mock *WebAuthnCredentialRepository) DeleteCredentialByID(ctx context.Context, credentialID primitive.ObjectID, accountID primitive.ObjectID) error {
	ret := _mock.Called(ctx, credentialID, accountID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCredentialByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, primitive.ObjectID) error); ok {
		r0 = returnFunc(ctx, credentialID, accountID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WebAuthnCredentialRepository_DeleteCredentialByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCredentialByID'
type WebAuthnCredentialRepository_DeleteCredentialByID_Call struct {
	*mock.Call
}

// DeleteCredentialByID is a helper method to define mock.On call
//   - ctx context.Context
//   - credentialID primitive.ObjectID
//   - accountID primitive.ObjectID
func (_e *WebAuthnCredentialRepository_Expecter) DeleteCredentialByID(ctx interface{}, credentialID interface{}, accountID interface{}) *WebAuthnCredentialRepository_DeleteCredentialByID_Call {
	return &WebAuthnCredentialRepository_DeleteCredentialByID_Call{Call: _e.mock.On("DeleteCredentialByID", ctx, credentialID, accountID)}
}

func (_c *WebAuthnCredentialRepository_DeleteCredentialByID_Call) Run(run func(ctx context.Context, credentialID primitive.ObjectID, accountID primitive.ObjectID)) *WebAuthnCredentialRepository_DeleteCredentialByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 primitive.ObjectID
		if args[1] != nil {
			arg1 = args[1].(primitive.ObjectID)
		}
		var arg2 primitive.ObjectID
		if args[2] != nil {
			arg2 = args[2].(primitive.ObjectID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *WebAuthnCredentialRepository_DeleteCredentialByID_Call) Return(err error) *WebAuthnCredentialRepository_DeleteCredentialByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WebAuthnCredentialRepository_DeleteCredentialByID_Call) RunAndReturn(run func(ctx context.Context, credentialID primitive.ObjectID, accountID primitive.ObjectID) error) *WebAuthnCredentialRepository_DeleteCredentialByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCredentialByID provides a mock function for the type WebAuthnCredentialRepository
func (_mock *WebAuthnCredentialRepository) GetCredentialByID(ctx context.Context, credentialID primitive.ObjectID) (*model.Credential, error) {
	ret := _mock.Called(ctx, credentialID)

	if len(ret) == 0 {
		panic("no return value specified for GetCredentialByID")
	}

	var r0 *model.Credential
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) (*model.Credential, error)); ok {
		return returnFunc(ctx, credentialID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) *model.Credential); ok {
		r0 = returnFunc(ctx, credentialID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Credential)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = returnFunc(ctx, credentialID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WebAuthnCredentialRepository_GetCredentialByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCredentialByID'
type WebAuthnCredentialRepository_GetCredentialByID_Call struct {
	*mock.Call
}

// GetCredentialByID is a helper method to define mock.On call
//   - ctx context.Context
//   - credentialID primitive.ObjectID
func (_e *WebAuthnCredentialRepository_Expecter) GetCredentialByID(ctx interface{}, credentialID interface{}) *WebAuthnCredentialRepository_GetCredentialByID_Call {
	return &WebAuthnCredentialRepository_GetCredentialByID_Call{Call: _e.mock.On("GetCredentialByID", ctx, credentialID)}
}

func (_c *WebAuthnCredentialRepository_GetCredentialByID_Call) Run(run func(ctx context.Context, credentialID primitive.ObjectID)) *WebAuthnCredentialRepository_GetCredentialByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 primitive.ObjectID
		if args[1] != nil {
			arg1 = args[1].(primitive.ObjectID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WebAuthnCredentialRepository_GetCredentialByID_Call) Return(credential *model.Credential, err error) *WebAuthnCredentialRepository_GetCredentialByID_Call {
	_c.Call.Return(credential, err)
	return _c
}

func (_c *WebAuthnCredentialRepository_GetCredentialByID_Call) RunAndReturn(run func(ctx context.Context, credentialID primitive.ObjectID) (*model.Credential, error)) *WebAuthnCredentialRepository_GetCredentialByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCredentials provides a mock function for the type WebAuthnCredentialRepository
func (_mock *WebAuthnCredentialRepository) GetCredentials(ctx context.Context, accountID primitive.ObjectID) ([]model.Credential, error) {
	ret := _mock.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetCredentials")
	}

	var r0 []model.Credential
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) ([]model.Credential, error)); ok {
		return returnFunc(ctx, accountID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) []model.Credential); ok {
		r0 = returnFunc(ctx, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Credential)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = returnFunc(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WebAuthnCredentialRepository_GetCredentials_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCredentials'
type WebAuthnCredentialRepository_GetCredentials_Call struct {
	*mock.Call
}

// GetCredentials is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID primitive.ObjectID
func (_e *WebAuthnCredentialRepository_Expecter) GetCredentials(ctx interface{}, accountID interface{}) *WebAuthnCredentialRepository_GetCredentials_Call {
	return &WebAuthnCredentialRepository_GetCredentials_Call{Call: _e.mock.On("GetCredentials", ctx, accountID)}
}

func (_c *WebAuthnCredentialRepository_GetCredentials_Call) Run(run func(ctx context.Context, accountID primitive.ObjectID)) *WebAuthnCredentialRepository_GetCredentials_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 primitive.ObjectID
		if args[1] != nil {
			arg1 = args[1].(primitive.ObjectID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WebAuthnCredentialRepository_GetCredentials_Call) Return(credentials []model.Credential, err error) *WebAuthnCredentialRepository_GetCredentials_Call {
	_c.Call.Return(credentials, err)
	return _c
}

func (_c *WebAuthnCredentialRepository_GetCredentials_Call) RunAndReturn(run func(ctx context.Context, accountID primitive.ObjectID) ([]model.Credential, error)) *WebAuthnCredentialRepository_GetCredentials_Call {
	_c.Call.Return(run)
	return _c
}

// GetCredentialsCount provides a mock function for the type WebAuthnCredentialRepository
func (_mock *WebAuthnCredentialRepository) GetCredentialsCount(ctx context.Context, accountID primitive.ObjectID) (int, error) {
	ret := _mock.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetCredentialsCount")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) (int, error)); ok {
		return returnFunc(ctx, accountID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) int); ok {
		r0 = returnFunc(ctx, accountID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = returnFunc(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WebAuthnCredentialRepository_GetCredentialsCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCredentialsCount'
type WebAuthnCredentialRepository_GetCredentialsCount_Call struct {
	*mock.Call
}

// GetCredentialsCount is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID primitive.ObjectID
func (_e *WebAuthnCredentialRepository_Expecter) GetCredentialsCount(ctx interface{}, accountID interface{}) *WebAuthnCredentialRepository_GetCredentialsCount_Call {
	return &WebAuthnCredentialRepository_GetCredentialsCount_Call{Call: _e.mock.On("GetCredentialsCount", ctx, accountID)}
}

func (_c *WebAuthnCredentialRepository_GetCredentialsCount_Call) Run(run func(ctx context.Context, accountID primitive.ObjectID)) *WebAuthnCredentialRepository_GetCredentialsCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 primitive.ObjectID
		if args[1] != nil {
			arg1 = args[1].(primitive.ObjectID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WebAuthnCredentialRepository_GetCredentialsCount_Call) Return(n int, err error) *WebAuthnCredentialRepository_GetCredentialsCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *WebAuthnCredentialRepository_GetCredentialsCount_Call) RunAndReturn(run func(ctx context.Context, accountID primitive.ObjectID) (int, error)) *WebAuthnCredentialRepository_GetCredentialsCount_Call {
	_c.Call.Return(run)
	return _c
}

// SaveCredential provides a mock function for the type WebAuthnCredentialRepository
func (_mock *WebAuthnCredentialRepository) SaveCredential(ctx context.Context, credential webauthn.Credential, accountID primitive.ObjectID) error {
	ret := _mock.Called(ctx, credential, accountID)

	if len(ret) == 0 {
		panic("no return value specified for SaveCredential")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, webauthn.Credential, primitive.ObjectID) error); ok {
		r0 = returnFunc(ctx, credential, accountID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WebAuthnCredentialRepository_SaveCredential_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveCredential'
type WebAuthnCredentialRepository_SaveCredential_Call struct {
	*mock.Call
}

// SaveCredential is a helper method to define mock.On call
//   - ctx context.Context
//   - credential webauthn.Credential
//   - accountID primitive.ObjectID
func (_e *WebAuthnCredentialRepository_Expecter) SaveCredential(ctx interface{}, credential interface{}, accountID interface{}) *WebAuthnCredentialRepository_SaveCredential_Call {
	return &WebAuthnCredentialRepository_SaveCredential_Call{Call: _e.mock.On("SaveCredential", ctx, credential, accountID)}
}

func (_c *WebAuthnCredentialRepository_SaveCredential_Call) Run(run func(ctx context.Context, credential webauthn.Credential, accountID primitive.ObjectID)) *WebAuthnCredentialRepository_SaveCredential_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 webauthn.Credential
		if args[1] != nil {
			arg1 = args[1].(webauthn.Credential)
		}
		var arg2 primitive.ObjectID
		if args[2] != nil {
			arg2 = args[2].(primitive.ObjectID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *WebAuthnCredentialRepository_SaveCredential_Call) Return(err error) *WebAuthnCredentialRepository_SaveCredential_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WebAuthnCredentialRepository_SaveCredential_Call) RunAndReturn(run func(ctx context.Context, credential webauthn.Credential, accountID primitive.ObjectID) error) *WebAuthnCredentialRepository_SaveCredential_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCredential provides a mock function for the type WebAuthnCredentialRepository
func (_mock *WebAuthnCredentialRepository) UpdateCredential(ctx context.Context, credential webauthn.Credential, accountID primitive.ObjectID) error {
	ret := _mock.Called(ctx, credential, accountID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCredential")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, webauthn.Credential, primitive.ObjectID) error); ok {
		r0 = returnFunc(ctx, credential, accountID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WebAuthnCredentialRepository_UpdateCredential_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCredential'
type WebAuthnCredentialRepository_UpdateCredential_Call struct {
	*mock.Call
}

// UpdateCredential is a helper method to define mock.On call
//   - ctx context.Context
//   - credential webauthn.Credential
//   - accountID primitive.ObjectID
func (_e *WebAuthnCredentialRepository_Expecter) UpdateCredential(ctx interface{}, credential interface{}, accountID interface{}) *WebAuthnCredentialRepository_UpdateCredential_Call {
	return &WebAuthnCredentialRepository_UpdateCredential_Call{Call: _e.mock.On("UpdateCredential", ctx, credential, accountID)}
}

func (_c *WebAuthnCredentialRepository_UpdateCredential_Call) Run(run func(ctx context.Context, credential webauthn.Credential, accountID primitive.ObjectID)) *WebAuthnCredentialRepository_UpdateCredential_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 webauthn.Credential
		if args[1] != nil {
			arg1 = args[1].(webauthn.Credential)
		}
		var arg2 primitive.ObjectID
		if args[2] != nil {
			arg2 = args[2].(primitive.ObjectID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *WebAuthnCredentialRepository_UpdateCredential_Call) Return(err error) *WebAuthnCredentialRepository_UpdateCredential_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WebAuthnCredentialRepository_UpdateCredential_Call) RunAndReturn(run func(ctx context.Context, credential webauthn.Credential, accountID primitive.ObjectID) error) *WebAuthnCredentialRepository_UpdateCredential_Call {
	_c.Call.Return(run)
	return _c
}
