FROM golang:1.25.7

RUN apt update; apt install -y make

WORKDIR /app

# Copy golang dependency manifests
COPY api/go.mod .
COPY api/go.sum .

# Copy the DNS libs
COPY ../libs/ /libs

# Cache the downloaded dependency in the layer.
RUN go mod download

COPY api/ .

RUN GOOS=linux GOARCH=amd64 go build -o /app/dnsapi -v .
RUN GOOS=linux GOARCH=amd64 go build -o /bin/healthcheck ./cmd/healthcheck
CMD ["./dnsapi"]
